### ISSUE TITLE
Node networks: Hiking map doesn't seem to receive any updates since a week or so

### ISSUE THREAD

**Issue by jdhoek** [vmarc/knooppuntnet#101]
The [hiking map](https://knooppuntnet.nl/en/map/rwn) seems to be stuck since a week ago (perhaps longer).

New routes are analysed and picked up by the tool, but not rendered ([example segment](https://knooppuntnet.nl/en/route/11289540)).

![Screenshot from 2020-07-19 21-40-32](https://user-images.githubusercontent.com/683699/87883599-d62c5480-ca08-11ea-8996-92ee0359e1cb.png)

**Comment by vmarc** [comment]
@jdhoek thanks for reporting this problem

About a week ago the processing of the tiles has moved from a server in Amsterdam to a new bigger server in Germany. It looks like I forgot to start the synchronization of the tiles between that new analysis server and the webserver. I have just started it, and the map looks better now:

![solution](https://user-images.githubusercontent.com/6596480/87884193-f78f3f80-ca0c-11ea-8004-107ed43c47ee.png)

**Comment by jdhoek** [comment]
It looks up-to-date now. Thanks!
