### ISSUE TITLE
Fietsnetwerk Belgisch Limburg is uit de lijst van netwerken verdwenen

### ISSUE THREAD

**Issue by dvdhoven** [vmarc/knooppuntnet#108]
Het fietsnetwerk B Limburg is uit het overzicht verdwenen.
Op de knooppuntkaart worden de routes als routewees gemeld.

Link naar B Limburg https://www.openstreetmap.org/relation/155047

Vriendelijke groeten,
Dick van den Hoven

**Comment by vmarc** [comment]
Zelfde probleem als #105 (Couchdb versie 3.0.1).
