### ISSUE TITLE
Analyse -  Verzoek ondersteuning fietsrotonde routerelatie

### ISSUE THREAD

**Issue by pelderson** [vmarc/knooppuntnet#109]
Dit heeft geen haast! Het verzoek is om in de validaties de "fietsrotonde" te ondersteunen. Daarmee bedoel ik een rondgesloten fietsroute waarin meerdere knooppunten voorkomen met hetzelfde nummer. Als voorbeeld het Keizer Karelplein in Nijmegen, waar 4 gesplitste fietsroutes op "landen". 
![image](https://user-images.githubusercontent.com/38458314/90404416-ab362e80-e0a2-11ea-8cb5-878bc6a7a26d.png)

Meerdere aansluitende gelijkgenummerde knooppunten in 1 route wordt door Knooppuntnet goed gevonden. Maar als die route dan rondgesloten wordt volgt er een foutfeit, ik dacht "Overbodig segment". Daarom heb ik nu twee relaties op de rotonde gelegd, dan werkt het foutloos voor de validaties en voor de planner. 

Er is een werkend alternatief, dus het heeft geen haast, en als het niet kan dan kan het niet. Maar het zou fijn zijn als deze methodiek helemaal foutloos werkend te krijgen is, want voor nieuwe mappers is het zo veel gemakkelijker te begrijpen en op te pakken dan de tentakelmethode (jij en Dick zijn vermoedelijk de enigen die dat begrijpen...) , en er hoeven geen drie- en vierdubbele stukken gemapt te worden zoals bij de "rondsluitmethode" waarbij elke route die op de rotonde landt, vervolgens een eigen terugweg over de hele rotonde krijgt.

**Comment by pelderson** [comment]
PS. Ik vraag het voor fietsroutes en een mooie rotonde, maar de vraag geldt natuurlijk voor alle soorten routes en ook als de deelknooppunten niet in zo'n mooi rondje staan!

**Comment by vmarc** [comment]
De situatie van fietsrotonde is opgenomen in de case study [Issue109_RoundaboutRoute](https://github.com/vmarc/knooppuntnet/blob/develop/server/src/test/scala/kpn/server/analyzer/engine/analysis/caseStudies/Issue109_RoundaboutRoute.scala).  De analyze herkent de situatie nu.

De rotonde is terug 1 route [45-45](https://experimental.knooppuntnet.nl/nl/analysis/route/11512870/map) gemaakt.
