### ISSUE TITLE
Route planner - remove "onto" from the navigation instructions

### ISSUE THREAD

**Issue by vmarc** [vmarc/knooppuntnet#110]
Currently, in the route directions the word "onto" is used in the instructions to precede the streetname.

- Head west onto Stationsstraat
- Turn left onto Rouwmoer
- Turn right onto Nolsebaan

[segubi](https://www.openstreetmap.org/user/segubi) reported this does not work very well in German:

> For correct German still would remain the need for the correct article for the street depending on the gender. Don't know what usual navigational systems do with it... I think it's more useful to ignore that and avoid the article...

As suggested, the easy way out is to take away the word "onto" from the navigation instructions.

**Comment by pelderson** [comment]
Why not use ': ' (colon space) or ' (name)'  (space name-in-parentheses). That will work in all four languages.

**Comment by vmarc** [comment]
@pelderson thanks for the suggestions.

"onto" changed to ": " in release 3.0.0-alpha-42.
