### ISSUE TITLE
[Planner] Loading a gpx does not seem to work

### ISSUE THREAD

**Issue by pelderson** [vmarc/knooppuntnet#112]
[Planner] Loading a gpx does not seem to work

**Comment by vmarc** [comment]
@pelderson thanks for reporting this problem

This regression is the result of a code cleanup that went a bit too far. Should be fixed in release 3.0.0-alpha-49.

**Comment by vmarc** [comment]
Problem solved. In the mean while the gpx upload button has been temporarily removed. The button is part of the solution for issue #96  (surveydate helper function), and that function is not complete yet. Leaving the button in at this moment only causes confusion.
