### ISSUE TITLE
Kan niet meer inloggen op experimental.knooppuntnet.be

### ISSUE THREAD

**Issue by hgcvm** [vmarc/knooppuntnet#113]
Het inloggen werkt bij mij niet meer. Ik wordt doorverwezen naar OSM, geef daar toestemming. Browser venster keert terug naar knooppuntnet.be, maar blijft dan hangen op "logging in...."

Ik heb dit zowel in Chromium als in Firefox.

**Comment by vmarc** [comment]
@hgcvm many thanks for reporting this problem!

It seems there is a change in the interaction between knooppuntnet and the openstreetmap api. When knooppuntnet requests the user data, the openstreetmap api now returns a json response instead of xml as it used to.

I will investigate further...

**Comment by vmarc** [comment]
I have changed the code to explicitly request an XML response when retrieving user details from the openstreetmap api, and now the openstreetmap response contains XML instead of JSON, and the login works again for me.

@hgcvm can you try again?

**Comment by hgcvm** [comment]
OK, fixed. Thank a lot!!

**Comment by vmarc** [comment]
Problem was related to this [change](https://github.com/openstreetmap/openstreetmap-website/pull/2839) in the OpenStreetMap api.
