### ISSUE TITLE
Analysis - expected_rXn_route_relations does not count non-network routes

### ISSUE THREAD

**Issue by pelderson** [vmarc/knooppuntnet#117]
The expected._rXn_route_relations check is a strong detector of network problems. But it only counts routes within a network. I think non-network routes ("orphan" routes) should be counted as well, because the integrity of the total network is not limited to one network relation.

In fact the presentation on the node detail page is all right, but if all the routes are "orphans", no "fact" is raised. 

Since the introduction of network:type=node_network, network membership is no longer required to determine that a route is a node network route, so I think non-network node2node routes should be taken into account for the expected.... check. At least during analysis by administrative area.

**Comment by vmarc** [comment]
Implemented in experimental.knooppuntnet.nl (will be deployed in knooppuntnet.nl with release v3.2).
