### ISSUE TITLE
Planner - Non-network nodes do not show 

### ISSUE THREAD

**Issue by pelderson** [vmarc/knooppuntnet#118]
It looks like "orphan" nodes do not show up on the planner. Since they are tagged with network:type=node_network, this restriction seems no longer necessary.

**Comment by vmarc** [comment]
At this moment orphan node [R91](https://knooppuntnet.nl/nl/analysis/node/1457877780/map) is shown on the map. Which node does not show up?

For a new orphan node, it could be that there is a delay before it is shown on the map (max 2 hours I think).

**Comment by pelderson** [comment]
I added a bunch of nodes and routes yesterday (eg https://knooppuntnet.nl/nl/analysis/node/43536233 ) , on Schouwen-Duiveland, without adding them to the netwerk, and more this morning from 8.00 onwards. I can see the routes on the map, and some nodes. The nodes shown are mostly pre-existing members orf the network relation, but I see now that some are not, e.g. https://knooppuntnet.nl/nl/analysis/node/2979100594 

Maybe it takes a little longer than expected? I am used to a few hours delay, but in this case the routes do show up after a few hours but most of the nodes don't.

**Comment by vmarc** [comment]
Node 2979100594 seems to show up fine for me. Does refreshing the browserwindow make a difference?

![node-2979100594](https://user-images.githubusercontent.com/6596480/98243809-c3656d80-1f6e-11eb-9ff1-4b898117fb1d.png)

**Comment by pelderson** [comment]
node 43 shows up, but node 44 (uploaded in the same session!) does not : https://knooppuntnet.nl/nl/analysis/node/1257270342

One difference I can see is that 44 is in a route which actually is in a network relation.

**Comment by pelderson** [comment]
Just looked again and all the nodes show up!

**Comment by vmarc** [comment]
Yep. There was no problem for "real orphan nodes" (nodes not in any network and not in any orphan route), these were included in the map tiles. But nodes from orphan routes only (and not otherwise part of a network) were not included in the map tiles.

This has been fixed in the code, and the tiles were re-generated.

**Comment by pelderson** [comment]
vmarc strikes again!
