### ISSUE TITLE
Network nodes without a reference - as a feature, not an error!

### ISSUE THREAD

**Issue by pelderson** [vmarc/knooppuntnet#119]
We encounter instances of network nodes without a node number. We had them down as errors, but they are used systematically by some operators. 
These are actual switch points with the arrow shields pointing to different directions/nodes, they just do not carry a number and are not end points of any route. At least one direction is common to two routes. 

I think this setup should be accommodated. 

Proposal
======
I propose to tag these nodes as regular nodes, with the (to be) reserved rwn_ref=*
Analysis should allow middle nodes tagged rwn_ref=* in the routes. Comparable to how nodes with the same number as one of the end nodes are allowed.

This should in principle give applications the information they need for rendering, planning and exporting the routes.
I think the handling for Planner also resembles the way that nodes with the same number as one of the end nodes are handled.

Status
====
The problem is recognised and I am told for bicycle routing a similar solution is already in use.
There is no broad consensus about the proposed solution.
For the discussion, it would help to know if the assumptions in the above are correct. Maybe a better solution springs to mind?

**Comment by pelderson** [comment]
https://knooppuntnet.nl/nl/analysis/node/354906288 is my test node

**Comment by vmarc** [comment]
Following changes have been done in release 3.0.3:
- routes with star-nodes (rwn_ref=*) no longer receive fact RouteRedundantNodes (OvertolligKnooppunt)
- the star-nodes are displayed with a small circle without node name in the planner map
- star-nodes cannot be used to plan a route (cannot click the node, or use as drag target)
- it is still possible to ctrl-click the star-node in the planner map to navigate to the node details page

**Comment by pelderson** [comment]
Looks fine for walking! 
Does it also apply to cycling and to the other modes of transport?

**Comment by vmarc** [comment]
Yes, this should also work for cycling, horse-riding, motorboat, canoe and inline-skating.

**Comment by pelderson** [comment]
I'll bring it to the forum.
