### ISSUE TITLE
rwn_expected_route_relations=3 and node has 2 relations associated with it, but no error

### ISSUE THREAD

**Issue by hgcvm** [vmarc/knooppuntnet#120]
This node https://knooppuntnet.nl/en/analysis/node/1475927236 has only two relations connected to it. But it has rwn_expected_route_relations=3. So it should show up as an error, or not?

Please keep in mind, Bulskampveld is currently being redesigned, and we are already mapped the new signs as they appear on the ground. So that network is currently a big mess.

**Comment by vmarc** [comment]
The tag interpreted by knooppuntnet is _expected_rwn_route_relations_ (see [wiki](https://wiki.openstreetmap.org/wiki/Cycle_Node_Network_Tagging#.28A.29_Node_tagging)). The tag _rwn_expected_route_relations_ in your example node is ignored.

**Comment by hgcvm** [comment]
Oh, OK. I used the JOSM preset. I should go update the JOSM preset then.
I will have a look with overpass where else I made this mistake.
THanks for pointing it out.

**Comment by hgcvm** [comment]
Currently 102 nodes have "rwn_expected_route_relations" in Belgium. I guess I will update them all in one go.

**Comment by vmarc** [comment]
Thanks!
