### ISSUE TITLE
Map view "Node and route quality status" difference in colours in Legend and on map itself

### ISSUE THREAD

**Issue by hgcvm** [vmarc/knooppuntnet#122]
This is only a minor remarks,

Nodes that are not OK are blue on the map, but in the legend it is dark brown/dark red

**Comment by vmarc** [comment]
Fixed in release v3.1.1

![legend](https://user-images.githubusercontent.com/6596480/103344960-5fec4d80-4a90-11eb-9bdc-edf881b12e46.png)
