### ISSUE TITLE
Interaction bug in Map mode

### ISSUE THREAD

**Issue by StephaneChatty** [vmarc/knooppuntnet#129]
When in Map mode (in Analysis for sure, probably in Routing too), if I want to pan I press my finger or mouse button and move the map. Except than when I my finger or mouse pointer is too close to a node, the app switches to the page of said node even before I release my finger/button.

The normal behaviour, in most UIs, is to do that only when:
 - the finger/button is released
 - there has been no significant movement between press and release (any significant move would engage the pan mode)

This makes navigating in the map somewhat frustrating, especially since pan/zoom parameters are lost when coming back to the page.

**Comment by vmarc** [comment]
@StephaneChatty thanks for reporting this problem, I will try to fix this

**Comment by vmarc** [comment]
The map interaction has been changed in version 3.1.2.

Selecting a node/route/flag/poi by single-click now feels a bit slower than it used to be. Perhaps the cursor should change upon single-click to give faster feedback to user that item has been clicked and request to server has been issued.

**Comment by StephaneChatty** [comment]
> Le 24 janv. 2021 à 11:05, vmarc <notifications@github.com> a écrit :
> 
> 
> The map interaction has been changed in version 3.1.2.
> 
Much better, thanks!
> Selecting a node/route/flag/poi by single-click now feels a bit slower than it used to be. Perhaps the cursor should change upon single-click to give faster feedback to user that item has been clicked and request to server has been issued.
> 
> 

Either that or a color change for the clicked object.

Cheers,

St.

**Comment by vmarc** [comment]
Re-opened to improve user feedback upon single-click: either cursor change for the duration of the round-trip to the server, or a color change for the clicked object.
