### ISSUE TITLE
No facts are shown

### ISSUE THREAD

**Issue by MaartenDeen** [vmarc/knooppuntnet#13]
https://knooppuntnet.nl/nl/network-facts/2240269

On the left after facts it says 68, the old site also show these facts (mostly nodes where the integrityCheckFailed "expected_rwn_route_relations" failed) but the main screen says "Venlo
Facts
no facts"

**Comment by vmarc** [comment]
@MaartenDeen thanks for reporting this problem.

Only route related facts were shown in the fact page. The code has been further completed to also include all other (network and node related) facts.
