### ISSUE TITLE
[Planner] Search is broken?

### ISSUE THREAD

**Issue by pelderson** [vmarc/knooppuntnet#135]
![image](https://user-images.githubusercontent.com/38458314/104568670-aaed8f80-5650-11eb-8171-3610ef5ece8f.png)

Internet connection is good (I just started the planner and switched modes). It's not incidental, I have tried it for several days now.

**Comment by vmarc** [comment]
@pelderson thanks for reporting this problem

Further detail about what is going on, is in the browser console:

> Access to fetch at 'https://photon.komoot.de/api/?q=essen&limit=5&lang=en' from origin 'https://knooppuntnet.nl' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

I will investigate how to fix this.

**Comment by vmarc** [comment]
Fixed in version 3.1.2

The geo-locater now uses the new address komoot.io (instead of komoot.de) where the CORS policy problem does not exist.
