### ISSUE TITLE
Kaartachtergrond toont buurten (place=neighbourhood) wel, maar wijken (place=quarter) niet

### ISSUE THREAD

**Issue by jdhoek** [vmarc/knooppuntnet#136]
De gekozen achtergrondstijl toont netjes de buurtnamen waar die ingetekend zijn, maar wijknamen niet; `place=neighbourhood` wordt dus wel getekend, maar `place=quarter` niet.

Dit is denk ik een upstream bug in de kaartstijl die gebruikt wordt. Wat is deze stijl?

Voorbeeld uit OSM-Carto (wijken Nijlân en Huizum-West staan erop, buurt Hollanderwijk ook):

![Screenshot from 2021-01-15 19-15-09](https://user-images.githubusercontent.com/683699/104763351-08bfcb80-5766-11eb-9c90-43f5c0356a94.png)

Dit is op knooppuntnet.nl (bovengenoemde wijknamen ontbreken):

![Screenshot from 2021-01-15 19-16-36](https://user-images.githubusercontent.com/683699/104763457-33aa1f80-5766-11eb-8fd7-dbeed2c5f0ce.png)

**Comment by vmarc** [comment]
The style is based on [osm-liberty](https://github.com/maputnik/osm-liberty).

The vector tiles on which this style is applied are generated using [OpenMapTiles](https://openmaptiles.org/).

I guess that the definition that determines 'place' is here: [place.yaml](https://github.com/openmaptiles/openmaptiles/blob/master/layers/place/place.yaml)
See also: [schema](https://openmaptiles.org/schema/#place)
See also: [mapping_diagram.png](https://github.com/openmaptiles/openmaptiles/blob/master/layers/place/mapping_diagram.png)

The mapping does seem to include "neighboorhood", but not "quarter". 

I am not sure exactly how all this works. Maybe "quarter" should be inserted after line 177 in [mapping.yaml](https://github.com/openmaptiles/openmaptiles/blob/master/layers/place/mapping.yaml).


Note that the background map layer currently reflects the OpenStreetMap data from Oct 24th 2020.  At this moment, the generation of the background tiles is a process that still includes a number of manual steps and takes about a week or so (see: [tile docs](https://github.com/vmarc/knooppuntnet/blob/develop/docs/tiles.md)). I try to do this process about once per month, but lately it fails in [08-generate-tiles-12.sh](https://github.com/vmarc/knooppuntnet/blob/develop/server/src/main/resources/kpn/scripts/tiles/08-generate-tiles-12.sh), and I have not been able to find the time yet to figure out what is going wrong.

If you know of a better way of generating background tiles (and perhaps are able to help with this), I am open for suggestions.

**Comment by jdhoek** [comment]
> If you know of a better way of generating background tiles (and perhaps are able to help with this), I am open for suggestions.

No idea unfortunetely.

**Comment by vmarc** [comment]
@jdhoek today I have started a new background-tile generation, including your changes to OpenMapTiles (thanks!). So, perhaps quarters start to appear in about one week...

**Comment by jdhoek** [comment]
I think https://github.com/maputnik/osm-liberty/issues/92 may need to be resolved first. It'll probably take some time for both projects to release a new version too. It's coming though!

**Comment by vmarc** [comment]
![quarter](https://user-images.githubusercontent.com/6596480/105628137-5cec3f00-5e3b-11eb-8387-856514efc02c.png)

**Comment by jdhoek** [comment]
Nice!
