### ISSUE TITLE
Map appearance option 'Surface' defaults to 'unpaved'

### ISSUE THREAD

**Issue by jdhoek** [vmarc/knooppuntnet#142]
The default appearance option ('Surface') shows the routes in two colours:

![Screenshot from 2021-01-24 14-27-55](https://user-images.githubusercontent.com/683699/105631796-8794c280-5e50-11eb-94cc-747eacd5543b.png)

It looks like ways without any `surface=*` tags are classified as 'unpaved'. This is probably not the best default — in an urban environment most ways will be paved.

I would suggest adding a third classification of 'unknown'. This can also guide any mapper interested in completing the paved/unpaved classification of a route to sections that need tagging.

**Comment by vmarc** [comment]
@jdhoek I like your suggestion of adding a classification _"unknown"_

See also #106 (add classification _"cobblestone"_).

The _"paved/unpaved"_ logic is in [SurfaceAnalyzer](https://github.com/vmarc/knooppuntnet/blob/develop/server/src/main/scala/kpn/server/analyzer/engine/analysis/route/segment/SurfaceAnalyzer.scala).

Line 94 seems to suggest that the default without surface tag would be _"paved"_ (not _"unpaved"_).

According to this logic, in the absence of a _"surface"_ tag, _"unpaved"_ is still given for:

> tracktype=grade2
> tracktype=grade3
> tracktype=grade4
> tracktype=grade5
> 
> smoothness=very_bad
> smoothness=horrible
> smoothness=very_horrible
> smoothness=impassable
> 
> highway=bridleway    <-- ???
> highway=track    <-- ???
> highway=unsurfaced
> highway=footway    <-- ???
> highway=unpaved
> highway=path    <-- ???

@jdhoek can you give an example of where you see an unexpected _"unpaved"_ (without _"surface"_ tag)?  Does it match any of the rules above?

Looking back at these rules, maybe following rules would better be removed?

> highway=bridleway
> highway=track
> highway=footway
> highway=path

**Comment by jdhoek** [comment]
> Line 94 seems to suggest that the default without surface tag would be "paved" (not "unpaved").

Sounds right for a large section of the highway classes. The [wiki](https://wiki.openstreetmap.org/wiki/Key:surface) documents:

> For roads for motor vehicles there there is normally an assumption that the surface is surface=paved unless otherwise stated.

> @jdhoek can you give an example of where you see an unexpected "unpaved" (without "surface" tag)? Does it match any of the rules above?

Mostly `highway=footway` that are missing `surface`. [Like this one](https://www.openstreetmap.org/way/896290063).

I think there are a few footway-subtypes that can be considered paved by default:

```
footway=crossing
footway=traffic_island / footway=island 
footway=sidewalk
```

These might be useful in `SurfaceAnalyzer`. `footway=crossing` follows the default assumption noted on the wiki that roads for motor vehicles are considered paved unless otherwise stated. `highway=crossing` crosses such roads.

Considering sidewalks paved by default may be Netherlands-centric thinking though.

I think bridleways are usually unpaved (sand mostly), and track may be expected to be unpaved too. `highway=path` is so generic that it tends towards 'unknown'.

**Comment by Henry00572** [comment]
I think the SurfaceAnalyzer should also take the tag `cycleway:surface` into account. This is used by StreetComplete on `segregated` `highway`s for `foot`and `bicycle`. Tagging these `highways` with an additional `surface` key would be redundant.

**Comment by vmarc** [comment]
@Henry00572 do you perhaps have some examples of routes with ways with tag `cycleway:surface`? That would be useful for testing.

**Comment by Henry00572** [comment]
An example would be https://knooppuntnet.nl/de/map/cycling?plan=37unif-2vneog which goes through https://www.openstreetmap.org/way/428698265. This way has the tags `bicycle=designated` + `foot=designated` + `segregated=yes` + `cycleway:surface=paving_stones` and not `surface=*`.

**Comment by vmarc** [comment]
The logic of the SurfaceAnalyzer has been changed to  take `cycleway:surface` and `footway:surface` tags into account.

Before:

![way-before](https://user-images.githubusercontent.com/6596480/193082903-102f93a6-ac45-453d-af14-c8a0c069a8a9.png)

After:

![way-after-2](https://user-images.githubusercontent.com/6596480/193083479-ffb2fe30-199f-404a-9903-fd4f641f140b.png)

**Comment by vmarc** [comment]
As suggested by @jdhoek

> `highway=path` is so generic that it tends towards 'unknown'.

the SurfaceAnalyzer now considers the surface to be `unknown` for `highway=path` when there are no further tags from which the surface can be derived. In the following example, the unknown surfaces are displayed in blue (in the production application at this moment they are still displayed in green):

![way](https://user-images.githubusercontent.com/6596480/193087021-fa3d40ed-866c-4ef9-8c7c-df2a01336104.png)

**Comment by vmarc** [comment]
The new legend:

![legend](https://user-images.githubusercontent.com/6596480/193144499-1a17bfb7-7579-4c42-a0e7-9db794290d13.png)
