### ISSUE TITLE
Node 60 shown as "

### ISSUE THREAD

**Issue by vmarc** [vmarc/knooppuntnet#153]
Node [60](https://knooppuntnet.nl/nl/analysis/node/43670514/map) is not shown on the map. Instead, a double quote (") is shown as the node name.

![a-declutter-true-1](https://user-images.githubusercontent.com/6596480/111900539-740e6e00-8a33-11eb-86a8-326fa40685f8.png)

Thanks to [FrankOverman](https://www.openstreetmap.org/user/FrankOverman) for reporting this problem.

**Comment by vmarc** [comment]
When zooming futher in to the highest zoomlevels, node [60](https://knooppuntnet.nl/nl/analysis/node/43670514/map) is shown:

![a-declutter-true-zoomed-in](https://user-images.githubusercontent.com/6596480/111900739-90f77100-8a34-11eb-9a4c-827e828d97f3.png)

The [node with the double quote as name](https://www.openstreetmap.org/node/7091836586) is a separate node.  Investigation learns that it is parameter _"declutter"_ in the [Openlayers](https://openlayers.org/) VectorTileLayer that causes node 60 to only be shown at the highest zoomlevels.

When setting  _"declutter"_ to false, node 60 is also shown at lower zoomlevels also:

![a-declutter-false-1](https://user-images.githubusercontent.com/6596480/111901070-13346500-8a36-11eb-9765-08f595a6817e.png).

The effect of setting the _"declutter"_ parameter to true is that for map objects that are very close to eachother, only 1 object is shown instead of multiple overlapping objects.  The nodes [60](https://knooppuntnet.nl/nl/analysis/node/43670514) and [double-quote-node](https://www.openstreetmap.org/node/7091836586) are only 5 meters appart.

But: setting  _"declutter"_ to false, has a negative impact on the way many of the other nodes are displayed, as shown here:

![declutter-false-annotated](https://user-images.githubusercontent.com/6596480/111901188-bf764b80-8a36-11eb-92db-eeb1811fd16b.png)

Not so nice:
- node 61 is cut off at the tile boundary
- the way nodes 25 and 45 are displayed is a bit messy

This is what the map looks like with _"declutter"_ parameter set to true:

![declutter-true-annotated](https://user-images.githubusercontent.com/6596480/111901240-12500300-8a37-11eb-882d-2fa72b0071e4.png)

I suspect that the reason for introducing the [double-quote-node](https://www.openstreetmap.org/node/7091836586) was that routes with the same node as start- and end-node (loop routes) were not correctly processed in the past. I believe that removing that node and closing the loop would now work ok. See for example [62-62](https://knooppuntnet.nl/nl/analysis/route/11772920/map) and [demo](https://knooppuntnet.nl/nl/demo/via-loop) for a route that is a loop.

Conclusion: I would propose to leave the knooppuntnet code as-is, and try to close the loop to create a loop route 60-60 to resolve this particular problem. I would expect this will display node 60 nicely and better reflect reality on the ground.

**Comment by elnfrov** [comment]
I agree with the proposed solution.
Thanks for attending this one!

**Comment by elnfrov** [comment]
Updated the route in OSM:
[https://www.openstreetmap.org/changeset/101446462](url)
[https://overpass-api.de/achavi/?changeset=101446462](url)
Begin- & end-piece of highway are now the same one: let's see how this renders.

**Comment by elnfrov** [comment]
Status: route / relation 60-60 now gives issues; as these are related to issue 114, that one has been reopened:
https://github.com/vmarc/knooppuntnet/issues/114

**Comment by vmarc** [comment]
Problem resolved.

In the meanwhile route route 60-60 has been changed to 25-60 (see changeset: [101526187](https://knooppuntnet.nl/nl/analysis/changeset/101526187/4466769)).
