### ISSUE TITLE
Icons show very small, on phone/tablet, on return to main menu

### ISSUE THREAD

**Issue by elnfrov** [vmarc/knooppuntnet#154]
The following happened when I started to use KPN on phone (Android 10, OnePlus 5T); also reproduced on tablet Pixel-C (Android 10):

- Using latest FireFox browser on phone
- Go to site
- Go to Analyse
- Go to Overzicht in Cijfers
- Return to Analyse
- Icons are shown small
- Return to Main
- Icons are shown small
- See attached screenshot (phone)
![Screenshot_20210321-233129_Firefox](https://user-images.githubusercontent.com/11708725/111959866-4edf3580-8aef-11eb-9ccc-6fb640766aec.png)

**Comment by elnfrov** [comment]
Another screenshot:
![Screenshot_20210322-091743_Firefox](https://user-images.githubusercontent.com/11708725/111960254-ca40e700-8aef-11eb-98dc-e715273118c9.png)

**Comment by vmarc** [comment]
@elnfrov thank for reporting this problem

Fixed in release v3.1.5.
