### ISSUE TITLE
Incorrect URL is generated with CTRL-Click

### ISSUE THREAD

**Issue by elnfrov** [vmarc/knooppuntnet#155]
Start --> Analyse --> Network --> Altena --> Kaart
Select a point and click mouse and a working URL is generated: https://knooppuntnet.nl/nl/analysis/node/3509020896
CTRL-click on the same point and a non-working URL is generated: https://knooppuntnet.nl/analysis/node/3509020896
See it misses the '/nl/' part in the URL.

**Comment by pelderson** [comment]
Maybe related: In the Planner, control-click doesn't bring the user to Analysis any more. It just selects the node or route, same as click (Windows10, Google Chrome)

**Comment by vmarc** [comment]
Both problems fixed in release 3.1.7
