### ISSUE TITLE
Deleted nodes remain as "facts"

### ISSUE THREAD

**Issue by pelderson** [vmarc/knooppuntnet#184]
https://knooppuntnet.nl/nl/analysis/hiking/nl/Bergeijk/facts the two nodes 11 no longer exist in OSM (other nodes in almost the same place now carry the numbers 11).

I think what triggered this: I had created the nodes with MapComplete, then in JOSM I merged them with the actual junction nodes.  The MapComplete nodes then no longer existed, but Knooppuntnet does not remove them.

**Comment by vmarc** [comment]
@pelderson thank for reporting this problem

For now I have manually set the nodes [8813858560](https://knooppuntnet.nl/nl/analysis/node/8813858560) and [8813846463](https://knooppuntnet.nl/nl/analysis/node/8813846463) to non-active in the knooppuntnet database. That made the nodes disappear from the reporting.

The actual problem still needs further investigation. Probably similar or the same as #183.

**Comment by vmarc** [comment]
Analysis for node [8813846463](https://knooppuntnet.nl/nl/analysis/node/8813846463) ([osm](https://www.openstreetmap.org/node/8813846463)):

- The node was added in changeset [106013851](https://knooppuntnet.nl/nl/analysis/changeset/106013851/4576053) (minute diff 004/576/053)

  <create>
    <node id="8813846463" version="1" timestamp="2021-06-08T07:15:51Z" uid="7103674" user="Peter Elderson" changeset="106013851" lat="51.2709244" lon="5.3986269">
      <tag k="network:type" v="node_network"/>
      <tag k="rwn_ref" v="o"/>
    </node>
  </create>


- The node was updated in changeset [106013851](https://knooppuntnet.nl/nl/analysis/changeset/106013851/4576054) (minute diff 004/576/054):

  <modify>
    <node id="8813846463" version="2" timestamp="2021-06-08T07:16:25Z" uid="7103674" user="Peter Elderson" changeset="106013851" lat="51.2709244" lon="5.3986269">
      <tag k="expected_rwn_route_relations" v="3"/>
      <tag k="network:type" v="node_network"/>
      <tag k="rwn_ref" v="11"/>
    </node>
  </modify>


- The node was deleted in change  [106052497](https://knooppuntnet.nl/nl/analysis/changeset/106052497/4576729) (minute diff 004/576/729)

  <delete>
    <node id="8813846463" version="3" timestamp="2021-06-08T18:46:37Z" uid="7103674" user="Peter Elderson" changeset="106052497" lat="51.2709244" lon="5.3986269"/>
  </delete>


In a [simulation of this sequence of events](https://github.com/vmarc/knooppuntnet/blob/develop/server/src/test/scala/kpn/server/analyzer/engine/analysis/caseStudies/Issue184_NodeDeletion.scala), the node is successfully set to non-active.

---

The deletion details do not contain the tags of the node. So the only way the knooppuntnet logic can recognize that this was a network node is through the fact that it is in the watched collection: analysisContext.data.orphanNodes.watched.

Looking at the code to populate analysisContext.data.orphanNodes.watched during analyzer startup, the reason for the deletion going wrong was found: the OverpassAPI query to collect all node ids was wrong. It was using wrong tags to find the network nodes.  After fixing the query, the deletion of orphan nodes should be picked up correctly by the analysis logic from now on.
