### ISSUE TITLE
New prefix of network name: Wanderwegenetz

### ISSUE THREAD

**Issue by A67-A67** [vmarc/knooppuntnet#186]
This prefix is used in the network Wanderwegenetz Ostbelgien.

https://knooppuntnet.nl/nl/analysis/network/9532813

To be added to the "substrings to be ignored in network names".

**Comment by vmarc** [comment]
Implemented in next release (screenshots below are from development environment).

Before:

<kbd>![before](https://user-images.githubusercontent.com/6596480/125198853-f7aecd80-e263-11eb-947b-5ac05a3586a9.png)</kbd>

After:

<kbd>![after](https://user-images.githubusercontent.com/6596480/125198869-02696280-e264-11eb-8091-a0521ed7d61d.png)</kbd>
