### ISSUE TITLE
RWN Knooppunt nummer getoond met het RCN getal

### ISSUE THREAD

**Issue by FrankOverman** [vmarc/knooppuntnet#187]
Valt me op dat deze RWN16 getoond wordt als RWN37: 37 is daareentegen de waarde voor RCN: verwacht wordt de waarde 16 te zien. Zie ook attached screenshot.

![KPN_37](https://user-images.githubusercontent.com/11708725/123540984-23996180-d742-11eb-8f8f-407f4c7aefa6.jpg)

**Comment by elnfrov** [comment]
Nog een screenshot, maar nu van de browser met URL
![KPN_37_2](https://user-images.githubusercontent.com/11708725/123541039-84c13500-d742-11eb-93a8-35a1365d459a.jpg)

**Comment by elnfrov** [comment]
Ook wel handig: de locatie:
https://www.openstreetmap.org/?mlat=51.5112&mlon=5.0888#map=16/51.5112/5.0888&layers=N

**Comment by vmarc** [comment]
@FrankOverman dankjewel om dit te melden

In jou screenshots kan ik inderdaad duidelijk zien dat er iets niet klopt met wandelknooppunt 16 en fietsknooppunt 37 op dezelfde plek. 

Helaas, als ik dat hier op mijn scherm probeer zie ik het probleem niet (zie afbeeldingen hieronder). Ik heb tot nu toe niet kunnen achterhalen hoe het komt dat dit bij jou anders is.  Als er ondertussen iets veranderd zou zijn in de OpenStreetMap database of in de logica van de knooppuntnet toepassing, dan zou dit eventueel een verklaring kunnen zijn dat het 2 weken geleden niet klopte en nu wel, maar ik heb niet direct iets in de mapping geschiedenis gevonden, en ik kan ook niet bedenken welke verandering in de toepassing dit effect zou kunnen hebben.

---

Wandelnetwerk:

<kbd>![hiking](https://user-images.githubusercontent.com/6596480/125192523-9a595300-e248-11eb-8070-728c9f2d6e52.png)</kbd>

---

Fietsnetwerk:

<kbd>![cycling](https://user-images.githubusercontent.com/6596480/125192528-9e857080-e248-11eb-815c-bd0c34658763.png)</kbd>

**Comment by FrankOverman** [comment]
Ook hier (op dezelfde PC, zelfde browser, etc) toont het nu ok, zoals in jouw laatste screenshots.
Ik was hier redelijk scherp op omdat vectormaps van openandromaps (en de thema's daarin) eenzelfde probleem ooit hadden.
Ik stel voor dat we het hierbij laten voor dit issue. Er kan later altijd op teruggekomen worden indien het zich toch wederom manifesteert. Bedankt!
