### ISSUE TITLE
487 vrije routes in Fietsen in Nederland

### ISSUE THREAD

**Issue by dvdhoven** [vmarc/knooppuntnet#191]

**Comment by dvdhoven** [comment]
Sinds vanmorgen 20-07-2021 staan er 487 vrije routes bij Fietsen in Nederland
Deze routes lijken allemaal afkomstig uit het netwerk Stadsregio Arnhem-Nijmegen https://knooppuntnet.nl/nl/analysis/network/934714
In OSM bestaan deze routes niet.
Alle routes van de Stadsregio staan maar eenmaal in OSM als member van de Stadsregio

Vriendelijke groeten,
Dick van den Hoven

**Comment by vmarc** [comment]
In netwerk [934714](https://knooppuntnet.nl/nl/analysis/network/934714) ontbreekt de _"network:type=node_network"_ tag geloof ik.

**Comment by dvdhoven** [comment]
Sinds vanmorgen 20-07-2021 staan er 487 vrije routes bij Fietsen in Nederland
Deze routes lijken allemaal afkomstig uit het netwerk Stadsregio Arnhem-Nijmegen https://knooppuntnet.nl/nl/analysis/network/934714
In OSM bestaan deze routes niet.
Alle routes van de Stadsregio staan maar eenmaal in OSM als member van de Stadsregio

Vriendelijke groeten,
Dick van den Hoven

**Comment by dvdhoven** [comment]
Ja, je hebt gelijk. Dat had ik totaal niet bedacht
Ik heb het aangepast.
Bedankt voor de snelle reactie

Vriendelijke groeten,
Dick van den Hoven
