### ISSUE TITLE
[Planner output] Route colour is not shown in pdf output

### ISSUE THREAD

**Issue by pelderson** [vmarc/knooppuntnet#195]
![image](https://user-images.githubusercontent.com/38458314/130601603-f0b6dfe7-ad39-4cb1-a41a-fde39883d8c8.png)

**Comment by pelderson** [comment]
Ik loop nu veel in Overijssel en daar staan de nummerverwijzingen niet op de knooppunten, je kan daar niet zonder de kleuraanwijzing. Mijn knooppuntenstripje daar had ik dus niet veel aan!

**Comment by vmarc** [comment]
While testing the colour logic for the compact pdf, I came across the following routes where there was a problem with interpreting the  colour tag (perhaps in the future there could be an additional route fact for this):


|route|colour|
|---|---|
|[6835338](https://knooppuntnet.nl/nl/analysis/route/6835338)|purple;red;colour|
|[6839527](https://knooppuntnet.nl/nl/analysis/route/6839527)|blue;yellow;whitte-purple|
|[6839580](https://knooppuntnet.nl/nl/analysis/route/6839580)|green;puple;white-purple|
|[6839625](https://knooppuntnet.nl/nl/analysis/route/6839625)|blue;greeen;red;white-green|
|[6839859](https://knooppuntnet.nl/nl/analysis/route/6839859)|blue;yekkow|
|[7149859](https://knooppuntnet.nl/nl/analysis/route/7149859)|blue;green;orange;purp;e;red;yellow;white-red|
|[7803073](https://knooppuntnet.nl/nl/analysis/route/7803073)|;purple;red;yellow|
|[7827331](https://knooppuntnet.nl/nl/analysis/route/7827331)|blue;orange;yellow;whiote-red|
|[8284529](https://knooppuntnet.nl/nl/analysis/route/8284529)|blkuie;yellow-red|
|[8361423](https://knooppuntnet.nl/nl/analysis/route/8361423)|yelloow-red|
|[9643682](https://knooppuntnet.nl/nl/analysis/route/9643682)|blue;green;ornage;yellow;white-green;white-red|
|[11749509](https://knooppuntnet.nl/nl/analysis/route/11749509)|;purple|
|[11751701](https://knooppuntnet.nl/nl/analysis/route/11751701)|;purple|
|[11757604](https://knooppuntnet.nl/nl/analysis/route/11757604)|`blue;purple|
|[11758154](https://knooppuntnet.nl/nl/analysis/route/11758154)|`blue;orange|
|[11763674](https://knooppuntnet.nl/nl/analysis/route/11763674)|;purple;yellow|
|[11763675](https://knooppuntnet.nl/nl/analysis/route/11763675)|;green;purple|
|[11763676](https://knooppuntnet.nl/nl/analysis/route/11763676)|;purple|
|[11763677](https://knooppuntnet.nl/nl/analysis/route/11763677)|red;;purple|
|[11764732](https://knooppuntnet.nl/nl/analysis/route/11764732)|;green;yellow|
|[11764733](https://knooppuntnet.nl/nl/analysis/route/11764733)|;blue;green|
|[11764734](https://knooppuntnet.nl/nl/analysis/route/11764734)|;blue;green|
|[11770269](https://knooppuntnet.nl/nl/analysis/route/11770269)|;orange;yellow|
|[11778339](https://knooppuntnet.nl/nl/analysis/route/11778339)|;purple;yellow|
|[11779935](https://knooppuntnet.nl/nl/analysis/route/11779935)|;green;red;yellow|
|[11791044](https://knooppuntnet.nl/nl/analysis/route/11791044)|green;orange;purple;yelow;yellow-red|
|[11791045](https://knooppuntnet.nl/nl/analysis/route/11791045)|green;orange;yelow;yellow-red|
|[11803268](https://knooppuntnet.nl/nl/analysis/route/11803268)|green;blue;orange;purple;red;yelkow|
|[11800272](https://knooppuntnet.nl/nl/analysis/route/11800272)|yellow;red-whit';yellow-red|
|[11803269](https://knooppuntnet.nl/nl/analysis/route/11803269)|green;purple;red;yelkow|
|[11803271](https://knooppuntnet.nl/nl/analysis/route/11803271)|green;orange;purple;red;yelkow|
|[11812206](https://knooppuntnet.nl/nl/analysis/route/11812206)|green;;purple;white-purple|
|[11812207](https://knooppuntnet.nl/nl/analysis/route/11812207)|green;;purple;red;white-purple|
|[11812210](https://knooppuntnet.nl/nl/analysis/route/11812210)|;green;purple;white-red;yellow-red;white-purple|
|[11812211](https://knooppuntnet.nl/nl/analysis/route/11812211)|;green;purple|
|[11815806](https://knooppuntnet.nl/nl/analysis/route/11815806)|blue;green;orange;purple;redyellow|
|[11815808](https://knooppuntnet.nl/nl/analysis/route/11815808)|blue;green;orange;purple;redyellow|
|[11825217](https://knooppuntnet.nl/nl/analysis/route/11825217)|orange;yellow;yellow-red;white-puple|
|[11830223](https://knooppuntnet.nl/nl/analysis/route/11830223)|yellow;white-puple|
|[11830225](https://knooppuntnet.nl/nl/analysis/route/11830225)|orange;purple;yellow;white-puple|
|[11880462](https://knooppuntnet.nl/nl/analysis/route/11880462)|blue;white-red;yelloow-red;white-pueple|
|[11888395](https://knooppuntnet.nl/nl/analysis/route/11888395)|;white-redorange;purple;yellow-red|
|[11898020](https://knooppuntnet.nl/nl/analysis/route/11898020)|green;;purple;red|
|[11891734](https://knooppuntnet.nl/nl/analysis/route/11891734)|blue;;orange;purple|
|[11891735](https://knooppuntnet.nl/nl/analysis/route/11891735)|blue;green;;orange;purple;red|
|[11898546](https://knooppuntnet.nl/nl/analysis/route/11898546)|-purple;red|
|[11904042](https://knooppuntnet.nl/nl/analysis/route/11904042)|green;yelloe|
|[11906462](https://knooppuntnet.nl/nl/analysis/route/11906462)|;purple;red|
|[11906474](https://knooppuntnet.nl/nl/analysis/route/11906474)|orange;;red|
|[11906475](https://knooppuntnet.nl/nl/analysis/route/11906475)|orange;;purple;red|
|[11906476](https://knooppuntnet.nl/nl/analysis/route/11906476)|blue;;purple;red|
|[11908259](https://knooppuntnet.nl/nl/analysis/route/11908259)|;red|
|[11908260](https://knooppuntnet.nl/nl/analysis/route/11908260)|green;orange;;red|
|[11908262](https://knooppuntnet.nl/nl/analysis/route/11908262)|orange;;red|
|[11908265](https://knooppuntnet.nl/nl/analysis/route/11908265)|orange;;purple|
|[11923075](https://knooppuntnet.nl/nl/analysis/route/11923075)|blue;green;purple;yeloow|
|[11923076](https://knooppuntnet.nl/nl/analysis/route/11923076)|blue;green;purple;yeloow|
|[11923077](https://knooppuntnet.nl/nl/analysis/route/11923077)|purple;yeloow|
|[11954413](https://knooppuntnet.nl/nl/analysis/route/11954413)|blue;greeen;red|
|[11954415](https://knooppuntnet.nl/nl/analysis/route/11954415)|blue;greeen;red;white-red|
|[11971167](https://knooppuntnet.nl/nl/analysis/route/11971167)|blue;orange;;white-red|
|[11968436](https://knooppuntnet.nl/nl/analysis/route/11968436)|blueorange;;red;yellow|
|[11988961](https://knooppuntnet.nl/nl/analysis/route/11988961)|green;0range|
|[11994741](https://knooppuntnet.nl/nl/analysis/route/11994741)|oblue;range;purple;white-red;white-green|
|[12046721](https://knooppuntnet.nl/nl/analysis/route/12046721)|;purple|
|[12078294](https://knooppuntnet.nl/nl/analysis/route/12078294)|;white-red|
|[12095795](https://knooppuntnet.nl/nl/analysis/route/12095795)|greay|
|[12105823](https://knooppuntnet.nl/nl/analysis/route/12105823)|yes|
|[12128591](https://knooppuntnet.nl/nl/analysis/route/12128591)|green;ewhite-red|
|[12128592](https://knooppuntnet.nl/nl/analysis/route/12128592)|green;purplewhite-red|
|[12128593](https://knooppuntnet.nl/nl/analysis/route/12128593)|green;purplewhite-red|
|[12128594](https://knooppuntnet.nl/nl/analysis/route/12128594)|green;purplewhite-red|
|[12220170](https://knooppuntnet.nl/nl/analysis/route/12220170)|;purple|
|[12209699](https://knooppuntnet.nl/nl/analysis/route/12209699)|green;yelloow;red|
|[12209700](https://knooppuntnet.nl/nl/analysis/route/12209700)|green;yelloow|
|[12211184](https://knooppuntnet.nl/nl/analysis/route/12211184)|red;yelloow|
|[12267160](https://knooppuntnet.nl/nl/analysis/route/12267160)|bkue;yellow-red|
|[12291009](https://knooppuntnet.nl/nl/analysis/route/12291009)|blue;orang';red|
|[13035930](https://knooppuntnet.nl/nl/analysis/route/13035930)|bllue|

**Comment by pelderson** [comment]
Haha, foutjes! Ik zal ernaar kijken, bedankt voor de oplettendheid!
Vr gr Peter Elderson


Op do 4 nov. 2021 om 23:02 schreef vmarc ***@***.***>:

**Comment by pelderson** [comment]
I have corrected most of them, I think, but I had a computer crash so I may have lost some work. Could you run this check again, or is that complicated?

**Comment by vmarc** [comment]
Remaining:

|route|colour|
|---|---|
|[8284529](https://knooppuntnet.nl/nl/analysis/route/8284529)|blkuie;yellow-red|
|[8361423](https://knooppuntnet.nl/nl/analysis/route/8361423)|yelloow-red|
|[9643682](https://knooppuntnet.nl/nl/analysis/route/9643682)|blue;green;ornage;yellow;white-green;white-red|
|[11830223](https://knooppuntnet.nl/nl/analysis/route/11830223)|yellow;white-puple|
|[11830225](https://knooppuntnet.nl/nl/analysis/route/11830225)|orange;purple;yellow;white-puple|
|[11880462](https://knooppuntnet.nl/nl/analysis/route/11880462)|blue;white-red;yelloow-red;white-pueple|
|[11888395](https://knooppuntnet.nl/nl/analysis/route/11888395)|;white-redorange;purple;yellow-red|
|[11898020](https://knooppuntnet.nl/nl/analysis/route/11898020)|green;;purple;red|

**Comment by pelderson** [comment]
Dank! Nu heb ik ze denk ik allemaal verbeterd.

**Comment by vmarc** [comment]
With the installation of release 4.0, the pdf in "Compact" style now includes a colour indicator for the route between nodes. When a route has multiple colours, only the first colour is shown.

![pdf-compact](https://user-images.githubusercontent.com/6596480/180489602-dee61d7f-9153-4b95-adf6-af824074bf76.png)

---

Also, in release 4.0, a new pdf style "Text" has been added. This style includes the route colour in text format. All colours are included if there are multiple colours.

![pdf-text](https://user-images.githubusercontent.com/6596480/180489963-086885e7-c7ca-4892-b6ca-65d32f81894c.png)
