### ISSUE TITLE
No routes on map

### ISSUE THREAD

**Issue by UncleOwen** [vmarc/knooppuntnet#197]
The map doesn't show any routes, see [screenshot](https://i.imgur.com/CcHUfzU.png)

The screenshot was created using Firefox 91.0.2, Chromium 93.0.4577.63 looks the same

Yesterday, the routes were visible.

**Comment by vmarc** [comment]
@UncleOwen thanks for reporting this problem

The routes have disappeared after I installed a new version of knooppuntnet this afternoon.  There was an error in the url that is used to pick up the map tiles with the routes and nodes from the server. As a result of your report this has been fixed now. So thanks again!!

While preparing the map image below I thought for a minute I discovered another problem: an island in the North See (Helgoland) included in Pinneberg.  Luckily, [Wikipedia](https://de.wikipedia.org/wiki/Kreis_Pinneberg) confirms OSM is right about [Helgoland](https://de.wikipedia.org/wiki/Helgoland)... :) 

![pinneberg](https://user-images.githubusercontent.com/6596480/132137684-3fbefc47-bae9-41bf-ac5b-cf072d8a959f.png)
