### ISSUE TITLE
Node numbers in web page title

### ISSUE THREAD

**Issue by A67-A67** [vmarc/knooppuntnet#20]
In the old VMarc the node numbers where shown in the title (e.g. on the tabs in your browser). To solve errors, I used to open all similar errors in a network in new tabs. It was then easy to see which tab was which route. In the new Knooppuntnet.nl however only the name 'knooppuntnet' is shown in the title.

Example:
- Old: [Route 02-04 - Asten](http://old.vmarc.be/nl/route/2337416)
- New: [knooppuntnet](https://knooppuntnet.nl/nl/route/2337416)

I would prefer when the node numbers where shown at the start of the title, like '02-04 - knooppuntnet' or '02-04 - Asten - knooppuntnet'. The word 'Route' is not necessary as all routes start with two numbers and when a lot of tabs are opened, only the word Route would be visible.

**Comment by vmarc** [comment]
The titles for all pages have been changed so that they are page specific.
