### ISSUE TITLE
Display username of the changeset

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#207]
- In https://knooppuntnet.nl/en/analysis/changeset/112555794/4758923<br/><img width="50%" alt="changeset 112555794" src="https://user-images.githubusercontent.com/2158081/137544147-09875d6f-47bf-4905-8e6c-95e9fdce8563.png">

- In https://knooppuntnet.nl/en/analysis/network/13305300/changes<br/><img width="50%" alt="Network changes" src="https://user-images.githubusercontent.com/2158081/137544737-d3697d83-ab8b-4575-80a9-c50083fec4af.png">

- In https://knooppuntnet.nl/en/analysis/node/2862412683/changes
- In https://knooppuntnet.nl/en/analysis/route/13319570/changes

**Comment by vmarc** [comment]
@pyrog prior to May 2018, knooppuntnet did actually show the usernames exactly as you are requesting, and also in network/route/node pages, and this was very useful.

In addition, there were pages per user showing all node network related changes by that user (most recent first).

But: in the period before May 2018 (start of [GPDR](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation)) the login functionality was introduced in knooppuntnet, and all usernames and user specific pages were removed.

In fact, I expected more information was going to have to be removed. See appendix B in [GDPR_Position_Paper.pdf](https://wiki.openstreetmap.org/w/images/8/88/GDPR_Position_Paper.pdf).  Until today, this did not happen.

I think I cannot simply reintroduce the username information.

At most places where you would want to see the username, I think there is a link to the osm website that shows you the information.

**Comment by pyrog** [comment]
Same issue with [OSMcha](https://osmcha.org), [HDYC](https://hdyc.neis-one.org),…
Once you are logged in, you could see usernames 😉

> I think there is a link to the osm website that shows you the information.

Too painful. [Knooppuntnet analysis](https://knooppuntnet.nl/en/analysis/network/13305300) is… an analysis tool 😅 
So knowing quickly who do which changeset on the network is an important feature.
(Currently we work at 3 contributors on the same network. Changesets comments are not sometime very useful, username are valuable).

**Comment by pyrog** [comment]
@vmarc could your reopen this issue?

The appendix B is clear : "everything" is accessible if the user is logged in
- Display name
- Time stamps
- Changeset tags
- Changeset comments
- Notes

Contributing to OSM is a voluntary act.

The contributors accept that OSM Website, Osmcha… display theses informations.
If they don't, they could simply leave their way.

**Comment by pyrog** [comment]
Idea: use script like [Better OSM](https://github.com/deevroman/better-osm-org) to display the user name.
