### ISSUE TITLE
Group dates in Analysis > Network > Details

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#209]
Like Analysis > Route details > Details, group dates.

<img width="50%" alt=" Analysis > Network > Details" src="https://user-images.githubusercontent.com/2158081/137574190-eda27c48-3a08-4913-adf4-cec6570c79ea.png">
<img width="50%" alt="Analysis > Route details > Details" src="https://user-images.githubusercontent.com/2158081/137574193-e913fc15-2b35-4e9a-be5a-ff635efc922e.png">

**Comment by vmarc** [comment]
@pyrog well spotted, there is an inconsistency here

What I like though is that when you click following links, the "Situation on" is always at the same position:

https://knooppuntnet.nl/fr/analysis/hiking/fr/networks
https://knooppuntnet.nl/fr/analysis/hiking/fr/facts
https://knooppuntnet.nl/fr/analysis/hiking/fr/orphan-nodes
https://knooppuntnet.nl/fr/analysis/hiking/fr/orphan-routes
https://knooppuntnet.nl/fr/analysis/hiking/fr/changes

https://knooppuntnet.nl/fr/analysis/network/13305300
https://knooppuntnet.nl/fr/analysis/network/13305300/facts
https://knooppuntnet.nl/fr/analysis/network/13305300/nodes
https://knooppuntnet.nl/fr/analysis/network/13305300/routes
https://knooppuntnet.nl/fr/analysis/network/13305300/changes

https://knooppuntnet.nl/en/analysis/hiking/fr/Dole/nodes
https://knooppuntnet.nl/en/analysis/hiking/fr/Dole/routes
https://knooppuntnet.nl/en/analysis/hiking/fr/Dole/facts
https://knooppuntnet.nl/en/analysis/hiking/fr/Dole/changes

So it is perhaps the node and route detail pages that should be changed?
The node and route changes pages do not contain "Situation on"; perhaps should be added there also?

**Comment by pyrog** [comment]
> So it is perhaps the node and route detail pages that should be changed?

For me, no. This is more easy to compare dates if they are closer.
Also I have a "small" screen and "Relation last updated" is almost hidden.

(In fact there is also some issues with the page layout: i.e. too more spaces between tables rows)

> The node and route changes pages do not contain "Situation on"; perhaps should be added there also?

Why not, consistency is a good point 😄

**Comment by vmarc** [comment]
@pyrog can you explain the issue with the page layout a bit better?

>  too more spaces between tables rows

Is this about the table that shows the tag keys and values, or about the use of white space on the page in general?

**Comment by pyrog** [comment]
![arrows that show spaces](https://user-images.githubusercontent.com/2158081/137781705-fbea42a8-8c34-4e09-b309-b297c2beb24e.jpg)

**Comment by pyrog** [comment]
This is a screen copy on my 13" MacBook: a lot of space is lost.
I should scroll down the page 🥲

<img width="1280" alt="Screen copy" src="https://user-images.githubusercontent.com/2158081/137781983-de753abd-f84d-4b56-a525-8da7c6eeb88f.png">

I try to edit manually the CSS inside the web browser: here margin were reduced from 16 px to 4 px in the Summary row.
Couldn't find where to set other "margins"
<img width="651" alt="Capture d’écran 2021-10-18 à 19 59 33" src="https://user-images.githubusercontent.com/2158081/137783116-d26064af-7f18-4c53-b657-48d96cd0dc5a.png">

**Comment by vmarc** [comment]
@pyrog ok, thanks, that is clear: I will try to reduce the vertical white space, so that more information can be seen with less scrolling

**Comment by vmarc** [comment]
Changed in version 3.2.8 (can be tested on [experimental](https://experimental.knooppuntnet.nl/)):
- moved timestamps closer together, and reduce the between-white-space to group them together
- reduced white space between elements (header, paragraphs, data-blocks)
- re-arranged some elements to reduce need to scroll
- moved network type icon to header in network and route pages to win some vertical space

**Comment by pyrog** [comment]
Now the Home > Analysis > Overview is displayed has a list, not a table.
<img width="50%" alt="Home > Analysis > Overview" src="https://user-images.githubusercontent.com/2158081/138637975-ca769be0-5f6d-48c4-9ebe-554fca0a932e.png">

I should zoom out the web page to display it as a table
<img width="50%" alt="zoom out" src="https://user-images.githubusercontent.com/2158081/138638129-1a23520a-d6a2-4788-b785-aab9123ab204.png">

Should I open a new issue for that or we leave this one opened?

But for the previous example and initial issue, dates are grouped and less space is lost 😄 

<img width="50%" alt="Home > Analysis > Network
" src="https://user-images.githubusercontent.com/2158081/138638696-d8e5f584-81a1-480f-a02d-c7009a959167.png">

**Comment by vmarc** [comment]
> Should I open a new issue for that or we leave this one opened?

No issue I think.

The switching between list and table format is as intended. For wide screens "table" is used, for narrow screens "list" is used. This is similar to for example the [networks page](https://experimental.knooppuntnet.nl/fr/analysis/hiking/fr/networks), which uses a "table" on wide screens, and "non-table" on more narrow screens, or the [network detail page](https://experimental.knooppuntnet.nl/fr/analysis/network/13305300) where the layout changes for narrow screens (make browser window less wide to see the layout change).

See: [responsive web design](https://en.wikipedia.org/wiki/Responsive_web_design).

**Comment by pyrog** [comment]
I recognise responsive design 😄 

My laptop screen is not so small: so with an appropriate setting the table could also displayed? 😉

**Comment by vmarc** [comment]
In the overview page sidebar, the possibility has been added to express a preference of how to display the  data. The default is still for the application to automatically determine the use of table or list based on the page width. The user preference is remembered between browser sessions. Available in [experimental](https://experimental.knooppuntnet.nl/fr/analysis/overview). Translations will be added later.

![dialog](https://user-images.githubusercontent.com/6596480/139052277-d9c5b37d-79be-49c0-a10e-61cfc515d2c6.png)

**Comment by pyrog** [comment]
That's fine for me, thank you 😄 

Note: the menu disappear in table view

<img width="33%" alt="Table view" src="https://user-images.githubusercontent.com/2158081/139062761-650412f2-0018-48cb-9daf-18452d1dc2a0.png"> <img width="33%" alt="List view" src="https://user-images.githubusercontent.com/2158081/139062704-7e0ffb68-1d31-4dd1-bdf6-05143109a4d3.png">
<img width="33%" alt="Table view and closed menu" src="https://user-images.githubusercontent.com/2158081/139062993-66dbbfa1-0254-4b32-8973-c71fbcd06cc1.png">
