### ISSUE TITLE
Support for inline skating networks

### ISSUE THREAD

**Issue by A67-A67** [vmarc/knooppuntnet#21]
Thanks for expanding to horse, canoe and motorboat networks! But there is one other mode of transportation that uses knooppunten: inline skating. At this moment there is [one network](https://www.openstreetmap.org/relation/5537385) in Midden-Delfland, which is also rendered on [Waymarked Trails](https://skating.waymarkedtrails.org/#?map=12!51.9543!4.3117).

The skating network uses the same syntax are cycling networks. To compare both:
- network=rcn <--> network=rin
- rcn_ref=* <--> rin_ref=*
- route=cycling <--> route=inline_skates

**Comment by vmarc** [comment]
Support for inline skating has been added.
