### ISSUE TITLE
Analyser down?

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#212]
[Route not found](https://knooppuntnet.nl/en/analysis/route/13357516) for[ relation 13357516](https://www.openstreetmap.org/relation/13357516) created ~40 mn ago 😢 

Last changeset [112842270](https://knooppuntnet.nl/en/analysis/changeset/112842270/4768647) 2021-10-22 16:56 (see [changes](https://knooppuntnet.nl/en/analysis/changes))

**Comment by pyrog** [comment]
Analyse restarted around 20:00 😄
Was it an issue in data ?

**Comment by vmarc** [comment]
There was a problem with the analysis logic on the analysis server (Falkenstein Germany) accessing the analysis database on the database server (Amsterdam).  It is unclear what the root problem was. It may have been a network problem. It certainly was not an issue in the OpenStreetMap data.  The analysis picked up again after a manual restart.
