### ISSUE TITLE
Remove prefixes like 'Sloepennetwerk' from network name

### ISSUE THREAD

**Issue by A67-A67** [vmarc/knooppuntnet#22]
In the cycling and hiking networks 'prefixes' like 'Fietsnetwerk' and 'Wandelnetwerk' are removed from the network name. This way all networks are sorted at the important part of the name.

Example: [Fietsnetwerk Haaglanden](https://knooppuntnet.nl/nl/network/2048535) has the tag name=Fietsnetwerk Haaglanden, but the page title is 'Haaglanden' and the network is sorted at the 'H' in the network list.

This however doesn't work for [horse](https://knooppuntnet.nl/nl/networks/nl/rhn), [canoe](https://knooppuntnet.nl/nl/networks/nl/rpn) and [motorboat](https://knooppuntnet.nl/nl/networks/nl/rmn) networks.

The prefixes in use are:
- Horse: Ruiternetwerk, Ruiterroute and Ruiterroutenetwerk
- Canoe: Kanonetwerk
- Motorboat: Motorbootnetwerk and Sloepennetwerk

**Comment by vmarc** [comment]
The proposed prefixes have been added to the  [substrings to be ignored in network names](https://github.com/vmarc/knooppuntnet/blob/develop/production/core/src/main/scala/kpn/core/engine/analysis/NetworkNameAnalyzer.scala).
