### ISSUE TITLE
[Analysis] Route has UnusedSegments fact, but it looks OK in JOSM

### ISSUE THREAD

**Issue by pelderson** [vmarc/knooppuntnet#220]
https://knooppuntnet.nl/nl/analysis/route/11829926 is een circulaire route. Hij geeft UnusedSegments. Analysis geeft voor Start en Eind twee node id's waar ik er eentje met a en b zou verwachten, en kenmerkt alle wegen in de relatie als Unused. 

(Zou het kunnen zijn dat de node een merge is van twee eerdere nodes? Daar hebben we al eerder problemen mee gehad).

**Comment by pyrog** [comment]
See #208

**Comment by pelderson** [comment]
Translating my issue (I sometimes forget we are a multinational now...)

[Analysis] Route returns unused segments but looks good in JOSM

https://knooppuntnet.nl/nl/analysis/route/11829926 is a circular route. It gives UnusedSegments.

Analysis gives two node ids for Start and End where I would expect one with a and b, and characterises all paths in the relation as Unused.
(Could it be that the node is a merge of two previous nodes? We've had problems with that before).

**Comment by vmarc** [comment]
Resolved in release 4.

- See [unit test code](https://github.com/vmarc/knooppuntnet/blob/develop/server/src/test/scala/kpn/server/analyzer/engine/analysis/caseStudies/Issue220_LoopRoute.scala).

- [route release 3](https://knooppuntnet.nl/nl/analysis/route/11829926)

- [route release 4](https://experimental.knooppuntnet.nl/nl/analysis/route/11829926)
