### ISSUE TITLE
IntegrityCheckFailed for a node in network page but not in the node page

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#221]
**Voie Communale** have IntegrityCheckFailed in the [network page](https://experimental.knooppuntnet.nl/en/analysis/network/13328611/facts) :

<img width="543" alt="Capture d’écran 2021-11-05 à 15 24 59" src="https://user-images.githubusercontent.com/2158081/140525950-bfa5bc9c-b904-4c3f-abd2-d464a2cba973.png">

…but is fine on the [node page](https://experimental.knooppuntnet.nl/fr/analysis/node/3667026424) :

<img width="703" alt="Capture d’écran 2021-11-05 à 15 25 36" src="https://user-images.githubusercontent.com/2158081/140526045-7447f738-c9f4-4933-9123-45d4e5e47bcc.png">

The [Route Forêt de Mouchard - Voie Communale](https://experimental.knooppuntnet.nl/en/analysis/route/13406087) id not part of the network [Val d'Amour](https://experimental.knooppuntnet.nl/en/analysis/network/13328611)

**Comment by vmarc** [comment]
With the installation of release 4.0, the IntegrityCheckFailed information in the network page should now match the information in the node page.
