### ISSUE TITLE
Ik zie al een tijdje geen wijzigingen meer

### ISSUE THREAD

**Issue by dvdhoven** [vmarc/knooppuntnet#222]
Sinds een aantal dagen worden er geen wijzigingen meer getoond.
Het overzicht geeft nog wel het aantal wijzigingen, maar de wijzigingen zelf worden niet meer getoond, niet bij de routes en de knopen en ook niet in het wijzigingenoverzicht.

**Comment by vmarc** [comment]
Kun je enkele voorbeelden geven van paginas waar wijzigingen ontbreken?  Ik zie heel recente wijzigingen in volgende paginas:

https://knooppuntnet.nl/nl/analysis/changes
https://knooppuntnet.nl/nl/analysis/network/13328611/changes
https://knooppuntnet.nl/nl/analysis/route/13414467/changes
https://knooppuntnet.nl/nl/analysis/node/197844995/changes

**Comment by dvdhoven** [comment]
Het is weer eens hetzelfde probleem, Firefox vindt iets niet goed.
Ik klikte  op een van de links vanuit de mail, die ik bekijk in GMail, dus Chrome en toen zag ik ze wel, na aanmelden.
Dus dat is de oplossing, in Chrome draaien.

Sorry, dat ik je hier mee lastig heb gevallen. Ik had het zelf kunnen denken.
Firefox doet in toenemende mate moeilijk en diverse sites draaien niet meer in Firefox.

Van de week heeft FF een new release gekregen, versie 94.0.1 en dat draait bij mij.

Bedankt voor de moeite,
Vriendelijke groeten,
Dick van den Hoven

**Comment by vmarc** [comment]
Voor mij werkt het goed in Firefox (versie 94.0 Ubuntu).
Ik heb wel opnieuw moeten inloggen om wijzigingen te kunnen zien.
