### ISSUE TITLE
Map overlap some text

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#223]
The text _Situation on 2021-11-08 17:19_ is partially hidden in all languages except english.

Example for [Dole](https://experimental.knooppuntnet.nl/fr/analysis/hiking/fr/Dole/map) on the experimental website.

<img width="920" alt="Capture d’écran 2021-11-08 à 17 25 38" src="https://user-images.githubusercontent.com/2158081/140779812-fb390d84-bd1c-4834-b13a-56172b2b8ad1.png">

**Comment by vmarc** [comment]
@pyrog I have been trying to reproduce this problem in browerstack.com without success, do you still see the problem today?

**Comment by pyrog** [comment]
"Situation on…" seem to be removed from the map (visible in Details).
Example "Dole" is now : https://knooppuntnet.nl/en/analysis/network/13305300/map
