### ISSUE TITLE
Municipality list is filled with "empty" cities

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#224]
A lot of cities have 0 nodes. They should be removed from the list ?

<img width="698" alt="Capture d’écran 2021-11-08 à 17 28 47" src="https://user-images.githubusercontent.com/2158081/140780371-243205e6-5e1d-4972-8e22-b987d845317d.png">

**Comment by vmarc** [comment]
When using the option _"Select from tree"_, you have the option to select _"In use only"_ to only show the locations with actual information behind it. I guess for _"Search by name"_ this option is not needed, and it can always leave out the locations without nodes/routes?

![location-selection](https://user-images.githubusercontent.com/6596480/140805823-29f3a4f1-a6c1-48fc-ab66-4056cc62b46e.png)

**Comment by vmarc** [comment]
Implemented in version 3.2.17: locations without nodes are no longer included in the location list.
