### ISSUE TITLE
Search cities without accentuated characters

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#226]
In the following [example](https://experimental.knooppuntnet.nl/en/analysis/hiking/fr), searching "rhône" found 2 entries, but searching "rhone" found nothing.

 <img width="488" alt="Capture d’écran 2021-11-09 à 00 35 21" src="https://user-images.githubusercontent.com/2158081/140835068-e16896a0-4f78-49ac-b1f7-9eb1c977089b.png">

**Comment by vmarc** [comment]
Implemented in version 3.2.17: you can now search without accents.
