### ISSUE TITLE
Undefined search by city

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#227]
Search for example for Ajaccio display [Hiking in undefined](https://experimental.knooppuntnet.nl/en/analysis/hiking/fr/undefined/nodes)

<img width="470" alt="Capture d’écran 2021-11-09 à 00 51 28" src="https://user-images.githubusercontent.com/2158081/140836466-45382580-92b7-4f93-8c62-9c1680383f62.png">
<img width="566" alt="Capture d’écran 2021-11-09 à 00 48 35" src="https://user-images.githubusercontent.com/2158081/140836387-dbfbd3e6-f3db-41df-8924-5b058e1cfbd7.png">

**Comment by vmarc** [comment]
Implemented in version 3.2.17: a warning message is displayed when clicking "Location overview" and the textfield contains a location name that does not match any of the locations in the dropdown list.
