### ISSUE TITLE
Localize date/time

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#229]
Use local date/time format.

I.e, for french date should be  **09/11/2021 09:17** instead of **2021-11-09 09:17**

<img width="949" alt="Capture d’écran 2021-11-09 à 09 20 43" src="https://user-images.githubusercontent.com/2158081/140887766-f5052328-835e-4570-ae81-878da5d18757.png">

**Comment by vmarc** [comment]
Implemented in version 3.2.17.
