### ISSUE TITLE
Right align number in table cells

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#230]
[Home > Analysis > Overview](https://experimental.knooppuntnet.nl/fr/analysis/overview)
Also, numbers should be localised (**161 084** in french, instead of **161.084**) (see #231)

<img width="75%" alt="Capture d’écran 2021-11-09 à 09 27 38" src="https://user-images.githubusercontent.com/2158081/140889113-925164ee-b2b1-45a2-a581-5b34c7fabfae.png">

[Home > Analysis > Network > Nodes](https://experimental.knooppuntnet.nl/en/analysis/network/13328611/nodes)

<img width="50%" alt="Capture d’écran 2021-11-09 à 09 28 23" src="https://user-images.githubusercontent.com/2158081/140889108-decc1c5f-957d-4cc3-84ba-f14a3e22d01b.png">

[Home > Analysis > Network > Routes](https://experimental.knooppuntnet.nl/en/analysis/network/13328611/routes)
Also, the space separator is missing between number and unit in the distance column.

<img width="50%" alt="Capture d’écran 2021-11-09 à 09 28 13" src="https://user-images.githubusercontent.com/2158081/140889109-0790d89d-cd1f-47b1-b206-ca1d3b6b2767.png">

**Comment by vmarc** [comment]
Implemented in version 3.2.17.
