### ISSUE TITLE
Localise numbers

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#231]
Numbers should be localised (**161 084** in french, instead of **161.084**)

[Home > Analysis > Overview](https://experimental.knooppuntnet.nl/fr/analysis/overview)

<img width="75%" alt="Capture d’écran 2021-11-09 à 09 27 38" src="https://user-images.githubusercontent.com/2158081/140889113-925164ee-b2b1-45a2-a581-5b34c7fabfae.png">

**Comment by vmarc** [comment]
Implemented in version 3.2.17.
