### ISSUE TITLE
Route A - A

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#233]
If start and end nodes have the same name, the fact RouteNameMissing is "raised".
It could be solved by adding the tag `note=A - A`.

In big and undocumented networks like [Maurienne Galibier](https://knooppuntnet.nl/en/analysis/network/12280144/facts), this is very painful 😢 

See #208

**Comment by pyrog** [comment]
There is [802](https://overpass-turbo.eu/s/1db7) routes in France with `note="? - ?"`.
Theses tags were added manually 😞 

Also there is at least [36](https://overpass-turbo.eu/s/1dba) routes with 2 different nodes with the same name:
- Ancienne gare du tram - Ancienne gare du tram
- Bas Percy - Bas Percy
- Bonnenuit-parking - Bonnenuit-parking
- Bonrevet - Bonrevet
- Camp des Rochilles - Camp des Rochilles
- Col de la Croix Perrin - Col de la Croix Perrin
- Col du Télégraphe - Col du Télégraphe
- Falletans Chêne N.D. - Falletans Chêne N.D.
- Fenace - Fenace
- Ferme Durand - Ferme Durand
- Font Cellier - Font Cellier
- Golf - Golf
- L'Entraz - L'Entraz
- La Borgé - La Borgé
- La Chapelle Saint-Pierre - La Chapelle Saint-Pierre
- La Cote - La Cote
- La Rivine - La Rivine
- Lac des Cerces - Lac des Cerces
- Le Poingt Ravier - Le Poingt Ravier
- Le Villard - Le Villard
- Les Chauchets - Les Chauchets
- Les Choseaux - Verneys - Les Choseaux - Verneys
- Les Gillères - Les Gillères
- Les Granges du Galibier - Les Granges du Galibier
- Les Revinettes - Les Revinettes
- Les Trois Croix - Les Trois Croix
- Montissot - Montissot
- Morte des fontaines - Morte des fontaines
- Moulin Benjamin - Moulin Benjamin
- Moulin Benjamin - Moulin Benjamin
- Piste de la Plagnette - Piste de la Plagnette
- Plan Lachat - Plan Lachat
- Roc Saint-Pierre - Roc Saint-Pierre
- Sous le Pain de Sucre - Sous le Pain de Sucre
- Virage de Plan Lachat - Virage de Plan Lachat
- Voie du Tram - Voie du Tram

**Comment by vmarc** [comment]
Resolved in release 4. No more RouteNameMissing when the route name can be derived from the names of the nodes in the route.
