### ISSUE TITLE
Smiley icons are disturbing

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#235]
<img width="354" alt="Capture d’écran 2021-11-14 à 09 08 33" src="https://user-images.githubusercontent.com/2158081/141673046-01d710fb-978d-49ea-a975-cfdcc90a425c.png">

- Color
  - Orange mean warning but the face is happy
  - Green mean good but the face is thinking

- Meaning not clear in this [changeset](https://knooppuntnet.nl/en/analysis/changeset/113753179/4800967)
   - Adding a new free route : the face smile<br/><img width="371" alt="Capture d’écran 2021-11-14 à 09 15 41" src="https://user-images.githubusercontent.com/2158081/141673228-6d0a4f2c-2bcd-48be-be9b-dd4ce23f16f6.png">

   - Adding an existing free route to the network : the face is thinking<br/><img width="543" alt="Capture d’écran 2021-11-14 à 09 15 04" src="https://user-images.githubusercontent.com/2158081/141673215-3dad5c92-6dd3-41bc-9e69-e4b48138c894.png">

**Comment by vmarc** [comment]
The icon has been changed from _investigate_ to _happy_ when adding a free route to a network in release v3.2.18. 

This change will not be reflected in the referenced [changeset](https://knooppuntnet.nl/en/analysis/changeset/113753179/4800967) until the history is recalculated in release v4.0. We will leave this issue open until that time.

**Comment by vmarc** [comment]
Icons have been updated in release 4.3.60 (you may have to make sure that the browser cache is emptied before the new icons are seen).
