### ISSUE TITLE
admin_level=7 in France

### ISSUE THREAD

**Issue by StephaneChatty** [vmarc/knooppuntnet#236]
Hi!

In France, admin_level=7 has been assigned to an administrative subdivision that is specific to our ministry of interior (police, firefighters, etc): arrondissements. This level is meaningless in any other context: justice, education, elections, transports... and outdoors (hiking/cycling/etc).

For outdoors, the only meaningful levels are "départements" (they manage a list of outdoor paths) and "communes" or "communautés de communes" (they manage the paths and the local routes).

Since the French OSM community is not ready to change the meaning of admin_level=7, would it be possible to have a parameter set that determines what subdivisions should be used in a given country for outdoor routes?

**Comment by vmarc** [comment]
[LocationConfigurationDefinition](https://github.com/vmarc/knooppuntnet/blob/893fb99b7e15b05639a521137ed03bd5b1ceb165/server/src/main/scala/kpn/server/analyzer/engine/analysis/location/LocationConfigurationDefinition.scala#L31) currently contains the configuration of the administrative boundaries that are used for France, and the other supported countries. It is not the intention for knooppuntnet to change the meaning of admin_level=7 for France in OSM. Knooppuntnet will be adapted to use boundaries that do make sense (See #225).

**Comment by pyrog** [comment]
https://github.com/vmarc/knooppuntnet/blob/893fb99b7e15b05639a521137ed03bd5b1ceb165/server/src/main/scala/kpn/server/analyzer/engine/analysis/location/LocationConfigurationDefinition.scala#L31
Should be `Seq(3, 4, 6)` 😃 

Also, overseas territories and Corsica have also trails, so you could use this [parent relation](https://www.openstreetmap.org/relation/11980) and remove Corsica from excluded locations ? 😃 
`LocationConfigurationDefinition(Country.fr, "fr/2/France (terres)", Seq(3, 4, 6)) `

```scala
  val excludedLocations = Seq(
    "nl/4/Caribbean Netherlands",
 // "fr/4/Corsica",
    "es/4/Balearic Islands",
    "es/4/Canary Islands",
    "es/4/Melilla",
    "es/4/Plazas de Soberanía",
    "es/4/Ceuta",
  )

```

**Comment by vmarc** [comment]
The subject of this issue is more or less the same as issue  #225. To make followup a bit simpler, I will close this issue, and we can do further followup in #225.

**Comment by StephaneChatty** [comment]
Yes, sorry I had forgotten about Yves’ ticket.

Cheers,

St.
