### ISSUE TITLE
Zombie nodes

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#239]
Same as #238 but for nodes.

Tags of node [La Bournay](https://knooppuntnet.nl/en/analysis/node/511070441/map) were removed in changeset [113900760](https://knooppuntnet.nl/fr/analysis/changeset/113900760/4805640) but the node is still displayed.

<img width="33%" alt="Map" src="https://user-images.githubusercontent.com/2158081/142230493-d4d7e288-02d6-4d7b-b1e9-6df7e01bf7ce.png"> <img valign=top width="33%" alt="Details" src="https://user-images.githubusercontent.com/2158081/142230638-d87aa3f9-c1e2-4626-b1fe-19570f992426.png">

OSM node [511070441](https://www.openstreetmap.org/node/511070441/history)

<img width="50%" alt="Node 511070441" src="https://user-images.githubusercontent.com/2158081/142231920-9e81b55c-04f9-4563-a89a-38aea1e5f1e1.png">

**Comment by pyrog** [comment]
Similar issue with [node 1129323117](https://knooppuntnet.nl/fr/analysis/node/1129323117).
The tag `rwn_ref |=Lc` was removed in [changeset 113974780](https://knooppuntnet.nl/fr/analysis/changeset/113974780/4807979) but is still displayed.


<img width="45%" alt="knooppuntnet" src="https://user-images.githubusercontent.com/2158081/142575599-61a4fe4f-e9ca-45dc-a059-dde80c1da6d6.png"> <img width="33%" alt="OSM" src="https://user-images.githubusercontent.com/2158081/142575667-eca2d740-fe25-430d-b061-6fd3e9b0cb82.png">

**Comment by vmarc** [comment]
No issue here I believe. Given nodes are still considered valid network nodes because they still have the _"rwn_name"_ tag.

An hiking network node needs to have _"network:type=node_network"_ and at least one of the following:
- rwn_ref
- rwn_name
- proposed:rwn_ref
- proposed:rwn_name

**Comment by pyrog** [comment]
I moved the Node [L'Oratoire de St Cassin](https://knooppuntnet.nl/en/analysis/node/10173796917/map?layers=background,hiking,node-marker-layer&position=45.53331234,5.89363187,18) so 2 routes have the fact **RouteUnusedSegments**.

<img width="33%" alt="Image" src="https://github.com/user-attachments/assets/3578b056-62a5-43ea-a848-f3d7b10789f4" />
