### ISSUE TITLE
Icons for horse riding and canoeing look zoomed in and low-res

### ISSUE THREAD

**Issue by A67-A67** [vmarc/knooppuntnet#24]
The icons of horse riding and canoeing look like they are zoomed in and not the entire pictogram is shown. When I check on my phone, they are of lower resolution (vague) than the other icons, probably because of the zoom.

**Comment by vmarc** [comment]
The horse riding and canoeing icons have been changed from bitmap based (png) to vector based (svg), and should look better now.
