### ISSUE TITLE
Display more admin levels when searching a place on the map

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#240]
When many places with the same name are in the same country, it's difficult to find the good one.

Example: Bec de l'Aigle in France.

<img width="50%" alt="Knooppuntnet planner" src="https://user-images.githubusercontent.com/2158081/142279782-eb1f4ae2-e0ac-4a37-8c53-7449b4b41a97.png">

Could you display at least city, department (and maybe  region and country) ?

- Bec de l'Aigle, Val-d'Isère, Savoie, Auvergne-Rhône-Alpes, France
- Bec de l'Aigle, Saint-Julien-Mont-Denis, Savoie, Auvergne-Rhône-Alpes, France
- Bec de l'Aigle, Jausiers, Alpes-de-Haute-Provence, Provence-Alpes-Côte d'Azur, France
- Bec de l'Aigle, La Ciotat, Marseille, Bouches-du-Rhône, France
- Bec de l'Aigle, Le Noyer, Hautes-Alpes, Provence-Alpes-Côte d'Azur, France
- Bec de l'Aigle, Saint-Firmin, Hautes-Alpes, Provence-Alpes-Côte d'Azur, France
- Bec de l'Aigle, Villar-d'Arêne, Hautes-Alpes, Provence-Alpes-Côte d'Azur, France
- Bec de l'Aigle, Montricher-Albanne, Savoie, Auvergne-Rhône-Alpes, France
- Bec de l'Aigle, Val-d'Oronaye, Alpes-de-Haute-Provence, Provence-Alpes-Côte d'Azur, France
- Bec de l'aigle, La Ciotat, Bouches-du-Rhône, Provence-Alpes-Côte d'Azur, France

<img width="50%" alt="OpenStreetMap" src="https://user-images.githubusercontent.com/2158081/142280321-c25f3370-6a9b-40db-b22d-8424c08ec064.png">

**Comment by vmarc** [comment]
Switched geocoding provider to get more detail in version v3.2.20:

![image](https://user-images.githubusercontent.com/6596480/142465042-79ee1cb5-6da9-4f0e-a63e-713959d3428a.png)

**Comment by pyrog** [comment]
Thank you very much 😃 

Note: the address should be internationalised
