### ISSUE TITLE
Changement comments are missing

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#242]
Since  2021-11-18 05:00  all changeset comments aren't displayed : 

* https://knooppuntnet.nl/en/analysis/hiking/fr/changes<br/><img width="50%" alt="Hiking in France" src="https://user-images.githubusercontent.com/2158081/142716628-cc79cdd9-6015-4354-bbbb-e226ac7d7621.png">

* https://knooppuntnet.nl/en/analysis/changeset/113930230/4806632<br/><img width="50%" alt="Changeset 113930230 004/806/632" src="https://user-images.githubusercontent.com/2158081/142716690-569139b0-4b46-4105-aa1c-887bc02fa980.png">

* https://www.openstreetmap.org/changeset/113930230<br/><img width="33%" alt="Changeset: 113930230" src="https://user-images.githubusercontent.com/2158081/142716737-e4c6a37c-f8d2-4e59-b26f-8b23d8d40b77.png">

**Comment by vmarc** [comment]
A separate application is used to fetch the changeset comments from OpenStreetMap.  To avoid conflicts, this application was stopped during the recovery of the local OverpassApi database last Thursday, and forgotten to restart after knooppuntnet was back in sync on Friday morning.  In the mean while this application has been restarted, and the changeset comments are available again.
