### ISSUE TITLE
NetworkExtraMemberNode for information=board

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#243]
This [information board](https://www.openstreetmap.org/node/9250936850) is used as start of a trail. Usually there is a guidepost nearby, but unfortunately not always.

<img width="615" alt="Vadans information board" src="https://user-images.githubusercontent.com/2158081/142721733-dec010a8-a715-4b52-b809-17b28b513faa.png">

**Comment by vmarc** [comment]
The relevant code is in [NetworkInfoExtraAnalyzer](https://github.com/vmarc/knooppuntnet/blob/becc47173a9862d9b6ef0026b0a68caec425b23a/server/src/main/scala/kpn/server/analyzer/engine/analysis/network/info/analyzers/NetworkInfoExtraAnalyzer.scala#L78):

```
  private def isNodeAllowedInNetworkRelation(tags: Tags): Boolean = {
    tags.has("tourism", "information") &&
      tags.has("information", "map", "guidepost")
  }
```
Can be changed to:

```
  private def isNodeAllowedInNetworkRelation(tags: Tags): Boolean = {
    tags.has("tourism", "information") &&
      tags.has("information", "map", "guidepost", "board")
  }
```

**Comment by pyrog** [comment]
👍

**Comment by vmarc** [comment]
NetworkInfoExtraAnalyzer has been adapted.

Node [9250936850](https://www.openstreetmap.org/node/9250936850) is no longer reported as NetworkExtraMemberNode in network [Cœur du Jura](https://knooppuntnet.nl/nl/analysis/network/13438459/facts).
