### ISSUE TITLE
Tiles rendering not triggered

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#246]
Tiles at current zoom level in route planner seem generated, but not at other zoom levels.
(Web browser cache was cleared and also tested in another browser).

<img width="33%" src="https://user-images.githubusercontent.com/2158081/145706627-cb760adb-ee7e-4020-8687-583127c65d0d.jpg"/> <img width="33%" src="https://user-images.githubusercontent.com/2158081/145706630-3f1c9530-e7ae-4b75-8032-efb458c62467.jpg"/> <img width="33%" src="https://user-images.githubusercontent.com/2158081/145706633-3daa09db-10d3-49c0-897a-7705b83e2259.jpg"/>

**Comment by vmarc** [comment]
With the installation of release 4.0, the update of the tiles with the nodes and routes should now be done immediately as the minute diff files are processed.

The background tile generation is still a manual process that happens every couple of weeks.
