### ISSUE TITLE
RouteRedundantNodes

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#247]
Raise RouteRedundantNodes fact when `note` does not match the names of the nodes.
[Example](https://knooppuntnet.nl/en/analysis/route/13569497):

<img width="852" alt="Capture d’écran 2021-12-21 à 00 07 06" src="https://user-images.githubusercontent.com/2158081/146844483-9135942b-40fb-478b-87e1-1b2c2c01f6e2.png">

**Comment by vmarc** [comment]
Resolved in release 4.

See [unit test code](https://github.com/vmarc/knooppuntnet/blob/develop/server/src/test/scala/kpn/server/analyzer/engine/analysis/caseStudies/Issue247_RouteRedundantNodes.scala).
