### ISSUE TITLE
Some French prepositions in network names are not handled like the others

### ISSUE THREAD

**Issue by StephaneChatty** [vmarc/knooppuntnet#248]
In the list of networks, all names formed as "Réseau pédestre de XXXX" appear as "XXXX" and that is good. However, this works only for prepositions "de" and "du", not for "des" and "d'". I also suspect it does not work for "de la". How we love French and its simplicity!

**Comment by vmarc** [comment]
The [logic for the abbreviation of network names](https://github.com/vmarc/knooppuntnet/blob/develop/server/src/main/scala/kpn/server/analyzer/engine/analysis/network/info/analyzers/NetworkNameAnalyzer.scala) has been adapted.

**Comment by StephaneChatty** [comment]
Thanks!

St.
