### ISSUE TITLE
Filter for unexpected route count

### ISSUE THREAD

**Issue by UncleOwen** [vmarc/knooppuntnet#252]
Hi,

it would be great, if there was a way to filter the /nodes page for nodes with an "unexpected route count". Or any other way to list only those with an unexpected route count. Weren't they listed on /facts some time ago?

(I use "unexpected route count" as my "TODO" list - where is a route missing that I still need to survey?)

**Comment by vmarc** [comment]
Yes, good idea.

There currently is the [IntegrityCheckFailed](https://knooppuntnet.nl/en/analysis/cycling/de/facts/IntegrityCheckFailed) page, but that does not seem to contain nodes that are not in a network. For now, there is  no such page when doing location based analysis.

**Comment by vmarc** [comment]
The filter has been added in the upcoming v4.0 release:

Example pages:
- [Schleswig-Holstein](https://experimental.knooppuntnet.nl/de/analysis/cycling/de/Deutschland:Schleswig-Holstein/nodes)
- [Deutschland](https://experimental.knooppuntnet.nl/de/analysis/cycling/de/Deutschland/nodes)
