### ISSUE TITLE
Duplicated orphan node

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#253]
Node [Teumelet / o](https://knooppuntnet.nl/en/analysis/node/620168928) appear twice in [Orphan nodes](https://knooppuntnet.nl/en/analysis/hiking/fr/orphan-nodes).

It have the tags `rwn_ref` and `lwn_name`.

**Comment by vmarc** [comment]
In release 3 this node is displayed twice in the orphan node list, once as rwn node and once as lwn node.  In release 4 the node is included only once (same on location nodes page).

See [unit test code](https://github.com/vmarc/knooppuntnet/blob/develop/server/src/test/scala/kpn/server/analyzer/engine/analysis/caseStudies/Issue253_DoubleTransportNode.scala).

Another problem with this node in release 3 is that [the node](https://www.openstreetmap.org/node/620168928/history) lost its node tags on Nov 9th 2021, so the node should have been set to non-active, and not included in the orphan list anymore. In release 4 this problem has been resolved.
