### ISSUE TITLE
[Feature Request] Route monitor: easy way to start JOSM editor from map page

### ISSUE THREAD

**Issue by hgcvm** [vmarc/knooppuntnet#258]
For the route monitor. It would be handy if there's a button that opens JOSM when you're on a deviation in the map page. I'm not sure if it's easy to implement or not. Thanks.

**Comment by vmarc** [comment]
@hgcvm Thanks for suggesting this improvement

Implemented in release 4.0.4.

A "josm" link has been added, that brings up a menu with options:
- Load route relation
- Zoom to fit route
- Zoom to selected deviation


Example:

![image823](https://user-images.githubusercontent.com/6596480/184317468-9ba95307-a8c9-4f5f-8adf-e2d30f1f7027.png)
