### ISSUE TITLE
Actual route count is greater than expected

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#259]
The fact xxx is raised but the actual route count equal the expected route count.
Note: a [long hiking route](https://www.openstreetmap.org/relation/3290295) (GR) cross this node.

https://knooppuntnet.nl/en/analysis/network/13969007/facts
Node | Expected | Actual
-- | -- | --
[Chênes Clairs](https://knooppuntnet.nl/en/analysis/node/1622504033) | 3 | **4**

https://knooppuntnet.nl/en/analysis/node/1622504033
Integrity | The expected number of routes (3) matches the number of routes found. :smiley:
-- | --
Routes | [Chênes Clairs - La Biolée](https://knooppuntnet.nl/en/analysis/route/14047498)<br/>[Chênes Clairs - Grand Rambey](https://knooppuntnet.nl/en/analysis/route/14047513)<br/>[Chênes Clairs - La Scie](https://knooppuntnet.nl/en/analysis/route/14051838)

**Comment by pyrog** [comment]
Node [Ferme du Pan](https://knooppuntnet.nl/en/analysis/node/2512611051)
<img width="50%" alt="Network facts" src="https://user-images.githubusercontent.com/2158081/167693962-caa9623b-24c5-4e8d-a2db-74b18bfa2729.png"> 
<img width="50%" alt="Node" src="https://user-images.githubusercontent.com/2158081/167694056-e470e542-5ce1-4453-90db-a9eceb335bb5.png">

**Comment by vmarc** [comment]
With the implementation of release 4.0, the logic around the integrity checks has completely changed. The information in the network facts pages should now match the information in the node pages.
