### ISSUE TITLE
Route A - A with space dash space in the name

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#260]
Same as #233.
* [Frontenex - Voie ferrée - Frontenex - Voie ferrée](https://knooppuntnet.nl/fr/analysis/route/13949070/)

Raised 4 facts:
![Capture d’écran 2022-05-02 à 10 24 18](https://user-images.githubusercontent.com/2158081/166205850-1cfd514a-73ed-4903-abf0-236558bdd0f1.png)

**Comment by vmarc** [comment]
With the implementation of release 4.0, I believe this situation is handled correctly now.

**Comment by lucgential** [comment]
I still have an issue with this one, please have a look: https://knooppuntnet.nl/fr/analysis/route/13542311
For other cases the issue is fixed: https://knooppuntnet.nl/fr/analysis/route/12264240
Thanks for your kind help

**Comment by pyrog** [comment]
In [La Chapelle Saint-Pierre - La Chapelle Saint-Pierre](https://knooppuntnet.nl/fr/analysis/route/12264240) the node name contain only `-` (dash)😉 

In [Les Choseaux - Verneys - Les Choseaux - Verneys](https://knooppuntnet.nl/fr/analysis/route/13542311) the node name contain ` - ` (space dash space)

**Comment by pyrog** [comment]
[RouteNameAnalyzerTest.scala](https://github.com/vmarc/knooppuntnet/blob/86a48b43de2ff12f99a7ae11d28c93c38fe3ebba/server/src/test/scala/kpn/server/analyzer/engine/analysis/route/analyzers/RouteNameAnalyzerTest.scala#L266) should also test "start - node - EndNode"
```scala
    val routeNameAnalysis = analyzeRouteName(Tags.from("name" -> "start - end-node"))
```

Issue is there ?
https://github.com/vmarc/knooppuntnet/blob/86a48b43de2ff12f99a7ae11d28c93c38fe3ebba/server/src/main/scala/kpn/server/analyzer/engine/analysis/route/analyzers/RouteNameAnalyzer.scala#L124-L142

**Comment by pyrog** [comment]
Note: route [Frontenex - Voie ferrée - Frontenex - Voie ferrée](https://knooppuntnet.nl/fr/analysis/route/13949070/) don't raise an error because the dash was removed from the Node name.


[See version 4](https://knooppuntnet.nl/en/analysis/route/13949070/changes?pageIndex=0&impact=false)
![Capture d’écran 2022-08-03 à 14 55 44](https://user-images.githubusercontent.com/2158081/182613136-a191f257-31ee-452b-8197-8a1ed29e1723.png)

**Comment by pyrog** [comment]
Note: In France, city name are "normalised".

- `Saint-Pierre` is a city (Saint Peter's)
- `Saint - Pierre` could be a route from `Saint` to `Pierre` or a place called `Saint - Pierre`
- `Saint-Maurice-Crillat` is the merging of `Saint-Maurice` and `Crillat`
- `Saint-Maurice-Crillat - Saint-Maurice-Crillat` could be a loop around this village (the case of this issue)
