### ISSUE TITLE
Route monitor: Deviation with "-" as length doesn't show on the map

### ISSUE THREAD

**Issue by hgcvm** [vmarc/knooppuntnet#261]
Not sure what could cause this, but in this example https://experimental.knooppuntnet.be/en/monitor/groups/GRV/routes/P-GR-122-scheldeland/map, there are four segments that don't show up on the map when you click them: 9, 14, 15 and 16. (the ones with a dash a deviation value)

**Comment by vmarc** [comment]
@hgcvm thanks for reporting this problem

Fixed in release 4.0.4: deviations with zero length are no longer shown in the deviation list
