### ISSUE TITLE
Paving stones error

### ISSUE THREAD

**Issue by tastrax** [vmarc/knooppuntnet#265]
Hi Folks,

I think these keys and values are incorrect

{
"key": "surface",
"value": "paving_stones",
"object_types": [
"way"
]
},

{
"key": "surface",
"value": "paving_stones:30",
"object_types": [
"way"
]
},

Should they actually be

{
**"key": "paving_stones:length",
"value": "30 cm",**
"object_types": [
"way"
]
},

as per https://wiki.openstreetmap.org/wiki/Tag:surface%3Dpaving_stones

https://taginfo.openstreetmap.org/tags/surface=paving_stones%3A30#projects

**Comment by vmarc** [comment]
The tag value _"paving_stones:30"_ has been removed from the surface analyzer logic. The file taginfo.json has been updated accordingly (TagInfoReport), so that knooppuntnet is not listed in the [taginfo](https://taginfo.openstreetmap.org/tags/surface=paving_stones%3A30#projects) page.
