### ISSUE TITLE
Misleading display of nodes at network connections

### ISSUE THREAD

**Issue by StC-OSM** [vmarc/knooppuntnet#266]
In https://knooppuntnet.nl/fr/analysis/network/13478859/map?position=45.17319652,5.80409839,13, the two western-most nodes of network "Grésivaudan" (Relais de Romage and Les Combettes) actually do not belong to that network relation. They belong to the network relation "Grenoble-Alpes", and are connected to nodes of "Grésivaudan" by route relations that belong to both network relations with role "connection".

In my understanding of the wiki, the nodes and relations are correctly tagged and connected. Am I right?

In my perception, the display is misleading because it does not correctly reflect the status of nodes, does not show the particular role of the route relations with "connection" roles, and creates questions as to where the borderline actually is.

**Comment by vmarc** [comment]
This issue was resolved with the changes for #410 in release 4.3.51.
