### ISSUE TITLE
Monitor - cannot rename route

### ISSUE THREAD

**Issue by vmarc** [vmarc/knooppuntnet#270]
When trying to rename a route, the response is "500 - Internal server error".

In the server log I can see the route update logic trying to read the existing route details using the new name instead of the old name.

**Comment by pyrog** [comment]
Note: this name is a simple label for humans. Could you allow all? UTF chars (especially space, dash…)

**Comment by vmarc** [comment]
The route update logic has been fixed.

About the characters that can be used in the group names and the route names: currently these names can consist of a-zA-Z0-9 and dash (with a maximum length of 15 characters). This naming convention was already in use for the GR routes. At the time it also seemed like a good idea to limit the available characters because the names are used in the url's. But this limitation is in not really necessary: we are using location names already in url's, and these contain all kind of characters and spaces and accents, etc.

This issue is left open to lift the character limitation on the name.

**Comment by vmarc** [comment]
The restriction on the characters that can be used in group and route names has been lifted in release 4.0.32. It is now possible to have accents, spaces, etc. in the names.
