### ISSUE TITLE
Monitor - Add URL for reference file

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#271]
Currently, the file could be only downloaded.

Could you add a field for an URL, i.e. to download it directly from the official site ?
This is useful for documenting the source of this reference data.

Also, the date of the last downloading is precious (i.e. when the reference file is updated and the name don't change at each new version).

**Comment by vmarc** [comment]
The day that the contents of the reference file is/was valid is important information.

In the next release, an extra field has been added in the route definition page to enter this reference day:

![route-reference-details](https://user-images.githubusercontent.com/6596480/205103813-4f373a59-b0d5-45b0-9b20-54b45eefcabb.png)

Also, an extra comment field has been added. This can be used to further clarify where the gpx trace is coming from (for example url for download from official site), or any other information that can help the user looking at the monitor analysis results.

![route-comment](https://user-images.githubusercontent.com/6596480/205104317-16001539-6069-44fc-b738-5508dfe055b9.png)

The reference day is shown in the route list:


![route-overview](https://user-images.githubusercontent.com/6596480/205104703-1ad8c5eb-cc42-4af5-a94a-12e0140d9284.png)

The reference day,  the gpx filename and the comment are shown in the route details page:

![route-detail](https://user-images.githubusercontent.com/6596480/205105126-8928c266-f0a6-4288-a180-f1c29433b1c2.png)

**Comment by vmarc** [comment]
Implemented in release 4.0.26

**Comment by pyrog** [comment]
Comment is a good point, thank you 😄 

Having an URL avoid downloading to the laptop and uploading gpx file from the laptop.
(Also a periodic download could be added in the future to fetch updates).

Marc, could you please reopen this issue?
