### ISSUE TITLE
Monitor - manage roundabouts

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#272]
When a roundabout is part of a route, KPN detect a discontinuity and create a new OSM segment.

<img width="75%" alt="Roundabout" src="https://user-images.githubusercontent.com/2158081/199706611-09108017-246d-4e57-ab30-500dd6c4a6f5.png">

In this example, the route is "artificially" cut in 7 segments.
Shortest (2, 4 and 7) are roundabouts.

**Comment by pyrog** [comment]
Another example with a roundabout in one piece, [here](https://knooppuntnet.nl/fr/monitor/groups/fr-iwn-Camino/routes/Voie-Soulac/map?mode=osm-segments&reference=false&matches=false&deviations=false&osm-relation=true&selected-deviation=0&selected-osm-segment=2&position=44.14790781,-1.21589212,20) in Voie de Soulac.
Way [571075309](https://www.openstreetmap.org/way/571075309).
<img width="80%" alt="Roundabout" src="https://user-images.githubusercontent.com/2158081/234099735-e25aa67c-b61b-4126-98ca-c625f672ac36.png">

**Comment by vmarc** [comment]
In release v4.3.0, the route analysis logic has been changed. Roundabout processing has been much improved, especially for cycling routes where forward and backward direction are taken into account.  Additional logic that allows going against the direction of traffic for hiking routes to take the shortest path (issue #313) has not been implemented yet at this moment.
