### ISSUE TITLE
[Planner] In 'Last survey date' display, improve visibility for unknown 

### ISSUE THREAD

**Issue by pelderson** [vmarc/knooppuntnet#273]
When no survey:date is set, routes appear light grey in the PLanner. This makes it hard to see where the unsurveyed routes are. Especially since the coloured routes really stand out.  Could a colour be used which stands out more against the background? Maybe a darker grey would be enough. 

The reason I ask is, I plan to do a survey of the network in my neighbourhood, with a group of volunteers, using this display to monitor progress and plan new survey trips. As it is now, it's very easy to overlook the routes!

**Comment by vmarc** [comment]
Light grey was changed to bright yellow:

![survey](https://user-images.githubusercontent.com/6596480/200660264-ff417f9c-7929-4af2-9856-2da482c37015.png)

**Comment by pelderson** [comment]
That's definitely more visible! Nearly got a shock!
