### ISSUE TITLE
Handle coordinates in monitor URL

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#275]
Add query parameters:
- `?position=46.79618546,5.62757432,15`
- deviation id i.e. `&deviation=2`
- map layers i.e. `&layers=1001`

Part of #202.
 
<img width="75%" alt="Screen copy" src="https://user-images.githubusercontent.com/2158081/200158777-f7958c6a-58be-432e-a4cd-2492e7df8d4c.png">

**Comment by vmarc** [comment]
Query parameters added in release 4.0.21.

- mode (comparison/osm-segments)
- reference: show blue line, gpx or osm reference (true/false)
- matches: show green line, reference matches osm relation  (true/false)
- deviations: show red line, reference does not match osm relation (true/false)
- osm-relation: show yellow line, osm relation (true/false)
- selected-deviation (id)
- selected-osm-segment (id)
- position (map position)
