### ISSUE TITLE
Add geolocation and search control on analysis map

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#277]
Could you add controls on the analysis map to easily go to the current location or to a known place (like in Route planner) ?

<img width="33%" alt="Route planner" valign="top" src="https://user-images.githubusercontent.com/2158081/200167084-e13bebce-26d1-460c-b8b6-177501688946.png"> <img width="50%" alt="Analysis" src="https://user-images.githubusercontent.com/2158081/200167116-ad84fa6b-842f-4480-abb9-0cab936f0506.png">

**Comment by vmarc** [comment]
Implemented in release v4.3.4.
