### ISSUE TITLE
[Planner] When nodes are close, only one is rendered

### ISSUE THREAD

**Issue by pelderson** [vmarc/knooppuntnet#279]
When nodes are close to each other, theay are rendered separately only at high zoom levels. Zooming out, only one remains visible, the other completely disappears and there is no way you can see that it is there. 
E.g. https://knooppuntnet.nl/nl/map/hiking?position=51.97330528,4.55130866,16 nodes 19 and 64 visible
vs https://knooppuntnet.nl/nl/map/hiking?position=51.97386455,4.55287131,16 only node 19 visible. 
The maps in Analysis have the same issue. 

I understand the rendering problem. Other planners e.g. [Wandelnet Routeplanner](https://wandelnet.planner.routemaker.nl/planner/wandelen) have the seem issue (on their planner, the 64 wins).

Would it be possible to have at least a visible indication that nodes are stacked? Maybe something like a double outline?

**Comment by vmarc** [comment]
Perhaps the  concept of _clusters_ in OpenLayers is something to look into for a solution.

- [Dynamic clusters example](https://openlayers.org/en/latest/examples/clusters-dynamic.html)

- [Clustered features example](https://openlayers.org/en/latest/examples/cluster.html)

**Comment by pelderson** [comment]
Problem with these clusters is that they show numbers in circles - exactly what nodes do. This would be highly confusing. Maybe if the cluster wouldn't show a number at all and/or the cluster circle would be clearly different - but I can't tell if that is an option. 
Waymarkedtrails just lets the nodes overlap: https://hiking.waymarkedtrails.org/#?map=14.0/51.9822/4.6431 which is totally clear to the user.

**Comment by vmarc** [comment]
Implemented in next release (at this time, not publicly available yet).

The map display options have been changed to always show all nodes (no longer using the OpenLayers declutter functionality).  This makes the map less nice (perhaps a matter of taste), but it avoids the problem with nodes disappearing or not being shown at all.

> ![overlapping-nodes](https://github.com/vmarc/knooppuntnet/assets/6596480/237ed3ca-6db3-4c22-ba01-9e32b6bd11e8)

**Comment by vmarc** [comment]
Solution published in release v4.1.0.
