### ISSUE TITLE
[monitor]  No GPX, so no known deviations, although there is a valid GPX uploaded

### ISSUE THREAD

**Issue by hgcvm** [vmarc/knooppuntnet#281]
https://knooppuntnet.be/en/monitor/groups/GRV/routes/p61
This one says "No GPX, so no known deviations. ", but I think I uploaded a GPX. So the error message is confusing. 
( I couldn't add the gpx here as attachment. Should I email the gpx, or can you find it on the server?)
It's a very very short route.

**Comment by vmarc** [comment]
The message _"No GPX, so no known deviations. "_ is wrong, and very misleading.

I do see the reference in the database, and also in the [map](https://knooppuntnet.be/en/monitor/groups/GRV/routes/p61/map?mode=comparison&reference=true&matches=false&deviations=false&osm-relation=true&selected-deviation=0&selected-osm-segment=0&position=50.80627171,4.92971166,18): the blue line (in the default settings the green line) represents the GPX trace.

**Comment by hgcvm** [comment]
Similar issue here: https://knooppuntnet.be/en/monitor/groups/GRV/routes/p54

**Comment by hgcvm** [comment]
https://knooppuntnet.be/en/monitor/groups/GRV/routes/p53
is another example, if this helps.

**Comment by vmarc** [comment]
Fixed in release 4.0.26
