### ISSUE TITLE
Monitor - route relations with sub-relations

### ISSUE THREAD

**Issue by vmarc** [vmarc/knooppuntnet#283]
In following example, the monitor reports an extra obsolete segment for the way to the abbey. The red and blue arrows represent 2 sub relations that stop and start at the abbey. So the hike is continuous and no obsolete segment should be reported.

![img](https://user-images.githubusercontent.com/6596480/204864998-7d2c6177-17d5-4a91-b429-35807bdda0a0.png)

Thanks to @pyrog for reporting this problem (telegram).

**Comment by vmarc** [comment]
Today the logic for relations with sub-relations is to simply throw all ways from all relations together and treat it as one route. The intention is to change this so that the sub-relations are analyzed separately. This way the above example should come out ok.

Performing separate analysis per sub-relation is expected to also reduce the use of resoures on the server (both time and memory use).  Even more so when in the future the processing of changes would only be done for the sub-relation that is impacted, and not for all sub-relations.

Details for example above:
- [darkgreen way](https://www.openstreetmap.org/way/190048670) (wrongly considered extra segment)
- [blue sub-relation](https://www.openstreetmap.org/relation/12864055)
- [red sub-relation](https://www.openstreetmap.org/relation/12864054)

**Comment by vmarc** [comment]
Some large routes:

|name|relationId|relations|ways|loaded|xml|geojson|
|----|----------|----|----------|---|-------|-------|
|LAW-2|532494|23|2486|4406ms|3680K|336K|
|LAW-3|2801085|21|2174|3541ms|3220K|292K|
|LAW-5-1|1959162|12|1108|1971ms|1849K|177K|
|LAW-5-2|9237672|14|1382|2764ms|2412K|238K|
|LAW-5-3|4097849|15|994|1919ms|1765K|165K|
|LAW-9-1|312993|14|1266|2044ms|1995K|182K|
|LAW-9-2|156951|14|1530|2391ms|2410K|229K|
|E2|1976033|5|4745|5971ms|15671K|1738K|
|E3|6585798|35|5630|5661ms|12208K|1289K|
|E4|171821|18|3261|4897ms|12173K|1391K|
|E5|12844449|50|11033|10972ms|22896K|2414K|
|E7|11865350|16|3234|4285ms|10723K|1214K|
|E9|1956185|82|15347|15696ms|40887K|4505K|
|E12|12744629|25|2322|3414ms|5383K|551K|

**Comment by pelderson** [comment]
Side note: The abbey situation could have been present as approach or excursion (single relation). See https://wiki.openstreetmap.org/wiki/Roles_for_recreational_route_relations
You will probably encounter this at some time in the future.

**Comment by pyrog** [comment]
Side notes:
- Sub relations with role `alternative`, `approach`, `connection` or `excursion` shouldn't part of the main segment.
- They should be "removed" from the segment count to compute the smiley.
- The structure tab could have new rows (**Deviations**, **OSM segments** and **smiley**) to detail which stage (sub relation) need fix.
- A new color scheme could be added to the map: color relations by roles.

**Comment by vmarc** [comment]
In the next release, the analysis of subrelations of superroutes has been improved.

The analysis is per subrelation. The way to the abbey is no longer considered an "obsolete segment".


> ![voie-beauport-2](https://github.com/vmarc/knooppuntnet/assets/6596480/f7a2e923-82f6-496d-a2d3-3544062af839)

> ![voie-beauport-1](https://github.com/vmarc/knooppuntnet/assets/6596480/ac21c492-c4b6-4e80-b8c6-33756c98dbfb)

> ![voie-beauport-3](https://github.com/vmarc/knooppuntnet/assets/6596480/ca92b04b-caa1-4b2d-985d-4664fdb95f2f)


Special handling of subrelation roles "alternative", "approach", "connection" or "excursion" (shouldn't part of the main segment) is not included yet.  This should be perhaps be the subject of a separate github issue.

**Comment by pelderson** [comment]
Question about how this works for the admin user: Does Knooppuntnet Monitor retrieve the subrelations, so that the adminuser only has to add the separate gpx's for each subrelation?

**Comment by vmarc** [comment]
The admin user only has to specify the parent route relation id.  The subrelations (could be several levels deep) do not have to be specified. Separate gpx traces should be uploaded for each subrelation with ways in it.

**Comment by vmarc** [comment]
Published in release v4.1.0.
