### ISSUE TITLE
[Monitor] Multiple gpx-files for a route

### ISSUE THREAD

**Issue by pelderson** [vmarc/knooppuntnet#293]
Would it be possible to define a series of gpx reference files for a GR/LAW/SP?

Reason: In Nederland, most walking routes consist of daily sections, that is superroute relations containing section route relations. Which is handled by Monitor. However, the reference gpx files are only available per section.
(Sometimes a gpx is availiable for the whole route, but this usually is processed to contain less trackpoints, which would result in many, many items ampng which the true differences would get lost.)
Would it be possible to define a series of gpx reference files for a GR/LAW/SP?

**Comment by vmarc** [comment]
The next release supports GPX references per subrelation in a superroute.

The upload button in the actions column in the structure table on the details page can be used to upload a detailed GPX trace per subrelation.  The button with the garbage icon can be used to remove the GPX reference.

> ![groene-hart-pad](https://github.com/vmarc/knooppuntnet/assets/6596480/eeb8711f-7692-4eaf-b540-1772b008ddf0)

**Comment by vmarc** [comment]
Solution published in release v4.1.0.
