### ISSUE TITLE
Add icons for monitor group actions

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#298]
At least in french, labels update and delete are long and displayed on 2 lines.
Could you please use icons instead labels ?

<img width="50%" alt="french" src="https://user-images.githubusercontent.com/2158081/207826389-49fce7bb-196d-439e-887d-f7327d58e788.png"> <img width="50%" alt="english" src="https://user-images.githubusercontent.com/2158081/207826531-6f682b5c-db00-45ee-807a-013d9d680c47.png">

**Comment by vmarc** [comment]
Implemented in 4.0.29.

![icons](https://user-images.githubusercontent.com/6596480/208727380-601d47bd-5eea-4920-b948-2caebeb5d1c2.png)
