### ISSUE TITLE
Wrong error message when monitored route has no members

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#299]
If a monitor have an OSM relation without any ways, KPN display the following message:
_"OSM relation missing in route definition, so no analysis results."_

Also, the map isn't zoomed to the gpx reference file.

Example: [Sur les Pas des Huguenots en Cévennes, stage 3](https://knooppuntnet.nl/en/monitor/groups/eu-iwn-Huguenot/routes/SPHC03/map?mode=comparison&reference=true&matches=true&deviations=false&osm-relation=false&selected-deviation=0&selected-osm-segment=0)
<img width="50%" alt="Sur les Pas des Huguenots en Cévennes, stage 3" src="https://user-images.githubusercontent.com/2158081/207839043-26e981e8-b110-4a35-80a2-16720f7dcafa.png">

**Note:** if the monitor have only a gpx reference file without an OSM relation, the display is correct.

Example: [Sur les Pas des Huguenots en Cévennes, stage 10](https://knooppuntnet.nl/en/monitor/groups/eu-iwn-Huguenot/routes/SPHC10/map)
<img width="50%" alt="[Sur les Pas des Huguenots en Cévennes, stage 10" src="https://user-images.githubusercontent.com/2158081/207839664-fcf39ae8-47af-4d6d-9ba0-d44908adfbc3.png">

**Comment by vmarc** [comment]
Fixed in release 4.0.30.
