### ISSUE TITLE
Error on page of route 28-40 (relation 6395727)

### ISSUE THREAD

**Issue by A67-A67** [vmarc/knooppuntnet#30]

**Comment by A67-A67** [comment]
The [page of relation 6395727](https://knooppuntnet.nl/nl/route/6395727) gives an error while it seems to be a correct route relation [in Openstreetmap](https://www.openstreetmap.org/relation/6395727).

**Comment by vmarc** [comment]
@A67-A67 Thanks for reporting this issue.

The [first way](https://www.openstreetmap.org/way/429929302) in the [route relation](https://www.openstreetmap.org/relation/6395727) contains only one node. This is unexpected for the logic that analyzes the change in route geometry for the route history.

This is [fixed](https://github.com/vmarc/knooppuntnet/commit/2466ff948ace35637515341d62ad4eb3eaaffc59) in v2.0.11: ways with just one node are now ignored when analyzing route geometry changes.
