### ISSUE TITLE
Add OpenStreetMap layer on every maps

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#301]
Like for [Monitor](https://knooppuntnet.nl/en/monitor/groups/fr-nwn/routes/R2/map?mode=comparison&reference=false&matches=true&deviations=false&osm-relation=true&selected-deviation=0&selected-osm-segment=0&position=-21.12774973,56.01981572,10) map, could you add the OSM bitmap layer too for [Analysis by network](https://knooppuntnet.nl/en/analysis/network/13436769/map?position=45.18963377,5.71162316,18), [Analysis by location](https://knooppuntnet.nl/en/analysis/hiking/fr/France:Isère/map) and [Route planner](https://knooppuntnet.nl/en/map/hiking?position=45.19438505,5.72169048,16) ?

<img width="50%" alt="Monitor" src="https://user-images.githubusercontent.com/2158081/210578145-b126a14e-b1a8-4c45-b73a-4280a44e92f2.png">

**Comment by vmarc** [comment]
The OSM layer is added to all maps.
