### ISSUE TITLE
NetworkExtraMemberNode for information=route_marker

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#302]
Some route markers are on small poles. They are part of the network.

Examples:
[Canton de la Chambre](https://knooppuntnet.nl/en/analysis/network/13476301/facts) and especially node [9625771895](https://www.openstreetmap.org/node/9625771895).

**Comment by vmarc** [comment]
Implemented in server release v4.2.3 thanks to @Henry00572.
