### ISSUE TITLE
Usable in Sweden?

### ISSUE THREAD

**Issue by dpriskorn** [vmarc/knooppuntnet#304]
Hi. I'm interesting in running this for the network of hiking paths in Sweden. Is that possible? Is there documentation for me to set up the whole thing or could you just add support for Sweden on the instance you are running?

**Comment by vmarc** [comment]
The simplest would be to add support for Sweden in the current instance.

The [analysis](https://knooppuntnet.nl/en/analysis) and [planner](https://knooppuntnet.nl/en/map/hiking) parts of knooppuntnet deal with node networks (routes with tag _network:type=node_network_).

At this moment I do not seem to find any such routes in Sweden. I used following overpass query:

```
[out:json][timeout:25];
{{geocodeArea:Sweden}}->.searchArea;
(
  relation["type"="route"]["network:type"="node_network"](area.searchArea);
);
out ids;
```

Are you planning to add such routes?

The [monitor](https://knooppuntnet.nl/en/monitor) part of knooppuntnet is not country specific, and can be used for routes in Sweden today.

I added an example: [European long distance path E6 - part Sweden](https://knooppuntnet.nl/en/monitor/groups/test/routes/E6-Sweden). 

The deviations shown in the [map](https://knooppuntnet.nl/en/monitor/groups/test/routes/E6-Sweden/map) page shows the differences found between the situation on Januari 1st and now.

Currently knooppuntnet does not have its own background tiles for Sweden for use in the map page. These could be added. For now you can switch to using OpenStreetMap background tiles by using the layerselector in the upper right corner of the map and clicking the OpenStreetMap checkbox.

If you want to try out the monitor functionality for yourself (add routes to be monitored), let me know your OSM user id (here or via message to [vmarc](https://www.openstreetmap.org/user/vmarc)).

**Comment by dpriskorn** [comment]
Thanks for the reply. I have never seen any kind of node network on the ground here unfortunately. I know that Norway have something similar though. See https://hiking.waymarkedtrails.org/#route?id=5461243&type=relation&map=10.0/61.3918/8.2925
![image](https://user-images.githubusercontent.com/68460690/217763186-be623e92-86e0-4b00-b5a5-92aa770e83d2.png)
