### ISSUE TITLE
Display all routes with facts in analysis maps

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#306]
* [route 15477154](https://knooppuntnet.nl/en/analysis/route/15477154/map?position=45.63303359,5.95075933,14)<br/>![route 15477154](https://user-images.githubusercontent.com/2158081/219857823-80900ac1-c123-4fb3-afe2-b51e75ea8644.jpg)

* [route 15477155](https://knooppuntnet.nl/en/analysis/route/15477155/map?position=45.63303359,5.95075933,14)<br/>![map with route 15477155](https://user-images.githubusercontent.com/2158081/219857791-73af18db-3017-4e98-89dd-9826a99f1f45.jpg)

* [Hiking in Grand Chambéry](https://knooppuntnet.nl/en/analysis/hiking/fr/France:Savoy:Grand%20Chambéry/map?position=45.63303359,5.95075933,14): no routes with facts are rendered<br/>
<img width="100%" alt="Map of Grand Chambéry (place)" src="https://user-images.githubusercontent.com/2158081/219857914-0160f61d-70e1-4187-8e10-9cafef2b52a3.png">

**Comment by vmarc** [comment]
Fixed with issue #385
