### ISSUE TITLE
Remember Analysis location map settings

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#307]
Links for a [route](https://knooppuntnet.nl/en/analysis/route/15477154/map?position=45.63303359,5.95075933,14) or for a [network](https://knooppuntnet.nl/en/analysis/network/13455079/map?position=45.63303359,5.95075933,14) works, but not for a [locality](https://knooppuntnet.nl/en/analysis/hiking/fr/France:Savoy:Grand%20Chambéry/map?position=45.63303359,5.95075933,14).
See #206

<img width="25%" alt="Route" src="https://user-images.githubusercontent.com/2158081/219863051-fcb2d403-dfad-4173-b032-b8d878460143.png"> <img width="25%" alt="Network" src="https://user-images.githubusercontent.com/2158081/219861274-03bc8358-794e-4b22-a2b9-faf96541b0f6.png"> <img width="25%" alt="Locality" src="https://user-images.githubusercontent.com/2158081/219862162-cca0ef3f-d423-4787-8940-c1f3eb39169b.png">

**Comment by vmarc** [comment]
Implemented in v4.3.37.
