### ISSUE TITLE
Display last monitoring date

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#309]
This timestamp is useful in [Detail](https://knooppuntnet.nl/en/monitor/groups/fr-iwn-Camino/routes/VPSM13) and [Map](https://knooppuntnet.nl/en/monitor/groups/fr-iwn-Camino/routes/VPSM13/map) views especially because the analysis is run every half hours.

**Comment by vmarc** [comment]
Implemented in next release (at this time, not publicly available yet).

Route details page:

![latest-analysis-details](https://github.com/vmarc/knooppuntnet/assets/6596480/3dd7d394-4514-42a3-9180-a629ca458e65)

Route map page:

![latest-analysis-map](https://github.com/vmarc/knooppuntnet/assets/6596480/2fad5ed7-ae87-4656-98e4-df8170ee8789)

**Comment by vmarc** [comment]
Solution published in release v4.1.0.
