### ISSUE TITLE
[Monitor] Management of long linear routes

### ISSUE THREAD

**Issue by StC-OSM** [vmarc/knooppuntnet#310]
Experience of helping a route operator to get started with OSM and knooppuntnet shows that managing very large relations or super-relations is not very practical. Working (and collaborating!) at the level of sub-relations is more comfortable. in the current version, however, creating and managing sub-relations is tedious and two features could help improve that:

 - automatically creating all sub-relations of a super-relation when it is added by an administrator. If necessary, adding individual GPX references can be left to said administrator in a later step.

 - managing super-relations as groups in the UI.  The group structure would thus become recursive but this probably does not create major problems. It would help make the current groups manageable, whereas adding all sub-relations tends to make the listing of groups unusable (see https://knooppuntnet.nl/fr/monitor/groups/fr-iwn-Camino for an example).

**Comment by vmarc** [comment]
Better support for superroutes has been added to next release.

A new route type has been added that allows for gpx traces per subrelation in a super route:

> ![multi-gpx](https://github.com/vmarc/knooppuntnet/assets/6596480/72d0739d-599f-4402-ba60-8f6228b8549a)

Subrelation GPX upload through structure section in details page:

> ![multi-gpx-2](https://github.com/vmarc/knooppuntnet/assets/6596480/8ff65f5f-a133-4c78-b6e2-fa7465fe4776)

**Comment by vmarc** [comment]
Solution published in release v4.1.0.
