### ISSUE TITLE
Monitor don't detect disordered members

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#312]
WMT display gap in elevation in the elevation profile but this relation is fine for KPN because there is no deviation.

[KPN](https://knooppuntnet.nl/en/monitor/groups/fr-iwn-Camino/routes/VPSM03/map)
<img width="50%" alt="Knoopuntnet" src="https://user-images.githubusercontent.com/2158081/230487502-ec3ad816-0f17-4c0c-be34-b6ff468b3c8a.png">

[WMT](https://hiking.waymarkedtrails.org/#route?id=15656716&type=relation&map=12.0/48.3362/-4.2217)
<img width="50%" alt="Waymarked trails" src="https://user-images.githubusercontent.com/2158081/230487557-1bf7aca2-fac3-46db-b97c-e942d8ed2498.png">

**Comment by vmarc** [comment]
In release v4.3.0, the route analysis logic has been changed. The new logic no longer tries to change the sorting order of the route relation members.  From now on, when the sorting order is incorrect, this will show in the analysis result.
