### ISSUE TITLE
Monitor - wrong distance in route relations with sub-relations

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#314]
In [Voie des Capitales](https://knooppuntnet.nl/en/monitor/groups/fr-iwn-Camino/routes/Voie-Capitales) KPN compute à length of 238 km but display a length of the parent relation of 197 km.

This route have the particularity of 3 levels of relations (this will be probably redesigned with only 2 levels).

238 km seem to be the length of the parent relation 197 km, plus the length of the first stage of the bottom level 40 km.
(Rennes - Saint-Malo-de-Phily is counted twice)

<img width="80%" alt="Structure of Voie des Capitales" src="https://user-images.githubusercontent.com/2158081/234513202-15de8bfa-2fab-4ec7-b859-8000df2a7c82.png">

**Comment by pyrog** [comment]
Side effect?
This relation don't have any reference length, KPN don't display a smiley even if there is no deviation and only one segment.

<img width="100%" alt="routes table" src="https://user-images.githubusercontent.com/2158081/234519394-a270f898-c654-4cc2-bf8d-b43ecf52e15d.png">

**Comment by pyrog** [comment]
Same issue with other routes.

Route | Summary | Distance
-- | -- | --
[Voie-St-Mathieu](https://knooppuntnet.nl/en/monitor/groups/fr-iwn-Camino/routes/Voie-St-Mathieu) | 685 km | 538 km
[Chemin-Conques](https://knooppuntnet.nl/en/monitor/groups/fr-iwn-Camino/routes/Chemin-Conques) | 274 km | 230 km
[Chemin-Vendeen](https://knooppuntnet.nl/en/monitor/groups/fr-iwn-Camino/routes/Chemin-Vendeen) | 299 km | 248 km
[Via-Arverna](https://knooppuntnet.nl/en/monitor/groups/fr-iwn-Camino/routes/Via-Arverna) | 654 km | 575 km
[Voie-Anglais](https://knooppuntnet.nl/en/monitor/groups/fr-iwn-Camino/routes/Voie-Anglais) | 293 km | 186 km
[Voie-Beauport](https://knooppuntnet.nl/en/monitor/groups/fr-iwn-Camino/routes/Voie-Beauport) | 264 km | 212 km
[Voie-Belgique ](https://knooppuntnet.nl/en/monitor/groups/fr-iwn-Camino/routes/Voie-Belgique)| 158 km | [123 km](https://hiking.waymarkedtrails.org/#route?id=8382432&type=relation)
[Voie-Capitales](https://knooppuntnet.nl/en/monitor/groups/fr-iwn-Camino/routes/Voie-Capitales) | 238 km | 197 km
…

**Comment by vmarc** [comment]
The route length calculation is improved in the next release (at this time, not publicly available yet).

If the route relation (or subrelation) has subrelations, the sum of the length of all **sub**relations is displayed in bold. The sum of the lengths of all **ways** in a (sub-)relation is displayed in normal font (so to be clear: the figure in normal font does not include the lengths of the subrelations). If a (sub-)relation has both its own ways and subrelations, there is both a figure in normal font and in bold font.

Example:

> ![issue314-1](https://github.com/vmarc/knooppuntnet/assets/6596480/8565bef1-42c5-43b7-ae39-4f741a6ea208)

Another example:

> ![issue314-2](https://github.com/vmarc/knooppuntnet/assets/6596480/04b9aeac-8c98-41c8-9600-4fd6a922ceb3)

Example showing both bold and normal figure in the main relation:

> ![issue314-3](https://github.com/vmarc/knooppuntnet/assets/6596480/d12469c9-c834-4550-9e8a-1d87278d199e)

**Comment by pyrog** [comment]
Thanks a lot Marc.
Especially the last example that show ways members of the super route.

Lengths are overrated compared to Waymarked Trails.
Is KPN wrong, WMT or both?

**Comment by vmarc** [comment]
The route length calculation has been changed to use the dedicated "Haversine" code in knooppuntnet instead of using the "geometry length" function from the jts graphical library.  The result now better matches reality.

> ![route-distance-calculation](https://github.com/vmarc/knooppuntnet/assets/6596480/ea3891d5-0a20-45be-b6ad-82aefbfc1cab)

**Comment by vmarc** [comment]
Solution published in release v4.1.0.
