### ISSUE TITLE
Monitor - Route details aren't updated

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#315]
I just updated this monitor and use the reference itself (date at tomorrow !).
At least the reference date and message aren't updated (probably, the distance too).

```
29/04/2023
GPX: "voie_pays_morlaix_mogueriec_morlaix-5996537-1682755312-164.gpx"
45 km
```
<img width="80%" alt="Route details tab" src="https://user-images.githubusercontent.com/2158081/235422457-7320e9c9-1e68-4c9a-99d9-743f02f54bfa.png">

**Comment by vmarc** [comment]
New improved logic published in release v4.1.0.
