### ISSUE TITLE
Monitor - Display from, to, osm:symbol for a new route

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#317]
After pressing **Verify route relation id** button, display also `from`, `to` and `osm:symbol`.

**Note:** image of the symbol could be generated by waymarkedtrails.org/api
`osmc:symbol=blue:blue:shell_modern` give ![](https://hiking.waymarkedtrails.org/api/v1/symbols/from_tags/NAT?osmc:symbol=blue%3Ablue%3Ashell_modern)

<img width="50%" alt="Verify route relation id" src="https://github.com/vmarc/knooppuntnet/assets/2158081/be26789b-a524-4614-9c85-6ca9b82d76f4">

**Comment by vmarc** [comment]
Implemented in next release (at this time, not publicly available yet).

Information from following route relation tags is shown (if available):
- name
- ref
- from
- to
- operator
- website
- osmc:symbol

Example:

> ![monitor-add-route](https://github.com/vmarc/knooppuntnet/assets/6596480/609e982e-16b5-449c-8959-ede98dbe7c2d)

Following information is no longer shown when verifying the route relation id:
- number of ways
- number of nodes
- total number of relations (main relation and subrelations, if any)
- total route length

For large super-routes it simply did take too much time to collect this information. For example route [European long distance path E9](https://www.openstreetmap.org/relation/1254604) consists of 255 relations that all had to be retrieved in full detail to count the number of ways, nodes and to calculate the total route length. This could take several minutes before showing the result.

**Comment by vmarc** [comment]
The route symbol is now also shown in:
- the monitor group routes page
- the monitor route detail page (including in route structure)
- the network analysis routes page
- the location analysis routes page
- the route analysis detail page

Monitor group routes page:

> ![monitor-group-routes](https://github.com/vmarc/knooppuntnet/assets/6596480/1717242b-b948-472b-8627-b08ead9dbad3)

Monitor route details page:

> ![monitor-route-details](https://github.com/vmarc/knooppuntnet/assets/6596480/2c7e9ca0-26ef-4f83-9db2-cf1ec66259d1)

Location routes page:

> ![location-routes](https://github.com/vmarc/knooppuntnet/assets/6596480/0935af02-212b-44da-b548-ebc7880526aa)

Network routes page:

> ![network-routes](https://github.com/vmarc/knooppuntnet/assets/6596480/ae281fcf-3c5c-4940-8899-fb111f10b655)

> ![network-routes-2](https://github.com/vmarc/knooppuntnet/assets/6596480/b5a935d9-7e49-4e07-89ad-e65115955205)

Route analysis detail page:

> ![route-analysis](https://github.com/vmarc/knooppuntnet/assets/6596480/f8eab9ad-49e1-4a0b-bacc-14c900d65ac8)

**Comment by vmarc** [comment]
Following symbol shapes are currently supported:

> ![symbol-shapes](https://github.com/vmarc/knooppuntnet/assets/6596480/6caf1749-4b36-4a57-a23d-75f524ced536)

Examples from the [osm wiki tag page](https://wiki.openstreetmap.org/wiki/Key:osmc:symbol):

> ![symbol-wiki-examples](https://github.com/vmarc/knooppuntnet/assets/6596480/785bbb5f-7d59-424c-9957-d3fb8ed99bbf)

**Comment by vmarc** [comment]
Solution published in release v4.1.0.
