### ISSUE TITLE
Display relations and facts counts in Analysis explored by location

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#320]
For each location, the number displayed currently is the node count.
Example for [France](https://knooppuntnet.nl/en/analysis/hiking/fr).

Like [Analysis explored by network](https://knooppuntnet.nl/en/analysis/hiking/fr/networks), KPN could display distance, nodes, routes and facts.

Lyon Saint Exupéry en Dauphiné 97% 😃
63 km, 27 nodes, 33 routes

PS:
- Analysis explored by network don't display yet facts
- Left panel could filter networks in the future :
  - with fact
  - without routes
  - …

**Comment by vmarc** [comment]
Route and fact counts added in v4.3.50.
