### ISSUE TITLE
Request: fixme=incomplete routes without errors should be flagged

### ISSUE THREAD

**Issue by A67-A67** [vmarc/knooppuntnet#33]
When a route is not finished yet, the tag fixme=incomplete can be used to marked the route as incomplete. This is a good way to separate those intentionally incomplete routes from the actual, incidental errors that should be solved.

However, sometimes people complete routes without removing this tag. The only way to check this, is to manually check all 842 pages of incomplete routes. I have done this a few times and it is a very tedious job. 

My request is that complete routes (without errors, except sorting and wrong-note errors) that are marked as incomplete will result in an error. This would make this check a lot easier.

**Comment by vmarc** [comment]
@A67-A67 Thanks for this idea.

The idea is implemented in v2.0.12 in [IncompleteOkRouteAnalyzer](https://github.com/vmarc/knooppuntnet/blob/develop/production/core/src/main/scala/kpn/core/engine/analysis/route/analyzers/IncompleteOkRouteAnalyzer.scala). The logic in this analyzer assumes that the route is OK if there are no facts with fact level _ERROR_ (this allows for a bit more than sorting and wrong-note errors). An overview of the levels assigned to the various facts can be found in [Fact](https://github.com/vmarc/knooppuntnet/blob/develop/production/shared/src/main/scala/kpn/shared/Fact.scala).
