### ISSUE TITLE
Switch to OAuth 2

### ISSUE THREAD

**Issue by danieldegroot2** [vmarc/knooppuntnet#333]
Switch to OAuth 2 from HTTP Basic Auth and OAuth 1.0a. They are being deprecated.
See https://github.com/openstreetmap/operations/issues/867

**Comment by vmarc** [comment]
Switched to OAuth2 in version 4.2.13.

This was not easy and did take a lot of time and effort (as you can tell from the commit log).

More details about how the authentication works in the [documentation](https://github.com/vmarc/knooppuntnet/blob/develop/docs/authentication.md).
