### ISSUE TITLE
Simplify column segments in Details page

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#343]
<img width="124" alt="Segments column" src="https://github.com/vmarc/knooppuntnet/assets/2158081/1c4f8956-5e46-44e9-ba62-167c913365c4">

The first column could be removed and when there is more than one segment, the number of segment could be drawn on the canvas.
<img width="125" alt="Capture d’écran 2023-11-05 à 16 11 54" src="https://github.com/vmarc/knooppuntnet/assets/2158081/e326c894-715b-4cbb-9600-491631b7a108">

**Comment by vmarc** [comment]
The number of segments drawn on the canvas:

> ![segments](https://github.com/vmarc/knooppuntnet/assets/6596480/ffa5cf3f-b359-4e4c-a909-8ced9fe320f6)

**Comment by vmarc** [comment]
Implemented in release v4.2.2.
