### ISSUE TITLE
Tabs are hidden when labels are too long

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#346]
[Example](https://knooppuntnet.nl/fr/monitor/groups/eu-iwn-E-paths/routes/E7/map?sub-relation-id=2911986&mode=comparison&reference=false&matches=true&deviations=true&osm-relation=true&position=42.58906133,1.86331745,12)
<img width="50%" alt="Normal view" src="https://github.com/vmarc/knooppuntnet/assets/2158081/5bd5ac96-b42b-49a0-b7a3-a80467cd8c21">
<img width="50%" alt="Zoomed view" src="https://github.com/vmarc/knooppuntnet/assets/2158081/e295f38f-b373-498c-b17e-a83db8e4fc2f">

**Comment by vmarc** [comment]
The code has been changed to show ellipsis in the page header and breadcrumb when the text is too long to fit the page width.

When hoovering over the route name, the complete text is shown.

> ![ellipsis](https://github.com/vmarc/knooppuntnet/assets/6596480/faf6aee5-4a0c-435e-9cef-301ce19df5b1)

**Comment by vmarc** [comment]
Implemented in release v4.2.2.
