### ISSUE TITLE
Consistency issue in Monitor

### ISSUE THREAD

**Issue by StC-OSM** [vmarc/knooppuntnet#349]
At https://knooppuntnet.nl/fr/monitor/groups/fr-iwn-Camino, Vendée-Tours appears with 2 segments. When one clicks on https://knooppuntnet.nl/fr/monitor/groups/fr-iwn-Camino/routes/Vend%C3%A9e-Tours, it appears as perfectly continuous.

<img width="1144" alt="Capture d’écran 2023-11-16 à 18 59 32" src="https://github.com/vmarc/knooppuntnet/assets/100076956/899e975d-a71e-4b1f-afd2-4b4e46a88204">
<img width="1115" alt="Capture d’écran 2023-11-16 à 19 02 51" src="https://github.com/vmarc/knooppuntnet/assets/100076956/d4b77084-7ba4-46cb-90e7-4e1ea00157ff">

**Comment by vmarc** [comment]
See also: #351.

**Comment by vmarc** [comment]
Resolved, see: https://github.com/vmarc/knooppuntnet/issues/351#issuecomment-1958992092
