### ISSUE TITLE
Unusual way of presenting data in Monitor

### ISSUE THREAD

**Issue by StC-OSM** [vmarc/knooppuntnet#352]
Information at https://knooppuntnet.nl/fr/monitor/groups/fr-nwn/routes/GR%203 is presented differently from other similar routes, on the first line of the table.

<img width="1127" alt="Capture d’écran 2023-11-17 à 17 18 56" src="https://github.com/vmarc/knooppuntnet/assets/100076956/7d81a459-0077-4cc9-bc8a-888d5c38b26a">

<img width="1084" alt="Capture d’écran 2023-11-17 à 17 20 31" src="https://github.com/vmarc/knooppuntnet/assets/100076956/2b120d79-225c-438f-a9bf-43a9d7270faf">

**Comment by vmarc** [comment]
In the distance column, the meaning of the number of km is shown when hoovering over the value:
- Numbers in bold font: "Total length of ways in all subrelations".
- Number is normal font: "Total length of ways in this relation".

When two numbers are shown, this would mean that the relation has both relation members and way members.

Your example route looks different on my laptop (only a bold number):

> ![GR3](https://github.com/vmarc/knooppuntnet/assets/6596480/c154c8fa-bda3-4f63-8278-81869f224e47)

When you look at the main relation of route [Voie-Lyon](https://knooppuntnet.nl/fr/monitor/groups/fr-iwn-Camino/routes/Voie-Lyon) you will find both relation and way members:

> ![Voie-Lyon](https://github.com/vmarc/knooppuntnet/assets/6596480/f35c5367-a0c8-4077-8b51-55f4acb44653)

**Comment by StC-OSM** [comment]
actually these are not the difference I had in mind. I thought about the 'map' link that is there or not, the number of segments, etc

**Comment by vmarc** [comment]
The map link and the number of segments are not shown for relations that do not contain any ways. This is as intented at this moment.

After implementation of #369 the map link will be added for relations without ways also.
