### ISSUE TITLE
Link to overview page in navigation panel on the left

### ISSUE THREAD

**Issue by A67-A67** [vmarc/knooppuntnet#36]
At this moment you need a few clicks to get from a certain page to [the overview page](https://knooppuntnet.nl/nl/overview), while this is one of the most important pages on the website (and the homepage of the old vmarc-site)

I suggest a link in the left navigation panel (where 'Introduction', 'Glossary' and 'Links' are) to the overview page.

**Comment by vmarc** [comment]
@A67-A67 Thanks for this useful suggestion.

Added the new link in v2.0.13.

Some more background information:

The work has started to build a route planner for [knooppuntnet.nl](https://knooppuntnet.nl/) and [knooppuntnet.be](https://knooppuntnet.be/) that is based on the node network data in OpenStreetMap. This route planner will allow to plan a trip by selecting networknodes on a map, and the planner will produce a route description and/or gps trace for the trip.

The idea is that this route planner will take a very prominent place on the web-site. The home page would either contain some introductary text with a link to this route planner, or perhaps the home page would immediately be the route planner itself. 

The hope is that this route planner can make the node network data in OpenStreetMap more useful for a broader audience, and perhaps attract additional mappers to add to and maintain this data.

The quality assurance aspect of the site will off course be kept and will be further developed. From a user interface navigation point of view however, the analysis (or at least the starting points for the analysis), would shift a bit more to the background.

Moving the overview away from the home page was one of the first steps in this development.

Adding the extra link to get back to that page more quickly was a good idea. Thanks.
