### ISSUE TITLE
[Monitor] Error after re-analysis when switching from OSM-reference to multi-gpx reference

### ISSUE THREAD

**Issue by pelderson** [vmarc/knooppuntnet#360]
![image](https://github.com/vmarc/knooppuntnet/assets/38458314/70abf0e6-5810-4bbd-a2d3-d79cd8339ba3)

I got this error for seveal different routes, so I suspect it's a bug.

**Comment by vmarc** [comment]
@pelderson thanks for reporting this issue

The server logic has been updated to make switching from 'osm' to 'multi-gpx' reference possible.
