### ISSUE TITLE
[Monitor user documentation] The user manual on the wiki should get a Monitor tab.

### ISSUE THREAD

**Issue by pelderson** [vmarc/knooppuntnet#362]
The user manual on the wiki should get a Monitor tab. I am prepared to write stuff while I am piloting the Monitor. I'm sorry to say that I simply don't know how to create a new tab on that page!
Could someone assist me by creating a tab, so I can use my limited wiki skills to add text?
No pressure, of course!

**Comment by vmarc** [comment]
@pelderson During the past couple of days I have made a start with writing text for a monitor tab in the wiki.  Perhaps give me a couple of days to finalize this initial text, so that you can start with your corrections and further additions from that?

**Comment by vmarc** [comment]
A [monitor tab](https://wiki.openstreetmap.org/wiki/Knooppuntnet_monitor) has been added in the OpenStreetMap wiki.
