### ISSUE TITLE
Display last monitoring date before the deviations or segments list

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#364]
If there is a lot of deviations or OSM segments, the Latest analysis timestamp is hidden.

Deviations list:
<img width="50%" alt="Deviations list" src="https://github.com/vmarc/knooppuntnet/assets/2158081/96c72449-dd0a-4280-99c8-166bd35b21ea">

OSM segments list:
<img width="50%" alt="OSM segments list" src="https://github.com/vmarc/knooppuntnet/assets/2158081/4bf9dcdc-c0e2-4a54-810c-6e4593fddf00">

Related to #309.

**Comment by vmarc** [comment]
The latest analysis timestamp has been moved to the top of the monitor map page.

![latest-analysis-timestamp](https://github.com/vmarc/knooppuntnet/assets/6596480/36a16525-60b6-482f-889d-f04bf5b3e2f0)
