### ISSUE TITLE
Map zoomed out when navigating back

### ISSUE THREAD

**Issue by Polfo** [vmarc/knooppuntnet#37]
This is a repeat of #11 (discovered after editing this issue)

After opening a [map](https://www.knooppuntnet.be/nl/map/rwn), then carefully zooming in to a location, then clicking on a route/node and choosing _more details_, a [route](https://www.knooppuntnet.be/en/route/3046861) / [node](https://www.knooppuntnet.be/en/node/2994515656) details screen is shown.
Fact: Navigating back in the browser returns to the map in **zoomed out** view
Opinion: I would really prefer to keep the previous zoomed in location, where I left the map.
Fact: There is a workaround: holding Ctrl down while clicking "more details" to open the details in another tab and keep the  #map.
Fact: Using the _MAP_ navigation on top, next to the language navigation, brings us to a map, but nodes and routes are not clickable on that map. So that map cannot be used as workaround.

Map with clickable routes/nodes:
![image](https://user-images.githubusercontent.com/10303392/49330343-61837880-f58d-11e8-875a-e22f9be5c749.png)

When returning to map:
![image](https://user-images.githubusercontent.com/10303392/49330356-9f809c80-f58d-11e8-905d-cd1283a4821a.png)

This map does not have clickable routes/nodes:
![image](https://user-images.githubusercontent.com/10303392/49330288-bc68a000-f58c-11e8-9000-97fa350f6b5e.png)

**Comment by vmarc** [comment]
@Polfo thanks for bringing this back on the radar, and describing the issue much more clearly than in #11. I will close the old issue and keep this one for further followup.

**Comment by vmarc** [comment]
Implemented in planner map in release v3.0.0.

The latest map position and zoomlevel are also stored in the browser localstorage, so that after closing and re-opening the browser, the map returns to the latest position and zoomlevel.
