### ISSUE TITLE
Wrong relation openned in JOSM

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#373]
From [eu-icn-EV/EV1](https://knooppuntnet.nl/fr/monitor/groups/eu-icn-EV/routes/EV1/map?sub-relation-id=4840316&mode=osm-segments&reference=false&matches=true&deviations=true&osm-relation=true&position=45.88709245,-1.04559325,9), JOSM > Load route relation open relations=[2763798](http://localhost:8111/import?url=https://api.openstreetmap.org/api/0.6/relations?relations=2763798) instead of relation=[4840316](http://localhost:8111/import?url=https://api.openstreetmap.org/api/0.6/relations?relations=4840316).

**Comment by pyrog** [comment]
In fact KPN try to open the root relation in JOSM.
The result was strange because few ways were member of this relation.

Seem more obvious to load the current relation.
(Parents relations could be loaded too ?)

**Comment by vmarc** [comment]
Implemented in frontend release 4.2.4.

The "josm > Load route relation" popup menu option in the monitor route map page now loads the relation of the sub-relation that is shown on the map (or main relation if there are no sub-relations).

The super relation can still be loaded from the edit button in the "Details" tab.

In a future redesign of the monitor pages (#356), it should be easier to select what is shown on the map (child relation, or parent relation), and to select what is loaded in JOSM.
