### ISSUE TITLE
JOSM link for missing nodes not working

### ISSUE THREAD

**Issue by StC-OSM** [vmarc/knooppuntnet#374]
Whereas the other JOSM links in the following picture work properly, clicking the JOSM link for missing nodes does not produce any effect.

<img width="1198" alt="Capture d’écran 2024-02-23 à 21 26 13" src="https://github.com/vmarc/knooppuntnet/assets/100076956/56944227-3f71-491f-b344-1c85d983e7b7">

**Comment by vmarc** [comment]
@StC-OSM thanks for reporting this problem, fixed in release v4.3.6.

**Comment by StC-OSM** [comment]
It works, thx! Nevertheless, it would be even better if the network relation was added to the list of objects loaded in JOSM. Otherwise it requires additional steps before starting the work itself (come back from JOSM, find the relation ID from the page URL, go back to JOSM, load the relation)

**Comment by vmarc** [comment]
Created issue #375 for further followup.
