### ISSUE TITLE
Separate page per type of fact

### ISSUE THREAD

**Issue by vmarc** [vmarc/knooppuntnet#378]
Example for facts of a given network:
https://knooppuntnet.nl/en/analysis/network/13829868/facts/RouteInaccessible

Example for facts of a given location:
https://knooppuntnet.nl/en/analysis/hiking/fr/France/facts/RouteNotContinious

**Comment by pyrog** [comment]
It could be a separate page or the same page with anchors to each facts.

I.e. https://knooppuntnet.nl/en/analysis/network/13829868/facts#RouteInaccessible

**Comment by vmarc** [comment]
Implemented in release v4.3.23.

The fact name in the url after the hash character causes the page to focus on the section with that fact.

Examples:

https://knooppuntnet.nl/fr/analysis/hiking/fr/France/facts#RouteNameMissing

https://knooppuntnet.nl/fr/analysis/network/13948824/facts#NodeMemberMissing
