### ISSUE TITLE
Display all routes in Analyser maps

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#385]
Routes with some facts aren't displayed in [node](https://knooppuntnet.nl/en/analysis/node/9281655824/map?position=45.43386186,6.33413890,18), [network](https://knooppuntnet.nl/fr/analysis/network/13511365/map?position=45.43386186,6.33413890,18) or [location](https://knooppuntnet.nl/en/analysis/hiking/fr/France:Savoy:Communauté%20de%20communes%20Porte%20de%20Maurienne/map?position=45.43386186,6.33413890,18) maps, but displayed in [route](https://knooppuntnet.nl/en/analysis/route/17147794/map?position=45.43386186,6.33413890,18) map.

Example: [Col Montjoie - Col Montjoie](https://knooppuntnet.nl/en/analysis/route/17147794) have the following facts:
- RouteUnusedSegments
- RouteInaccessible

<img width="33%" title="route view" src="https://github.com/vmarc/knooppuntnet/assets/2158081/e23910da-732d-41af-aac9-a544ce4a842a" > <img width="33%" title="network view" src="https://github.com/vmarc/knooppuntnet/assets/2158081/d68dea0a-29fc-430e-b211-3ecffae2b4db" >

**Comment by vmarc** [comment]
Routes with unused segments are now also displayed in the maps (release 4.3.63).

Node map:

<img width="527" alt="image" src="https://github.com/vmarc/knooppuntnet/assets/6596480/fe6e94a1-3982-471a-ab30-be2be5a6cec8">

---

Network map:

<img width="527" alt="image" src="https://github.com/vmarc/knooppuntnet/assets/6596480/b946566a-782c-42ca-b92a-18cf13248107">

---

Location map:

<img width="527" alt="image" src="https://github.com/vmarc/knooppuntnet/assets/6596480/a84db3a2-2da2-49d7-8497-bb400ab4b866">

---

Route map:

<img width="527" alt="image" src="https://github.com/vmarc/knooppuntnet/assets/6596480/c798b3f2-e47b-4a52-832e-ee67fa2e2815">
