### ISSUE TITLE
Handle coordinates in location map URL

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#386]
Add query parameter `?position=45.43386186,6.33413890,18`.

[Example](https://knooppuntnet.nl/en/analysis/hiking/fr/France:Savoy:Communauté%20de%20communes%20Porte%20de%20Maurienne/map?position=45.43386186,6.33413890,18):
<img width="33%" alt="Communauté de communes Porte de Maurienne zoomed on Col Montjoie " src="https://github.com/vmarc/knooppuntnet/assets/2158081/973be760-ec8c-4099-8cf1-22bf01737650">

See #275

**Comment by vmarc** [comment]
Implemented in release v4.3.19.
