### ISSUE TITLE
Handle map layers in URL

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#387]
Add parameters in URL to select layers.

<img width="239" alt="Map layers" src="https://github.com/vmarc/knooppuntnet/assets/2158081/87a923bc-6d1f-4486-aea2-b205cc71e3bd">

**Note:**
Parameter could handle futur layers:
- bitmap layers like satellite view, topographic map, IGN in France…
- vector styles
- customs bitmap tiles or vector styles
- overlays:
  - Waymarked Trails hiking tiles…
  - gpx tracks
  - kml
  - geojson
- …

Related to #386, #275

**Comment by vmarc** [comment]
Implemented in v4.3.38.

Changed for location, subset, network, node, route and monitor map pages.
