### ISSUE TITLE
Shortcut is OS dependent

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#398]
On macOS we must use `cmd + click` instead of `ctrl + click` to open the detail page in another browser tab.
Could you change the label _"Use ctrl-click to open the detail page in another browser tab."_ ?

<img width="306" alt="Screen copy" src="https://github.com/vmarc/knooppuntnet/assets/2158081/808cf07b-e4fe-4309-ae46-635b937641b1">

**Note:** `ctrl + click` is equivalent to the right click (used to open the contextual menu).

**Comment by vmarc** [comment]
Updated in v4.3.54.
