### ISSUE TITLE
Enable walking network and horse riding in Germany

### ISSUE THREAD

**Issue by dvdhoven** [vmarc/knooppuntnet#40]
There are several walking networks from the Netherlands that pass the German border.
Now these networks have problems with verification as the analysis said there are no walking networks in Germany.
Actually the networks of Twente and Vechtdal have already problems with the expected_rwn_route_relations tag. Several rwn_ref's are reported that they have a wrong number of routes but in fact they have the right number, but some routes are in Germany.
Also the network Bargerveen have problems
The  same problem will come in the very close future for horse riding networks.
The network of Twente will pass the German border and in the Grafschaft Bentheim there is a horse riding network already

Please enable walking networks and horse riding networks in Germany.

Thanks in advance

Regards,
Dick van den Hoven

**Comment by vmarc** [comment]
The code has been updated to add support for walking networks and horse riding networks in Germany.
