### ISSUE TITLE
[Analysis] Display connection routes more accurately 

### ISSUE THREAD

**Issue by StC-OSM** [vmarc/knooppuntnet#410]
On maps in the Analysis part of Knooppuntnet, when displaying network X:
 1- all the routes belonging to X only appear in green, and its network nodes appear in green with a blue icon
 2- all the routes and network nodes that do not belong to X appear in gray
 3- the connection nodes that belong to X appear in green with a green icon
 4- the connection routes that belong to X appear in green, and both their ends appear in green with a blue icon (including the end that does not belong to X at all). See for instance the image below, where the center node does not belong to the network currently displayed.
<img width="446" alt="Capture d’écran 2024-04-21 à 13 31 50" src="https://github.com/vmarc/knooppuntnet/assets/100076956/78b9b5c7-4cce-40b9-8423-3498e884b1e3">

Point 4 is problematic, because it shows a wrong information concerning the nodes and a misleading information concerning the route. It would be best if:
 - the end that does not belong to X is showed in gray
 - ideally, the route would come out as different from the other, e.g a dashes of green and gray

**Comment by vmarc** [comment]
The map contents and styling has been improved in v4.3.51.

> <img width="350" alt="legend" src="https://github.com/vmarc/knooppuntnet/assets/6596480/0ff761f0-0192-43b7-8592-978491ac625e">

![network-map](https://github.com/vmarc/knooppuntnet/assets/6596480/f2e51239-8370-449b-aeec-733041a1524b)
