### ISSUE TITLE
[Analysis] Display borders in network maps

### ISSUE THREAD

**Issue by StC-OSM** [vmarc/knooppuntnet#411]
Analysing errors in connection nodes and routes is difficult because it often relies on where the actual border between two operators is located. It would help a lot if the network map showed that border in addition to showing the network and its neighbours.

It is understood that finding what is the right border to display may pose a problem. Often, the name of the network or its operator will give a strong hint but not an immediate mapping. Maybe this could be solved by a table, or by using wikidata.

**Comment by vmarc** [comment]
With the changes to the map styling from issue #410 (which improves how connections to other networks are shown), I guess it is now easier to see the border between networks.  I am closing this issue because I do not see a way to unambiguously draw a border between networks of different operators.
