### ISSUE TITLE
Major change in a route not listed when impact filter is on

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#413]
https://knooppuntnet.nl/en/analysis/route/13139760/changes

The topology of the route changed, one node was replaced, and by side effect, the name change.

Impact off: last version v6 is listed.
<img width="607" alt="Capture d’écran 2024-04-23 à 10 10 05" src="https://github.com/vmarc/knooppuntnet/assets/2158081/4550b05d-00ed-4908-9b39-948ac767cc5e">

Impact on: only the v1 is listed, but v6 is filtered 😢 
<img width="606" alt="Capture d’écran 2024-04-23 à 10 11 01" src="https://github.com/vmarc/knooppuntnet/assets/2158081/2a018671-ab21-4b2d-b7c5-b3a0720bb1de">

**Comment by vmarc** [comment]
The analysis logic can set two flags for a change: 
- happy
- investigate

The _happy_ flag is intended to indicate that the mapping quality has improved (for example: issues have been resolved, new nodes were added, etc.).

The _investigate_ flag is intended to indicate that mapping quality may have become worse (for example: there are new facts, routes or nodes have been removed, etc.).

The _impact_ filter looks for changes where at least one of these flags is set.

A route name change does not result in either the _happy_ flag or the _investigate_ flag to be set. The route quality is ok before the change, and is still ok after the change.  So although a route name change may be experienced as a significant change, it is probably not really necessary to draw other mappers attention to it by setting the _happy_ or _investigate_ flag.

**Comment by pyrog** [comment]
In this case the geometry and topology got **significant change**: the beginning node was replaced by a completely different node (not an OSM node with the same name/ref near the previous node).

<img width="50%" alt="After" src="https://github.com/vmarc/knooppuntnet/assets/2158081/523db692-022b-46d3-900d-9c399d8191fe">
<img width="50%" alt="Capture d’écran 2024-06-13 à 12 29 56" src="https://github.com/vmarc/knooppuntnet/assets/2158081/06e7d477-3b71-4660-982a-c70e9b00a8c0">
