### ISSUE TITLE
Change color of nodes in the history

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#414]
In this [example](https://knooppuntnet.nl/en/analysis/route/13139760/changes?pageSize=25&pageIndex=0&impact=false) all pins are blue.
Like ways, could you use a "diff" color ?

🔵 no change
🟢 added
🟡 changed
🔴 deleted

<img width="592" alt="Capture d’écran 2024-04-23 à 10 28 06" src="https://github.com/vmarc/knooppuntnet/assets/2158081/677c82b6-5719-4a80-a825-83453a1c8b45">

**Comment by vmarc** [comment]
Implemented in v4.3.57.
