### ISSUE TITLE
Implement history for locations

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#415]
Currently [Changes](https://knooppuntnet.nl/en/analysis/hiking/fr/France:Savoy:Communauté%20de%20communes%20Cœur%20de%20Maurienne%20Arvan:Montricher-Albanne/changes) display "work-in-progress - not implemented yet".

Managing huge network is painful (lot of edition conflicts, orphaned nodes and routes issue, too big OSM relations…).
With this feature we could abandoned network management 😎 

For example [Vercors](https://knooppuntnet.nl/en/analysis/network/12409335) network have 2031 nodes and 2343 routes for 2 475 km (the real size is about 4 000 km).

**Comment by vmarc** [comment]
Implemented in release v4.3.29.
