### ISSUE TITLE
Help to find orphaned objects

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#416]
To help managers to add an object to a network I suggest the following features:
- Display the location in the lists
- Sort the lists also by location (see [#305](https://github.com/vmarc/knooppuntnet/issues/305))

Note: If we could have the same features for locations and for networks (especially the history see https://github.com/vmarc/knooppuntnet/issues/415) these features are less important.

**Comment by vmarc** [comment]
Support for locations has been improved, so I assume these features are less important now.
