### ISSUE TITLE
Manage other type of locations

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#417]
At least in France we have other type of boundaries that would be useful to managed in KPN.

Especially natural parks. They usually span across cities but could span across departments.

We currently managed Vercors as a node network relation but this is very painful.
Managing it has a Location would be fine (see https://github.com/vmarc/knooppuntnet/issues/415).

In order to do this, how KPN could know that a specific administrative boundary (i.e. natural park) will be managed?
We discuss off line several ways:
- Add all the natural parks ?
- "Hard code" a specific "administrative boundary" in KPN
- Add an had hoc tag to an "administrative boundary"
- Add an administrator menu to add, remove "administrative boundaries"

I suggest another and simplest way:
- Use a node network relation with one (or more) "administrative boundary" member.

In the example of the [Parc Naturel Régional du Vercors](https://knooppuntnet.nl/en/analysis/network/12409335) we will:
1. Remove all nodes and routes
1. Add the park administrative boundary
or 
Add only some cities boundaries (members of the park)

**Comment by pelderson** [comment]
I endorse this, as a (for me) non-urgent enhancement request. Nederland, too, has natural areas spanning multiple provinces/municipalities/networks. When managing such an area using an administrative boundary, you have sections that you don't want or sections that you miss because they are outside the area, or both.

**Comment by StC-OSM** [comment]
Same here in France. PNR Vercors manages all network routes and nodes inside its boundaries except those that are inside the boundaries of Grenoble-Alpes Métropole. All other adjacent groups of municipalities manage all routes inside their boundaries except those that are inside the boundaries of PNR Vercors.

**Comment by StC-OSM** [comment]
@pyrog encourages me to explain here the solution I have proposed for non-trivial relations between boundaries and networks, as exemplified above. It consists in elaborating on his proposal to add boundaries as members of networks (possibly replacing the list of routes and nodes) and defining "in" and "out" roles for boundaries, thus creating a boolean algebra. 

For the example above, we would have the boundary of PNR Vercors in the relation with role "in" and the boundary of Grenoble-Alpes Métropole with role "out". And, of course, we could remove all routes and nodes from the relation. At least, except for those outliers that need to be added or removed one by one following the same in/out logic.

**Comment by vmarc** [comment]
The location based data currently in the knooppuntnet database is all precalculated based on the boundaries as presented in the country location selection pages (click "Explore by location", "Select from tree", "Expand all" and "All").  These locations should cover the entire country, with a clear hierarchy and without overlaps at the same level.

- [France](https://knooppuntnet.nl/en/analysis/hiking/fr)

- [The Netherlands](https://knooppuntnet.nl/en/analysis/hiking/nl)

Queries in terms of these locations (include locations A and B and C, but exclude locations D, E and F) could be made very fast with the data as-is in the database today.  If that is enough, that would be doable to support in the knooppuntnet logic.

I expect that on-the-fly queries based on arbitrary boundaries are never going to be that fast, but I would like to try to prove or disprove this expectation.

Can you provide some examples of what would be useful to you, with each time:

- name that you would give to the area
- the OSM ids of boundary relations that are to be included
- the OSM ids of boundary relations that are to be excluded
- the OSM ids of route relations that are to be included but do not fit the boundaries above
- the OSM ids of route relations that are to be excluded but do not fit  the boundaries above
- the OSM ids of nodes that are to be included but do not fit the boundaries above
- the OSM ids of nodes that are to be excluded but do not fit the boundaries above

**Comment by StC-OSM** [comment]
Sticking to my example of Parc Naturel Régional du Vercors (in short, PNR Vercors), there are two ways to define it:
 - either through its own boundary: https://www.openstreetmap.org/relation/5555268
 - or through a list of 83 municipalities that adhere to it
I'll prefer the first option of course.

When looking for routes and nodes, we need to:
 - include everything in https://www.openstreetmap.org/relation/5555268
 - exclude everything in https://www.openstreetmap.org/relation/2102885
 
As for outliers in nodes and routes, I need some more time to find examples. I recall for instance some routes (and even nodes) that "invade" the territory of other operators but that are obviously not connect to any network related to those other operators. This occurs mostly in mountains, where an area is more easily accessed from outside the boundary.

What we do currently is list all nodes and routes by hand. What would be good it to just say "relation 5555268 is in", "relation 2102885 is out", "this outlier node is in", "that outlier node is out". The network relation would go from ~8000 members down to ~20 members, with the same level of accuracy.

**Comment by vmarc** [comment]
I have been investigating the possibilities for reporting using on-the-fly queries based on arbitrary boundaries.  The geospatial query operators in the MongoDB aggregations were used to collect the data.

The result is that node lists or node counts can be produced very fast (after changing the document model to allow the use of the special geospatial query operators).

Route list or route count queries remain too time consuming, even after changing the route document model, and adding indexes to speed up processing.  The best I could get for the "Parc Naturel Régional du Vercors" area was 22 seconds just to retrieve a route count.  The queries quickly become quite complex.

Producing queries for lists of changes for the area will be even more complex and the expectation is that this will be way too time-consuming.

My conclusion at this moment is that a system where knooppuntnet interprets arbitrary boundary references in network relations will not work.

--- 

What would be possible is that custom locations are defined in knooppuntnet  (with forms like used for monitor) and having all processing needed to determine wether a node or route is within those locations of not is done beforehand (at the time of defining the custom location the processing is done for all nodes and routes in the database, and afterwards a re-evaluation is done upon any change that arrives for the node or route).

The queries for these custom locations would be identical (also in performance) to the queries for the locations we have today.

---

Queries based on combinations of existing locations (the list of 83 municipalities) would also work.

---

Another possible idea would be that knooppuntnet would support "operator based analysis": all nodes and routes would get a tag like _"operator=Parc naturel régional du Vercors"_, and node lists, route lists and changes are made based on that.  No network or boundary relation interpretation needed.

**Comment by vmarc** [comment]
[Parc du Vercors](https://knooppuntnet.nl/fr/analysis/hiking/fr/Parc%20du%20Vercors/nodes) has been added as special custom location in release v4.3.32.  The definition is based on the 83 communes that are listed in [Le Parc naturel régional du Vercors de quoi s'agit il?](https://www.parc-du-vercors.fr/le-perimetre-et-les-chiffres-cles).

If the need arrises, more such _"custom locations"_ (that are collections of other locations) can be added in the future.  If there is a need for many such  _"custom locations"_ a new user interface could be made to define these.
