### ISSUE TITLE
Nodes have also an elevation

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#418]
In France in moutains, we could have several node with the same name but with different elevations.

In practice operator don't manage "nodes" but they manage guideposts.
So we have several guidepost with the same tag `name` and different tag `ele`.
Currently we must handle this manually and this is error prone (merge `name` and `ele` value of the guidepost, add a separator)

Could you manage also the tag ele for nodes and use it automatically in the label of the node?

See [KISS: keep it simple](https://wiki.openstreetmap.org/wiki/Talk:Node_Networks#KISS:_keep_it_simple) discussion in the wiki.

**Comment by pyrog** [comment]
Work also for saddles 😄 

- [Col de Chausseyras](https://knooppuntnet.nl/en/analysis/node/9558783785) • 1 563 m

**Comment by pyrog** [comment]
Some examples in France (probably in other countries).

OSM id | Name
-- | -- 
[281766176](https://knooppuntnet.nl/en/analysis/node/281766176) | Le Monolithe (1620 m)
[858528077](https://knooppuntnet.nl/en/analysis/node/858528077)  | Gare TGR 2700
955945080  | Les Bigeards - 1050
955949438  | Les Bigeards - 1060
1193834793  | Les Chosalets 1150 m
1229520194  | Les Essarts (338 m)
1232850005  | Chanaz - La Passerelle - 230 m
1232850017  | Chanaz - La Passerelle - 235 m
1321849939  | Avrieux (1247 m)
1321850006  | Avrieux (1248 m)
1371831052  | Pierre-Percée 1205
1491244004  | Au Dessus De Joiys - 650m
1491271554  | Dolmen De L'Antillière - 760
1491276195  | Col Des Mille Martyrs - 874 m
1491276223  | Col du Pilori - 883 m
1688843043  | Saint-Alban-des-Villards - 1110 m
1714988342  | Les Bigeards - 1050
1906826530  | Point 1321
2051364455  | Ontex - 723 m
2051364459 |  Ontex - 720 m
2186779942  | Le Grand Vivier - 735 m
2186780056  | Chatvillard - 735 m
2402425818  | Bois De Piantimey - 665m
2445986100  | Le Rocharey - 690 m
2445986118  | Croix de Tempêtat - 740m
2450253032  | Les Balmettes - 564m
2450253059 |  Étang Des Chartreux - 830 m
2661597181  | Ture - 507 m
2801930590  | N. D. de la Salette (792 m)
2824025020  | Sous La Ferme Michalet - 810m
3039717334  | Mollard Gris (910 m)
3039717339  | Mollard Gris (892 m)
3740213925  | Sentier du Signal - 820 m
3773216027  | Les Vincendières - 1860 m
3791987926  | Sentier du Signal - 840 m
3833537745  | Plateforme - 668 m
4359244757  | Avrieux (1209 m)
5464698041  | Circuit du Château 550 m
5832994673  | Glaise 775 m
5832994676  | Glaise 780 m
5854617184  | Les Mouilles (1525 m)
7619758638 |  Circuit du Château 600 m
8125146428  | La Grenonière Alt 1292m
8740443615 |  Plateforme - 667 m
9313276750  | La Chapelle (1049 m)
9313316485  | Pierre Plate (1330 m)
-- | -- 
7214539444  | Alt. 1842 m
10944185084  | Altitude 808
3988992313  | Altitude 840
245799262  | Altitude 1455
278234558  | Altitude 1640
278413830  | Altitude 1800
1289581188  | alt 2000 m
-- | -- 
9167779023  | Cote 392
9546098576  | Côte 2000
3916246129  | La Cote 457 mètres
1349136019  | La Cote 1545 mètres
1256811922  | La Cote 1304 mètres
4331154364  | La Cote 999 mètres
82713918  | La Cote 689 mètres
2356986548  | La Cote 689 mètres
3667117272  | La Cote 240 mètres
3830539466  | La Cote 1208 mètres
5085387498  | La Cote 802 mètres
11833641797  | La Cote 1257 mètres
1024885318  | Les Côtes 1487

Extract of this [overpass query](https://overpass-turbo.eu/?q=LyoKVGhpcyBoYcSGYmVlbiBnxI1lcmF0ZWQgYnkgdGhlIG92xJJwxIlzLXR1cmJvIHdpemFyZC7EgsSdxJ9yaWdpbmFsIHNlxLBjaMSsxIk6CsOiwoDCnCJuZXR3b3JrOnR5cGUiPW5vZGVfxYzFjsWQayBhbsSXbHduxZ5hbWU9Il4uKiBbMC05XSsgbSQiIMS6IEbEk25jZcWIwp0KKi8KW291dDpjc3YoOjppZCwgxafFqcS7xawpXVt0acWsxo3GjzI1MDBdOwp7e8SQb2PFm2VBcsWAOsaBxaTGhH19LT4uxL_FgWjGtcWAxqwKxZrFnFvFi8WNxY_FkcWTxZXFl8Wux4jFncWfx41rIsagIsabxarFrCJ-IsW0xbbFuMeYKMSwxYDHgMWAcsWCx4RhKceGxqXEj2VvbTs&c=BLp3vnuOdH&R=)

**Comment by pyrog** [comment]
[Le Monolithe](https://knooppuntnet.nl/en/analysis/node/281766176/map?position=45.24751878,6.76854494,20)
<img width="522" alt="Le Monolith" src="https://github.com/vmarc/knooppuntnet/assets/2158081/3315cea6-6e7f-4311-91f6-f01698211efe">

**Comment by pelderson** [comment]
May I offer my thoughts? Adjacent nodes can have identical names, that is no problem for integrity, routing and maintenance. Node labels are useful for users, on the planner display and planner output. If we want to show the difference based on elevation, it would be enough to append the ele value (if present) to the name for display and planner output.

**Comment by pyrog** [comment]
Does two or more adjacent nodes with the same name but with different elevation are the "same" node ?
Is it only a display "issue" ?

Should be checked, but in point of view of french operators it seem different nodes.

**Comment by vmarc** [comment]
Start- and endnode can have the same name ([example](https://knooppuntnet.nl/en/analysis/route/12653293)).  If on the ground, on the guideposts, the nodes are distinguished from each other by the elevation, then that should be reflected in the node name I think.
