### ISSUE TITLE
Map layer menu isn't visible in full screen

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#419]
Tested with Safari and Chrome.

[Example](https://knooppuntnet.nl/en/analysis/node/858528077/map?position=45.11734887,6.10571358,16)

Menu is displayed
<img width="272" alt="layer menu is visible" src="https://github.com/vmarc/knooppuntnet/assets/2158081/2909a97f-d27e-4489-ab30-4cab81fb49d7">

Full screen: menu is hidden
<img width="244" alt="layer menu is hidden in full screen" src="https://github.com/vmarc/knooppuntnet/assets/2158081/2bc2f633-3261-43c1-a869-6a5650756bab">

**Comment by vmarc** [comment]
Fixed in v4.3.56.
