### ISSUE TITLE
Strange unused segments

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#420]
[Route ? - Les Marmottons](https://knooppuntnet.nl/en/analysis/route/17574316) have the following facts:
- RouteRedundantNodes
- RouteUnusedSegments

Logically the route should be named "?  — La Salamandre" and the section "La Salamandre — Les Marmottons — Le Balcon de Villard" should be in red ?

<img width="407" alt="Nodes" src="https://github.com/vmarc/knooppuntnet/assets/2158081/a45a7b0b-a5ca-47d9-8ff9-0198e7228fb7"><br>

<img width="274" alt="Map" src="https://github.com/vmarc/knooppuntnet/assets/2158081/b0d18902-d29f-4eb4-b790-9d4757b7b38c">

**Comment by pyrog** [comment]
Possible explanation is that **Les Marmottons** is between segment 1 and 2, and **La Salamandre** is in the middle of segment 1.

<img width="298" alt="Capture d’écran 2024-05-08 à 22 30 25" src="https://github.com/vmarc/knooppuntnet/assets/2158081/4dde3c1c-6e1f-4ae0-9442-238412410982">

**Comment by vmarc** [comment]
Following logic is currently used to determine the route name: ast he route tags do not contain a route name, the knooppuntnet logic tries to derive the route name from the node-network nodes found in the ways in the relation. When there are more than two such nodes, the algorithm sorts them by name, and picks the last one in the list.  This is why node "Les Marmottons" was chosen as end-node.

The network nodes sorted by name:
-  "?"
-  "La Salamandre"
-  "Le Balcon de Villard"
-  "Les Marmottons"

Sorting by node name and picking the last one is indeed a bit a strange thing to do.  Nevertheless, for now, I will leave this logic as is.  The idea is that some time in the future, the analysis of node-network routes will be changed to be more in line with the monitor route analysis.  When that is done, the order of the nodes in the route ways would be respected and "Le Balcon de Villard" would be selected as the route end node.

I think it does not matter too much to leave this "strange" logic in for now.  The main thing is that fact RouteRedundantNodes is reported, and that the route is split in multiple routes that match the actual situation on the ground (as has been done in the mean while).
