### ISSUE TITLE
Locations don't display the same facts than networks for the same area

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#426]
Example:
Name | Type | Facts
--|--|--
[Grenoble-Alpes Métropole](https://knooppuntnet.nl/en/analysis/hiking/fr/France:Isère:Grenoble-Alpes%20Métropole/facts)|location|3
[Grenoble-Alpes](https://knooppuntnet.nl/fr/analysis/network/13436769/facts)|network|69

At least, **IntegrityCheckFailed** are missing from the location.

**Comment by pyrog** [comment]
Name | Type | Facts
--|--|--
[Grand Chambéry](https://knooppuntnet.nl/fr/analysis/hiking/fr/France:Savoie:Grand%20Chambéry/facts)|location|25
[Grand Chambéry](https://knooppuntnet.nl/fr/analysis/network/13948824/facts#RouteUnusedSegments)|network|64

Location display only in this example **RouteUnusedSegments**.

<img width="33%" alt="Network" valign="top" src="https://github.com/vmarc/knooppuntnet/assets/2158081/d18edd49-1e55-4b33-8b7a-15f2fcc23361"> <img width="33%" alt="Location" valign="top"  src="https://github.com/vmarc/knooppuntnet/assets/2158081/7b229b13-e478-46b8-b013-b01ab6c3fac3">

**Comment by vmarc** [comment]
The IntegrityCheckFailed count and fact details are added to the locations pages.

I think the remaining differences can be explained:
- nodes/routes in the location that are not included in the network
- nodes/routes in the network that are not within the location
- network specific facts that are not included in the location pages
