### ISSUE TITLE
Not very useful overview map of networks

### ISSUE THREAD

**Issue by MaartenDeen** [vmarc/knooppuntnet#43]
When you take a network map, from https://knooppuntnet.nl/en/networks/nl/rwn or https://knooppuntnet.nl/en/networks/nl/rcn and then use the map icon on top, you get a map with blue markers.
What do these markers do? You can not click them, they only give some very vague idea where a network is.
IMHO it would be a good addition to show some kind of popup with the network name and maybe the status when you hover over a marker and go to the network page when you click on it.

**Comment by vmarc** [comment]
In the original version of this map, the shape of the network was shown (calculated from the nodes and routes in the network). This made is easy to see the area that was covered by each of the networks, the relative network sizes, and also where networks overlap. It also made it possible to see which network a given orphan node or route probably belonged to.

This functionality was disabled when the underlying library that was used for this calculation was swapped out (not compatible with other library). In the future, I would like to bring back this functionality.

For now, when clicking a marker, a dialog will appear that shows the network name, total length, number of nodes and routes, with a link to go to the network detail page.
