### ISSUE TITLE
Batch addition of routes to Monitor

### ISSUE THREAD

**Issue by StC-OSM** [vmarc/knooppuntnet#430]
Over a few months, the fr-nwn group has reached 100 routes to monitor. I have produced an overpass query to find how many are missing from the group, and after some cleanup in the OSM database, the number has stabilized to 120 additional routes that need  monitoring.

Would it be possible to have a feature allowing to add a batch of routes, e.g. from a CSV or a json file?

**Comment by vmarc** [comment]
@StC-OSM if you post a CSV file here I will try to add the routes directly to the database

**Comment by StC-OSM** [comment]
Here is the CSV file of nwn routes in France. The "operator" column can be ignored, it is ongoing work to try and sort out who is in charge of exactly what on these routes (which might ultimately lead to removing some of them from OSM)

[fr-nwn.csv](https://github.com/user-attachments/files/17900815/fr-nwn.csv)

**Comment by vmarc** [comment]
@StC-OSM routes are added

**Comment by StC-OSM** [comment]
Thx!
