### ISSUE TITLE
Incorrectly ignored relations in rwn Roermond

### ISSUE THREAD

**Issue by MaartenDeen** [vmarc/knooppuntnet#44]
Some nodes in [walking network Roermond](https://knooppuntnet.nl/en/network-facts/6012903) fail integrity check because some relations are incorrectly ignored. Some of these relations are partly in Germany (one node even is) but they should not be ignored.
[Relation 6013263](https://knooppuntnet.nl/en/route/6013263)
[Relation 6013182](https://knooppuntnet.nl/en/route/6013182)
[Relation 6013181](https://knooppuntnet.nl/en/route/6013181)
[Relation 6013263](https://knooppuntnet.nl/en/route/6013263)
[Relation 6013269](https://knooppuntnet.nl/en/route/6013269)
[Relation 6013268](https://knooppuntnet.nl/en/route/6013268)

**Comment by dvdhoven** [comment]
#40

**Comment by vmarc** [comment]
This problem did go away after adding support for walking networks in Germany.
