### ISSUE TITLE
Oneway route seen as broken twoway route

### ISSUE THREAD

**Issue by A67-A67** [vmarc/knooppuntnet#45]
The routes below have been mapped with the tag 'direction=backward', because only the backward direction can be used. Knooppuntnet recognizes this tag, but thinks it is an broken twoway route, that has been mapped incorrectly as oneway route. 

The route strip shows that Knooppuntnet thinks that the first way is a part of the forward route, instead of the backward route, although it is mapped correctly.

- [60-61](https://knooppuntnet.nl/en/route/7328339)
- [63-64](https://knooppuntnet.nl/en/route/9515132)

**Comment by vmarc** [comment]
@A67-A67 Thanks for reporting this problem.

Test case [Issue45_OneWayRoute](kpn.core.engine.analysis.caseStudies.Issue45_OneWayRoute) was created to reproduce this problem.

Problem was in line 92 and 93 in kpn.core.engine.analysis.route.analyzers.RouteStructureAnalyzer.scala

Analysis database was rebuild from scratch to correct the affected routes.
