### ISSUE TITLE
Please remove network with no name

### ISSUE THREAD

**Issue by dvdhoven** [vmarc/knooppuntnet#49]

**Comment by dvdhoven** [comment]
Yesterday a mapper created an rcn route in NL with type=network.
This is corrected, but there are several messages about this network that cannot be solved.
It seems that the network is saved somewhere.
See this:
https://knooppuntnet.nl/nl/network/9661491
https://knooppuntnet.nl/nl/NetworkExtraMemberWay/nl/rcn

Thanks in advance

Regards,
Dick van den Hoven

**Comment by dvdhoven** [comment]
I don't want to close this

**Comment by vmarc** [comment]
The network has been manually set to active=false in the database.

As a result, the network page still exists and the history of the network changes is preserved, but the network does not appear appear anymore in the overview page, network list or as network reference in the node and route pages. The page reporting NetworkExtraMemberWay for cycling in The Netherlands also no longer includes the facts for this network.

This does not resolve the actual problem that the network deletion was not automatically detected by the analysis logic. That issue will be further handled in issue #51.
