### ISSUE TITLE
Deleted network Brabant doesn't disappear

### ISSUE THREAD

**Issue by A67-A67** [vmarc/knooppuntnet#50]
Someone made a [hiking network relation for Noord-Brabant](https://knooppuntnet.nl/nl/network/9663045), while those routes should be in network relations per municipality. I deleted the network, but it is still in Knooppuntnet including the errors.

**Comment by vmarc** [comment]
The network has been manually set to active=false in the database.

Where necessary the database views have been updated to properly exclude non-active networks, routes and nodes from reporting.

As a result, the network page still exists and the history of the network changes is preserved, but the network does not appear appear anymore in the overview page, network list or as network reference in the node and route pages.

This does not resolve the actual problem that the network deletion was not automatically detected by the analysis logic. That issue will be further handled in issue #51.
