### ISSUE TITLE
Automatically remove deleted networks

### ISSUE THREAD

**Issue by A67-A67** [vmarc/knooppuntnet#51]
I think at this moment deleted networks have to be removed manually. They doesn't seem to update after they are deleted and stay in the analysis including errors.

It may seem a rare case when a network is deleted, but it is often needed due to errors. Networks can be mapped from two sides, creating two networks. Network relations can be copied instead of edited, as the buttons are close together in JOSM. And networks can be made in the wrong way. At this moment the two newest issues are about deleted networks that have to be removed ([49](https://github.com/vmarc/knooppuntnet/issues/49) and [50](https://github.com/vmarc/knooppuntnet/issues/50)). 

It would be good when Knooppuntnet sees that a network is deleted from OSM, so it can remove the network automatically.

**Comment by vmarc** [comment]
Resolved in release v4.0.
