### ISSUE TITLE
Extra substrings to be ignored in network names for horse riding networks

### ISSUE THREAD

**Issue by A67-A67** [vmarc/knooppuntnet#55]
Belgium has to networks with prefixes in the name that are not ignored now. The values should be added to the [substrings to be ignored in network names](https://github.com/vmarc/knooppuntnet/blob/develop/production/core/src/main/scala/kpn/core/engine/analysis/NetworkNameAnalyzer.scala).

These are:

- [Ruiter- en mennetwerk](https://knooppuntnet.nl/nl/network/10030864)
- [Ruiter- en menroutenetwerk](https://knooppuntnet.nl/nl/network/4025258)

**Comment by vmarc** [comment]
@A67-A67 thanks for bringing this up

After looking through the other network names, I have also added:

- "Réseau Point-Nœud, "
- "Points-noeuds en "
- "Knotenpunktwegweisung "
