### ISSUE TITLE
NetwerkTypeNotTagged in overview 

### ISSUE THREAD

**Issue by A67-A67** [vmarc/knooppuntnet#56]
Thanks for adding support for the NetwerkTypeNotTagged, RouteNetwerkTypeNotTagged and NodeNetwerkTypeNotTagged errors. This makes it much easier to check the introduction of the tag network:type=node_network.

However the error is only shown in the facts pages of the networks. When it would be shown on the overview page it would be much easier to find the missing tags.

At this moment the Netherlands should be covered entirely and the coverage of Belgium is starting.

**Comment by vmarc** [comment]
@A67-A67 thanks suggesting this improvement

The new facts have been added to the overview page (release v2.0.18).  The counts in the overview are links that will bring you to new pages with fact details.
