### ISSUE TITLE
Some non-node_network routes still seen as node_network routes

### ISSUE THREAD

**Issue by pelderson** [vmarc/knooppuntnet#65]
Er zijn 23 "wandelroutewezen" in NL waarvan ik niet kan zien waarom ze in knooppuntnet als knooppuntroute gezien worden. Ik zie daar geen ondergesneeuwde fouten tussenstaan. Dat levert ook in de andere foutencategorieën een paar fouten op. Het is zeker niet zo dat alle rwn-etappes daar verschijnen. Ik denk dat de logika voor de selektie nog niet 100% is.

Ik heb een paar van de "nepwezen" bekeken. Ze lijken wel vaak bij een knooppunt te beginnen/eindigen, misschien is dat het?

**Comment by vmarc** [comment]
At the moment of this writing, the logic that takes the new tagging (_network:type=node_network_) into account has not been activated yet. Hopefully the analysis that uses the new tagging becomes active during the upcoming weekend. 

Let us have another look at the situation after this activation.

**Comment by vmarc** [comment]
In the mean while, the analysis logic that takes the new tagging (with _network:type=node_network_) into account has been activated.

The non-node-network-routes should now have disappeared from the reporting.

At the moment of the activation, not all node-network nodes and routes in Germany had received the new tagging. These nodes and routes are not recognized anymore, and as such have now disappeared from the reporting. Several hundreds of them still show up in another form, for example under _"RouteUnexpectedNode"_ (_"OnverwachteKnoopInRoute"_) when the node without the tag was added to a route relation with the tag.

For now only regional (rXn) nodes, routes and networks are processed. Support for lXn, nXn and iXn should follow in version 3.0.0 (currently under construction).

@pdelderson Thanks for submitting this issue. It would be good if you could look for remaining irregularities, and report here if you find any.

**Comment by pelderson** [comment]
Knooppuntwezen lijken helemaal niet meer gevonden te worden, terwijl de netwerkrelaties nog wel bestaan. Is dat voorsorteren op het uitfaseren van de "fysieke" netwerkrelaties ten gunste van de "administratieve" relaties? Dus dat alle nodes en routerelaties met het kenmerk "network:type=node_network" binnen een bepaalde administratieve grens samen een virtuele netwerkrelatie vormen? 
Op dit moment voeg ik tags en routes toe waarbij ik geen bron heb in welk netwerk ze vallen en of het verbindingsroutes zijn. Bij survey is het niet zichtbaar, en ook op de knooppuntroutesite (visitbrabant) niet, want die heeft die indeling helemaal niet. Op zich heb ik daar geen last van, maar ze worden nu denk ik helemaal niet gecheckt?

**Comment by vmarc** [comment]
@pelderson Kun je misschien enkele concrete nodes of routes aangeven die wezen zouden moeten zijn, maar die het niet zijn?

Ik ben zelf even op zoek gegaan in enkele van jou recente changesets. Ik vind daar een aantal nieuw aangemaakte routes die initieel wees zijn, maar die daarna door dvdhoven aan een netwerk toegevoegd zijn. Gaat het om deze routes?

Voor changeset [76615522](https://knooppuntnet.nl/nl/changeset/76615522/3745251) kun je onderaan de pagina zien dat er 7 nieuwe routes zijn toegevoegd, en dat deze herkend zijn als niet behorende tot een netwerk ("wees"). Gelijkaardig beeld (ook 7 nieuwe routes) in changeset [76614393](https://knooppuntnet.nl/nl/changeset/76614393/3745209).

Als je voor elk van deze routes de link volgt naar de route pagina, dan kun je daar zien dat ze werden toegevoegd aan netwerk "Moerdijk" (al dan niet ten onrechte?). Zie changeset [76634106](https://knooppuntnet.nl/nl/changeset/76634106/3745917), ongeveer halverwege de pagina onder _"Moerdijk"_ en _"Route wezen toegevoegd aan dit netwerk"_.

Rapportering aan de hand van administratieve grenzen is deels geimplementeerd in de ontwikkelingsomgeving, maar dit stuk is nog niet helemaal klaar en nog niet actief op de website. Daar gaat het probleem dus niet  liggen. De bedoeling zou denk ik initieel wel zijn om de nieuwe rapporting naast de bestaande netwerk gebaseerde rapportering te laten bestaan, om pas nadien te beslissen om de netwerk gebaseerde rapportering al dan niet te laten verdwijnen.

**Comment by pelderson** [comment]
Ah, ik had niet in de gaten dat iemand mijn zaagsporen aan het opruimen was!
Is het te laat om te zeggen "ik heb niks gezegd?"
Vr gr Peter Elderson


Op wo 6 nov. 2019 om 17:52 schreef vmarc <notifications@github.com>:

**Comment by vmarc** [comment]
@pelderson 

> Is het te laat om te zeggen "ik heb niks gezegd?"

Als je niets gezegd hebt, dan heb ik niets gehoord. ;)
Aarzel niet om het te melden als je nog zaken ziet waar je vragen bij hebt.

**Comment by pelderson** [comment]
Ik heb een item met je gedeeld:

knooppuntnet - Knooppuntplanner
https://docs.google.com/document/d/1jPpB4agz9zz6HV2_05hfPiWjJOT2nnjv0AtMGYtTz4o/edit?usp=sharing&invite=COuPsYMM&ts=5ec013a8

Dit is geen bijlage. Het item is online opgeslagen. Klik op de bovenstaande  
link om het item te openen.

Een link naar het google dokument knooppuntnet Planner. Kijken of dit  
werkt. Het is nog in opbouw en een beetje rommelig; ik heb er wat  
opmerkingen ingezet, misschien kan je daar vast eens naar kijken?
Als dit vanuit de planner opgeroepen moet worden, dan stel ik wel voor om  
het nog andersom op te bouwen.
- Met een heel kort aanwijzingenscherm  (quick reference) beginnen,
- dan de uitgebreide gebruiksaanwijzing (user tutorial), en
- dan pas de uitleg van knooppunten, OpenStreetMap en de achtergrond-links.
