### ISSUE TITLE
New network doesn't appear on map

### ISSUE THREAD

**Issue by alphensebezorger** [vmarc/knooppuntnet#66]
I recently added a new network for walking in the Netherlands to OSM. As expected, this network showed up in the list "Walking in the Netherlands - networks". The analysis seems to be working as well. However, somehow the [overview map](https://knooppuntnet.nl/en/map/rwn) doesn't show any routes or nodes in this network. Other maps on the site show similar behaviour.
Is manual intervention required to add new networks to the map, or is there another problem?

Concerned network:
[Wandelnetwerk Tholen](https://www.openstreetmap.org/relation/10313201)

**Comment by vmarc** [comment]
The new network was detected by the analysis logic, but the update of the tiles that contained the new network was still working with the old information. This issue has long been resolved in the mean while.
