### ISSUE TITLE
Extra substrings to be ignored in network names 

### ISSUE THREAD

**Issue by A67-A67** [vmarc/knooppuntnet#70]
In France the substring Réseau pédestre is used in [hiking networks](https://knooppuntnet.nl/nl/networks/fr/rwn), which should be ignored like [these substrings](https://github.com/vmarc/knooppuntnet/issues/55).

**Comment by vmarc** [comment]
Implemented in [v2.0.21.6](https://github.com/vmarc/knooppuntnet/releases/tag/v2.0.21.6).
