### ISSUE TITLE
Issue 5, a sorting error when forward and backward routes overlap, returned

### ISSUE THREAD

**Issue by A67-A67** [vmarc/knooppuntnet#71]
Issue #5 was about a route where the forward and backward routes were going in an 8-shape, where they overlapped in the middle. This issue was solved, but it has returned.

- [314-353](https://knooppuntnet.nl/nl/route/1245740) gives a sorting error
- [17-19](https://knooppuntnet.nl/nl/route/9637368) gives a sorting and an unjust segments error

**Comment by vmarc** [comment]
@A67-A67 thanks for reporting this problem. I will have a closer look.

**Comment by dvdhoven** [comment]
Nog 2 routes met dit probleem:
01-45 in Nijmegen: https://knooppuntnet.nl/nl/route/10015252
93-95 in Zuid Limburg: https://knooppuntnet.nl/nl/route/145281

**Comment by vmarc** [comment]
The problem has been resolved on experimental.knooppuntnet.nl (today not deployed on knooppunnet.nl yet):
- [314-353](https://experimental.knooppuntnet.nl/nl/analysis/route/1245740)
- [17-19](https://experimental.knooppuntnet.nl/nl/analysis/route/9637368)
- [01-45](https://experimental.knooppuntnet.nl/nl/analysis/route/10015252)
- [93-95](https://experimental.knooppuntnet.nl/nl/analysis/route/145281)

Case study [Issue71_OverlappingWays](https://github.com/vmarc/knooppuntnet/blob/develop/server/src/test/scala/kpn/server/analyzer/engine/analysis/caseStudies/Issue71_OverlappingWays.scala) reproduces the problem and solution.
