### ISSUE TITLE
Route planner - simplify points of interest user interface

### ISSUE THREAD

**Issue by vmarc** [vmarc/knooppuntnet#73]
Based on feedback from @pelderson (thanks!):

Today, the end user configuration of points of interests (pois) seems too complex and way too detailed for most users.

The existing configuration allows the user to determine at which zoom level pois become visible on the map, per poi-group and per individual poi-type.

Instead there could be a single switch to enable/disable this display of pois. The default could be to initially not show any pois in the route planner.

Perhaps the layer popup menu in the upper right corner of the map could be used: show separate poi layer and provide checkbox to enable/disable this layer. Perhaps still have separate layers for the different poigroups as defined today?

Depending on the map type (cycling, hiking, etc.) the pois that are shown could be different (for example: less emphasis on bicyle repair shops in the hiking map).

Perhaps the components that were built for the detailed can be recycled for a separate page that would still allow more advanced users to finetune their own poi profile.

**Comment by vmarc** [comment]
The poi configuration component has been taken out of the left sidebar.

Checkboxes to show/hide each poigroup have been added to the map layer popup menu on the right side of the map. There is also a checkbox to show/hide all pois in one go.

When the "Points of interest" option is unchecked, then the poigroupcheckboxes are disabled.

![pois-menu](https://user-images.githubusercontent.com/6596480/82078696-de52d580-96e1-11ea-844e-4540d3014b1a.png)

**Comment by pelderson** [comment]
Nice and simple for the end user!
