### ISSUE TITLE
Route planner - allow user to remove node marker

### ISSUE THREAD

**Issue by vmarc** [vmarc/knooppuntnet#74]
Based on feedback from @pelderson (thanks!):

It would be helpful during route planning to be able to remove intermediate node markers that were placed earlier.

Today removing a node marker is already supported: the user can drag an itermediate node marker over a neighboor node marker. The marker will disappear and the route will be recalculated without that interediate node.

This way of removing a marker is not immediately obvious to the user.

Options:

- better document this way of removing a marker

- include buttons (garbage can icon?) to remove user selected nodes in the route detail list in the left sidebar

- popup menu with remove option that opens when rightclicking on marker

- single-click on marker opens dialog to confirm deletion of the marker

**Comment by pelderson** [comment]
1. Dragging a marker A onto a neighbouring marker B appears to position both markers on the same network node. It looks like it's deleted, but you can drag the two markers separately to a different position! 
2. Option 5: Single-click on marker deletes the marker. Direct editing without confirmation is pretty common nowadays!

**Comment by vmarc** [comment]
Implemented in release v3.0.0-alpha-22: remove intermediate node markers through single-click. The route is recalculated. It is possible to use the Undo function to bring back the node marker and the original route.
