### ISSUE TITLE
Route planner - button to start planning from scratch

### ISSUE THREAD

**Issue by vmarc** [vmarc/knooppuntnet#75]
Based on feedback from @pelderson (thanks!):

It would be handy to have a button to wipe out all previous planning selections that have been made and start planning a new route from scratch.

**Comment by vmarc** [comment]
Reset action has been added in version 3.0.0-alpha-21.

The action is integrated in the undo/redo mechanism so that nothing is lost when the button is clicked unintentionally.

![reset](https://user-images.githubusercontent.com/6596480/82538644-5854e580-9b4c-11ea-8799-13b39ffb711d.png)

**Comment by pelderson** [comment]
Clever!
