### ISSUE TITLE
Route planner - reverse route

### ISSUE THREAD

**Issue by vmarc** [vmarc/knooppuntnet#81]
Reverse entire route. This is done surprisingly often, when after planning the route, the wind expectation is viewed!

**Comment by vmarc** [comment]
Implemented in release 3.0.0-alpha-23.

**Comment by pelderson** [comment]
De omkeerfunctie werkt niet meer, bij mij.

**Comment by vmarc** [comment]
@pelderson thanks for reporting this problem

Fixed in version 3.0.0-alpha-36.
