### ISSUE TITLE
Route planner - Quick access to other map types 

### ISSUE THREAD

**Issue by pelderson** [vmarc/knooppuntnet#87]
Something like this, below the layers icon?
![image](https://user-images.githubusercontent.com/38458314/82530481-af06f300-9b3d-11ea-99c3-ed3beb260486.png)
The current type is shown; hover over it to display the map types for selection.
Choosing a different one will discard current work and the chosen map type is displayed at the same focus and zoom.

**Comment by vmarc** [comment]
An earlier version of the route planner already contained buttons to switch between cycling, hiking, horse-riding, motorboat, canoe and inline-skating. These were removed in an attempt to make the overall userinterface simpler. Perhaps this was not a good idea. I have recycled the buttons in version 3.0.0-alpha-21. The actual actions behind the buttons still have to be implemented. 

![network-type-selector](https://user-images.githubusercontent.com/6596480/82542558-80dfde00-9b52-11ea-8cb7-464aefc693ba.png)

**Comment by pelderson** [comment]
Dat is snel! Deze knopjes maken het niet ingewikkelder, omdat de bedoeling zo vanzelfsprekend en duidelijk is. Acties: is het mogelijk om de route te bewaren als de user tussendoor naar een andere kaart gaat? Totdat-ie een nieuwe route begint op de nieuwe kaart. Anders moet er misschien een waarschuwing tussen.

**Comment by vmarc** [comment]
Implemented in release 3.0.0-alpha-24.

- planned route is preserved per network type
- also, the undo/redo history is preserved
