### ISSUE TITLE
Route planner - plan route via longer path

### ISSUE THREAD

**Issue by vmarc** [vmarc/knooppuntnet#89]
Currently the route planner always tries to find the shortest path between the nodes supplied by the user. In some exceptional cases this means that certain routes cannot be included in the planned route.

We need a way to allow the user to force the selection of such a route.

**Comment by vmarc** [comment]
Example 1:

We cannot include route 78-38 in the planned route (although this route is perhaps nicer to walk). The distance from 78 to 38 is shorter via nodes 27, 21 and 38, so this is path that the routeplanner is always selecting.

![route-issue-1](https://user-images.githubusercontent.com/6596480/83331461-e17bc300-a296-11ea-88a0-66949110ed1a.png)

**Comment by pelderson** [comment]
Two thoughts:

1. Optional preference (higher weight) for unpaved routes might solve it for this particular route. (That's a nice enhancement anyway!) 

2. Option to drag a Via marker or an intermediate section on to a node2node route.

Maybe a neat way to do that is to give every node2node route a "middle node", i.e a virtual node (small 'node' without a number?) that you can drag a via marker or a section to.

**Comment by vmarc** [comment]
Resolved in v3.0.0-alpha-34.

**Comment by pelderson** [comment]
Top!
