### ISSUE TITLE
Analysis - Collection edit (josm) for administrative area.

### ISSUE THREAD

**Issue by pelderson** [vmarc/knooppuntnet#90]
Without the network relation, you can't open a network for edit in JOSM. But the application has a collection of routes and nodes within the administrative area. Is it possible to create an Edit (josm)  link for this? Sort of what overpass turbo does with "export to josm" after a query?  
Although I am afraid a whole province would be too large anyway. A municipality would be a nice size for this.

**Comment by vmarc** [comment]
Implemented in server version 3.0.0-SNAPSHOT-alpha-21.

![bitmap](https://user-images.githubusercontent.com/6596480/83416969-bd002200-a421-11ea-83e0-62af8898d20e.png)

The application communicates the nodes and routes to JOSM via the remote control. It is JOSM that fetches the actual data from the OpenStreetMap api. In an attempt to not overburden the OSM api, the application includes a delay of 200 milliseconds between each route relation.  I am not sure if this was really needed.

The cancel button can be used to stop the transfer.

Loading the nodes is very fast (they are bulk loaded in batches of 50).

Loading the individual routes with their complete way structure takes a while. Loading the routes without the ways would be very fast.  But then it would be up to the JOSM user to download the additional data from within JOSM.

Perhaps some radio buttons that allow the user to decide to load nodes only, and/or routes with or without ways, would be useful?

**Comment by pelderson** [comment]
Every time I can think of, I did not need the ways, just the nodes and/or the nodes plus the relations. Loading the ways in JOSM for a selection of routes is easy enough. A radio button sounds ok. 
My default would be nodes plus relations without the ways.

**Comment by vmarc** [comment]
Implemented in release 3.0.0-alpha-28

![edit](https://user-images.githubusercontent.com/6596480/83942833-85b1bc80-a7f7-11ea-8511-a5aff96445a7.png)

**Comment by pelderson** [comment]
👍
