### ISSUE TITLE
Route planner - Output - handle colour routes 

### ISSUE THREAD

**Issue by pelderson** [vmarc/knooppuntnet#93]
In some networks the arrows on the nodes do not point to the adjacent nodes, but to route colours instead. In words, the indication is: from here, follow purple to the right, blue straight ahead and yellow to the left". When planning/routing, this makes little difference. But if the output only mentions numbers, the user has a problem, because at a node he doesn't know where the next number is! He needs the colour to follow. 
This system is odd, but it's not going to change any time soon, so I think the planner should handle it.

Simple solution: The result display and the output should show the colour (tag colour=*) between the numbers. Like this: G65-blue-G78-yellow-G79-yellow-G80-yellow-G90-purple-G91
Or a bit more compact: only show the colour where it changes.
G65-blue-G78-yellow-G79-G80-G90-purple-G91

In the compact pdf and node strip pdf the colour could be displayed next to the distance.

In the navigation istructions pdf the colour could be shown to the right of the node icon:\
G65 follow blue
....
....
G78 follow yellow 
...

Maybe in the future the colour itself could be used onscreen and in the output, but that's tricky because the colour tag is free format text and can have text such as "white-over-red" or dutch coulour names. 

This handling could be generic because in regular node networks no colour tag is present. If colour is important, de tag is there and should be shown in the output.

**Comment by pelderson** [comment]
Voorbeeld: https://twente.routemaker.nl/routes/nummer/77202  Ik weet niet hoe zij het doen, maar ze hebben het wel opgelost - voor Twente dan. De landelijke planner van Wandelnet kan het niet.

**Comment by vmarc** [comment]
Partially implemented in version v3.0.0-alpha-29.
- colours are included in compact, detailed and instructions output on screen, and instructions pdf
- colours still missing in node and nodestrip pdf's
- no colours in map yet

Open question is how to represent paved/unpaved surface while also showing the route colour.

Example [route plan](https://experimental.knooppuntnet.nl/nl/map/hiking#mtmik8-511h2l-1mjddt5-rs2ro-153iacc).

**Comment by vmarc** [comment]
Compact view.

![compact](https://user-images.githubusercontent.com/6596480/84077189-3a560480-a9d7-11ea-8877-64b403ff54a6.png)

**Comment by vmarc** [comment]
Detailed view.


![detailed](https://user-images.githubusercontent.com/6596480/84077242-4f329800-a9d7-11ea-989a-c233f67e722d.png)

**Comment by vmarc** [comment]
Instructions view.

![instructies](https://user-images.githubusercontent.com/6596480/84077277-640f2b80-a9d7-11ea-9dc9-d21f1c3a6148.png)

**Comment by pelderson** [comment]
I wouldn't know about the map - I think just keep the basic implementation in the result text, hopefully the node strip pdf can be adapted as well, and that's enough for the moment. 
Great job, once again!

**Comment by dvdhoven** [comment]
Dit is echt groots!
Ik ben ooit met die kleuren begonnen voor een mogelijke routeplanner en nu zie ik het toepassen.
Geweldig!

Klein punt, ik heb purple gebruikt voor de routekleur paars, is het mogelijk purple in paars te vertalen?

**Comment by pelderson** [comment]
Mijn idee: de tag moet de standaard kleuraanduidingen gebruiken, dan kan je die volgens de locale vertalen. Wat niet standaard is, blijft dan onvertaald.

**Comment by dvdhoven** [comment]
Ik begrijp niet wat je bedoeld.
In Overijssel worden voor de lokale rondjes 6 kleuren gebruikt:
blauw
groen
geel
oranje
paars
rood
Kijkend naar de uitleg van het osmc:symbol op Waymarked Trails heb ik daarvoor de engelse kleurnamen gebruikt:
blue
green
yellow
orange
purple
red
Ik zie dan dat die namen in het Nederlands worden vertaald behalve purple, dat wordt purper genoemd, alleen dat is een kleurnaam, die in Nederland niet veel wordt gebruikt. Paars wel, dan is het toch logisch dat ik om een vertaling in paars vraag?
Anders staan mensen straks buiten te kijken, purper? purper? wat is dat?

**Comment by pelderson** [comment]
Ok, dus goed gedaan! Zoals je al zei, dan hoort de NL vertaling "paars" te zijn, denk ik ook. Maar purper bestaat ook in het Nederlands, hoor, het is eeuh een soort van paars! IN NL niet zo gebruikelijk, misschien in VL wel?

**Comment by pelderson** [comment]
In the example, I take it that "blauw-groen-rood" is in fact tagged as colour=blue;green;red ?
I think for this purpose only the first colour of the semicolon-separated value list is relevant. It says you go to the next node on your route by following blue. It does not really matter that green and red happen to follow the same route.

It's different when a two-coloured symbol has to be followed, e.g. white-red. In that case, the colour value could be "white-red", and both should be displayed.

I have seen also colour=white-over-red many times in GR / LAW routes, in an attempt to describe the symbol, but I think that is wrong (should be in the symbol tag). I don't know how many node2node routes have this, I think not that many.

**Comment by dvdhoven** [comment]
Het is wel handig om alle kleurtjes, dus alle routes te vermelden.
Soms is het twijfelen in het veld en zo weet je zeker dat je de goede route hebt.
Bovendien als je zoals in jouw voorbeeld alleen de blauwe vermeld en er zijn nog 2 andere kleuren kan het verwarrend zijn. Zelf zou ik heftig gaan twijfelen. Er staat dat ik de blauwe moet nemen, maar ik ziie ook nog groen en rood. Heb ik dan wel de goede?
Mijn voorkeur is om alle kleuren in de tag te noemen.

**Comment by pelderson** [comment]
En de tweekleurenroutes die een stukje LAW volgen?

**Comment by dvdhoven** [comment]
Daar moeten we het nog over hebben; daar was ik nog niet uit
Nu begrijp ik je punt. Dan moet er iets anders tussen de kleuren dan een streepje
Of de 2 kleur routes moeten iets anders krijgen dan een streepje tussen de kleuren.
Zelf zat ik te denken aan een combi,: vermelden van welke 2kleur routes je krijgt en een tekstveld met de naam of namen van de 2kleur route
Alleen moet daar dan een tag voor verzonnen worden.
De 2kleur routes hebben allemaal een naam, die op de bordjes staat. Zie de foto in het topic in het forum

**Comment by pelderson** [comment]
Dus misschien maar gewoon de kleurtjes taggen zoals nu, met puntkomma's ertussen en dan ook zo weergeven, en de tweekleurenroutes taggen met een streepje ertussen en ook die zo weergeven? Dat is wel zo eenvoudig.

**Comment by pelderson** [comment]
Het zijn er denk ik niet zo veel, maar hier is er eentje zonder colour-tag, die via een LAW (wit-rood)  loopt: https://hiking.waymarkedtrails.org/#route?id=7763917 . Zullen we die [colour=white-red] taggen?

**Comment by dvdhoven** [comment]
Ja doe maar

Vriendelijke groeten,
Dick van den Hoven

Op 9 jun. 2020 21:35 schreef "pelderson" <notifications@github.com>:
>
> Het zijn er denk ik niet zo veel, maar hier is er eentje zonder
colour-tag, die via een LAW (wit-rood) loopt:
https://hiking.waymarkedtrails.org/#route?id=7763917 . Zullen we die
[colour=white-red] taggen?

**Comment by vmarc** [comment]
@dvdhoven en @pelderson dank voor jullie bijdragen rond de routekleuren

In versie 3.0.0-alpha-30 wordt _"purple"_ ondertussen vertaald naar _"paars"._

Purper wordt inderdaad misschien meer gebruikt in Vlaanderen, hoewel die kleur hier toch ook wel vaker paars genoemd wordt denk ik. Zowel _"violet"_ als _"purple"_ worden nu vertaald naar _"paars"._

De kleuren die niet voorkomen in de [kleur-vertalingen in poeditor](https://poeditor.com/projects/po_edit?order=terms_asc&filter=t&per_page=100&id=331365&id_language=41&search=route.colour) blijven onvertaald.

Volgend overzicht toont welke waarden voor de tag _"colour"_ gevonden worden in alle knooppuntroutes in de knooppuntnet database (de eerste kolom geeft aan in hoeveel routes gegeven waarde voorkomt).

[colours.txt](https://github.com/vmarc/knooppuntnet/files/4754439/colours.txt)

Volgende routes verdienen misschien nog nader onderzoek:

| route id | colour tag value
|:---|:---
| 10479121 | ;red
| 10537642 | blue;yeloow
| 10653526 |  ;yellow
| 10661811 | blueg;reen
| 10661812 | blueg;reen;red
| 10781646 | blueorange;;red
| 10808769 | orangered
| 10809943 | green;red;;yellow
| 10811793 | red;;yellow
| 10811794 | red;;yellow
| 10866357 | green;orange;ýellow
| 10866359 | green;red;ýellow
| 10866393 | ýellow
| 10866394 | orange;ýellow
| 1729061 | rcn
| 5205817 | green;orangepurple;;red
| 6800864 | ;red
| 6800869 | green;orange';purple
| 7709671 | green;orange';purple
| 7810228 | blue,green;orange
| 7811256 | blue;green;yellow;ornge
| 7827324 | red;yelliow
| 7832016 | green;orang';red
| 7922396 | blue;pgreen;purple;yellow
| 8430283 | redyellow
| 8898417 | blue, purplr;yellow

Verdere aanpassingen in de node en node-strip pdf's komen er nog aan.

**Comment by pelderson** [comment]
Marc, je bent goud waard!

**Comment by vmarc** [comment]
Resolved in v3.0.0-alpha-35.

Colours or colourcombinations that are separated by a semicolon in the _colour_ tag in the route relation, are now separated by a forward slash in the output (instead of the dash character as it used to be). This is to make is easier to distinguish from the dash character that is used in colourcombinations.

![screenshot](https://user-images.githubusercontent.com/6596480/89098921-e9b5c300-d3eb-11ea-8c8e-afda13834bf8.png)

**Comment by pelderson** [comment]
Hm... zo is het nog steeds niet makkelijk voor de gebruiker. Is M38-39 nou oranje+wit en rood, of oranje en wit+rood? Is M41-M48 nou blauw,wit+rood, wit+paars, of blauw+wit, rood+wit en paars? n NL wordt de slash ibij het schrijven gebruikt voor of, en (kombinatie), en en/of.
Ik vind het dan duidelijker om gewoon de semicolon aan te houden:

M38 oranje;wit-rood M39 rood;wit-rood M41 blauw;wit-rood;wit-paars

**Comment by vmarc** [comment]
> Ik vind het dan duidelijker om gewoon de semicolon aan te houden:

Of het woordje _"of"_ (_"or"_, _"oder"_)?

**Comment by pelderson** [comment]
> > Ik vind het dan duidelijker om gewoon de semicolon aan te houden:
> 
> Of het woordje _"of"_ (_"or"_, _"oder"_)?

Helemaal duidelijk natuurlijk, als de lengte geen probleem is.

**Comment by vmarc** [comment]
Adapted in v3.0.0-alpha-36: using _" or "_ instead of _"/"_.

![map](https://user-images.githubusercontent.com/6596480/89122420-41752c80-d4c7-11ea-9431-48c9cb4ffa02.png)
