### ISSUE TITLE
Verwijder foutmeldingen onbekend netwerk in wandelnetwerken Nederland

### ISSUE THREAD

**Issue by dvdhoven** [vmarc/knooppuntnet#94]
een aantal dagen geleden heeft een mapper per ongeluk 2 rwn routes ingevoerd met type=network.
Dat is hersteld, maar nu blijven er foutmeldingen hangen in Wandelen Nederland:
NetwerkZondernaam 2x
Onverwachte weg 8x

Kunnen deze verwijderd worden?
Alvast hartelijk dank

Groet,
Dick van den Hoven

**Comment by vmarc** [comment]
@dvdhoven dank voor de melding

Ik heb de netwerken die hiervoor aangemaakt werden manueel uit de analysedatabase verwijderd.

Ik laat dit issue voorlopig open en aangemerkt als _"bug"_ omdat de netwerken eigenlijk automatische op non-actief gezet hadden moeten worden waardoor ze niet meer in de raportering hadden mogen voorkomen.

Mogelijk is dit gerelateerd aan #49, #50 en #51.

**Comment by vmarc** [comment]
Resolved in release v4.0 (currently only on experimental), see #238.
